"""Declarations: the monthly DSN generated by Silae, their content, and declaration states.

`v1/InfosDeclaration/ListeDSNMensuelles`, `…/AcquisitionContenuPartielDSN`,
`v1/EtatDeclaration/EtatDeclarations`.
"""
from __future__ import annotations

from typing import Any, Optional, Sequence

from ..periodes import mois, periode_date, periode_datetime

#: `typeDeclaration` values documented for `EtatDeclarations`.
TYPES_DECLARATION = ("DECLARATION", "DADSU", "DUE", "DN-AC-AE", "DSIJ")
#: `typeDSN`: 0 not assigned, 1 Net-Entreprises, 2 MSA, 3 with PASRAU, 4 DSM Monaco.
TYPES_DSN = (0, 1, 2, 3, 4)


class _DeclarationsMixin:

    def list_dsn_mensuelles(self, numero_dossier: str, *, periode: str) -> Any:
        """The monthly DSN generated for a pay month: establishment, body code,
        affiliation number, `typeDSN`, SIRET, `fraction`, send date — the coordinates
        `contenu_partiel_dsn` needs."""
        return self.call(
            "v1/InfosDeclaration/ListeDSNMensuelles",
            {"periode": periode_date(periode), "numeroDossier": numero_dossier},
            numero_dossier=numero_dossier,
        )

    def contenu_partiel_dsn(
        self,
        numero_dossier: str,
        *,
        periode: str,
        etablissement: str,
        type_dsn: int,
        fraction: int,
        segments: Optional[Sequence[str]] = None,
        code_organisme: Optional[str] = None,
        numero_affiliation: Optional[str] = None,
    ) -> dict:
        """The content of one DSN — whole, or only the blocks named in `segments` —
        decoded from base64 as `{"data": bytes, "filename", "mimetype"}`. Silae does not
        document the encoding of the decoded content.

        Args:
            etablissement: internal name of the establishment (`etablissement` of
                `list_dsn_mensuelles`).
            type_dsn, fraction, code_organisme, numero_affiliation: as listed by
                `list_dsn_mensuelles` for that DSN.
            segments: blocks to read, as "S21.G00.30".
        """
        if not etablissement:
            raise ValueError("etablissement (internal name) is required")
        if type_dsn not in TYPES_DSN:
            raise ValueError(f"type_dsn: one of {list(TYPES_DSN)}")
        body: dict = {"nomInterneEtablissement": etablissement, "typeDSN": int(type_dsn),
                      "fraction": int(fraction), "periode": periode_date(periode),
                      "numeroDossier": numero_dossier}
        if segments is not None:
            if isinstance(segments, str) or not all(isinstance(s, str) and s for s in segments):
                raise ValueError('segments: a list of block names, e.g. ["S21.G00.30"]')
            body["segments"] = list(segments)
        if code_organisme is not None:
            body["codeOrganisme"] = code_organisme
        if numero_affiliation is not None:
            body["numeroAffiliation"] = numero_affiliation
        rendu = self.call("v1/InfosDeclaration/AcquisitionContenuPartielDSN", body,
                          numero_dossier=numero_dossier)
        an, mo = mois(periode)
        nom = f"silae-dsn-{numero_dossier}-{an:04d}-{mo:02d}-f{int(fraction)}.dsn"
        return self._document(rendu, "contenuPartiel", nom, "application/octet-stream")

    def etat_declarations(self, numero_dossier: str, *, type_declaration: str,
                          periode: Optional[str] = None) -> Any:
        """Declarations of a dossier and their state: ADS number, date, recipient,
        obsolete/test flags, and the returns received (nature, state).

        Args:
            type_declaration: DECLARATION, DADSU, DUE, DN-AC-AE or DSIJ.
            periode: pay month, required for DECLARATION (reference month for DN-AC-AE).
        """
        if type_declaration not in TYPES_DECLARATION:
            raise ValueError(f"type_declaration: one of {list(TYPES_DECLARATION)}")
        if type_declaration == "DECLARATION" and periode is None:
            raise ValueError("periode is required for type_declaration DECLARATION")
        body: dict = {"typeDeclaration": type_declaration, "numeroDossier": numero_dossier}
        if periode is not None:
            body["periode"] = periode_datetime(periode)
        rendu = self.call("v1/EtatDeclaration/EtatDeclarations", body,
                          numero_dossier=numero_dossier)
        # Silae documents a null return as "no declaration found for the period".
        return {"etatDeclarations": []} if rendu is None else rendu
