"""Tavily client — web search and page reading tailored for an agent (tavily.com).

REST API, Bearer auth `tvly-…`. Four surfaces, all **synchronous**:
- **search**: web search → optional synthesized answer + cited excerpts,
  filterable by topic (general/news/finance), period, country, language.
- **extract**: N URLs → clean content (markdown/text), reranked by an intent.
- **crawl**: site traversal guided in natural language → page content.
- **map**: discovery of a site's URLs (without content).

Cost (Tavily credits): search 1 (2 in `advanced`); extract 1 per 5 URLs (2 in
`advanced`); crawl/map 1 per 10 pages (2 with `instructions` or `advanced`).
`include_usage=True` is always sent: the response carries `usage.credits`.

Request bodies go to the API as is (`None`s are removed to
let Tavily apply ITS defaults) — see https://docs.tavily.com.

Requires: requests
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

import requests

from ..common.credentials import require
from ..common import raise_for_upstream


class TavilyClient:
    """Client Tavily (https://api.tavily.com), auth Bearer `tvly-…`."""

    BASE_URL = "https://api.tavily.com"

    def __init__(self, api_key: str = None):
        """
        Args:
            api_key: Tavily key.
        """
        self.api_key = require(api_key, "TAVILY_API_KEY")
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        })

    # --- transport ----------------------------------------------------------

    def _request(self, method: str, path: str, *, timeout: int = 60, **kwargs) -> Dict[str, Any]:
        # `timeout` (int) = READ budget only; connect is bounded to 10 s
        # (repo convention (connect, read) — an unreachable host must not
        # block for 160 s, the length of the crawl budget).
        resp = self.session.request(method, f"{self.BASE_URL}{path}",
                                    timeout=(10, timeout), **kwargs)
        raise_for_upstream(resp, service="tavily")
        return resp.json() if resp.content else {}

    @staticmethod
    def _compact(body: Dict[str, Any]) -> Dict[str, Any]:
        """Removes keys set to None — the API then applies ITS defaults."""
        return {k: v for k, v in body.items() if v is not None}

    # --- search -------------------------------------------------------------

    def search(
        self,
        query: str,
        search_depth: Optional[str] = None,
        topic: Optional[str] = None,
        max_results: Optional[int] = None,
        chunks_per_source: Optional[int] = None,
        time_range: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        include_answer: Optional[Union[bool, str]] = None,
        include_raw_content: Optional[Union[bool, str]] = None,
        include_images: Optional[bool] = None,
        include_domains: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        country: Optional[str] = None,
        language: Optional[str] = None,
        timeout: int = 60,
    ) -> Dict[str, Any]:
        """POST /search — web search. 1 credit (`advanced`: 2).

        Args:
            query: search terms (max 400 characters).
            search_depth: `basic` (default) | `advanced` | `fast` | `ultra-fast`.
            topic: `general` (default) | `news` | `finance`.
            max_results: 0-20 (default 5).
            chunks_per_source: 1-3 excerpts per source (`advanced` only).
            time_range: `day` | `week` | `month` | `year`.
            start_date / end_date: `YYYY-MM-DD` bounds.
            include_answer: `False` (default) | `True`/`"basic"` | `"advanced"` —
                synthesized answer generated by Tavily from the results.
            include_raw_content: `False` (default) | `"markdown"` | `"text"` —
                full content of each page (heavy).
            include_domains / exclude_domains: lists of domains.
            country: country name in English (`france`) — boosts that country.
            language: ISO 639-1 code (`fr`).
            timeout: local HTTP timeout (seconds).

        Returns: `{query, answer?, results: [{title, url, content, score,
            raw_content?, favicon?}], images?, response_time, usage: {credits},
            request_id}`.
        """
        body = self._compact({
            "query": query,
            "search_depth": search_depth,
            "topic": topic,
            "max_results": max_results,
            "chunks_per_source": chunks_per_source,
            "time_range": time_range,
            "start_date": start_date,
            "end_date": end_date,
            "include_answer": include_answer,
            "include_raw_content": include_raw_content,
            "include_images": include_images,
            "include_domains": include_domains,
            "exclude_domains": exclude_domains,
            "country": country,
            "language": language,
            "include_usage": True,
        })
        return self._request("POST", "/search", json=body, timeout=timeout)

    # --- extract ------------------------------------------------------------

    def extract(
        self,
        urls: Union[str, List[str]],
        query: Optional[str] = None,
        extract_depth: Optional[str] = None,
        chunks_per_source: Optional[int] = None,
        format: Optional[str] = None,
        include_images: Optional[bool] = None,
        include_favicon: Optional[bool] = None,
        timeout_s: Optional[float] = None,
        timeout: int = 90,
    ) -> Dict[str, Any]:
        """POST /extract — clean content of N URLs. 1 credit per 5 URLs (`advanced`: 2).

        Args:
            urls: one URL or a list (max 20).
            query: intent used to rerank the excerpts.
            extract_depth: `basic` (default) | `advanced` (tables, dynamic content).
            chunks_per_source: 1-5 excerpts per source (with `query`).
            format: `markdown` (default) | `text`.
            timeout_s: budget on Tavily's side (1-60 s).
            timeout: local HTTP timeout (seconds).

        Returns: `{results: [{url, raw_content, images?, favicon?}],
            failed_results: [{url, error}], response_time, usage: {credits},
            request_id}`.
        """
        body = self._compact({
            "urls": urls,
            "query": query,
            "extract_depth": extract_depth,
            "chunks_per_source": chunks_per_source,
            "format": format,
            "include_images": include_images,
            "include_favicon": include_favicon,
            "timeout": timeout_s,
            "include_usage": True,
        })
        return self._request("POST", "/extract", json=body, timeout=timeout)

    # --- crawl / map --------------------------------------------------------

    def _site_body(self, url: str, instructions, max_depth, max_breadth, limit,
                   select_paths, select_domains, exclude_paths, exclude_domains,
                   allow_external, timeout_s) -> Dict[str, Any]:
        return self._compact({
            "url": url,
            "instructions": instructions,
            "max_depth": max_depth,
            "max_breadth": max_breadth,
            "limit": limit,
            "select_paths": select_paths,
            "select_domains": select_domains,
            "exclude_paths": exclude_paths,
            "exclude_domains": exclude_domains,
            "allow_external": allow_external,
            "timeout": timeout_s,
            "include_usage": True,
        })

    def crawl(
        self,
        url: str,
        instructions: Optional[str] = None,
        max_depth: Optional[int] = None,
        max_breadth: Optional[int] = None,
        limit: Optional[int] = None,
        select_paths: Optional[List[str]] = None,
        select_domains: Optional[List[str]] = None,
        exclude_paths: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        allow_external: Optional[bool] = None,
        extract_depth: Optional[str] = None,
        chunks_per_source: Optional[int] = None,
        format: Optional[str] = None,
        include_images: Optional[bool] = None,
        include_favicon: Optional[bool] = None,
        timeout_s: Optional[float] = None,
        timeout: int = 160,
    ) -> Dict[str, Any]:
        """POST /crawl — traversal of a site with content. **Synchronous**.
        1 credit per 10 pages (2 with `instructions` or `extract_depth=advanced`).

        Args:
            url: root URL.
            instructions: natural-language instruction ("the product and pricing pages").
            max_depth: 1-5 (default 1). max_breadth: 1-500 links per level (default 20).
            limit: page cap (default 50) — first protection against a
                surprise bill.
            select_paths / select_domains / exclude_paths / exclude_domains: regex.
            allow_external: follow external links (API default: true).
            extract_depth: `basic` (default) | `advanced`.
            format: `markdown` (default) | `text`.
            timeout_s: budget on Tavily's side (10-150 s).
            timeout: local HTTP timeout (seconds).

        Returns: `{base_url, results: [{url, raw_content, favicon?}],
            response_time, usage: {credits}, request_id}`.
        """
        body = self._site_body(url, instructions, max_depth, max_breadth, limit,
                               select_paths, select_domains, exclude_paths,
                               exclude_domains, allow_external, timeout_s)
        body.update(self._compact({
            "extract_depth": extract_depth,
            "chunks_per_source": chunks_per_source,
            "format": format,
            "include_images": include_images,
            "include_favicon": include_favicon,
        }))
        return self._request("POST", "/crawl", json=body, timeout=timeout)

    def map_site(
        self,
        url: str,
        instructions: Optional[str] = None,
        max_depth: Optional[int] = None,
        max_breadth: Optional[int] = None,
        limit: Optional[int] = None,
        select_paths: Optional[List[str]] = None,
        select_domains: Optional[List[str]] = None,
        exclude_paths: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        allow_external: Optional[bool] = None,
        timeout_s: Optional[float] = None,
        timeout: int = 160,
    ) -> Dict[str, Any]:
        """POST /map — URLs of a site, without content. 1 credit per 10 pages.

        Same traversal arguments as `crawl` (without the content options).

        Returns: `{base_url, results: [url, …], response_time, usage: {credits},
            request_id}`.
        """
        body = self._site_body(url, instructions, max_depth, max_breadth, limit,
                               select_paths, select_domains, exclude_paths,
                               exclude_domains, allow_external, timeout_s)
        return self._request("POST", "/map", json=body, timeout=timeout)
