"""Nextmotion External API client (https://api.nextmotion.net/open_api/) —
practice-management software for aesthetic-medicine clinics.

Reference: https://api.nextmotion.net/open_api/docs/redoc (OpenAPI 3.0.3 served
at `/open_api/docs/schema`, read 2026-09-17). Paths, query parameters, bodies
and envelopes come from that spec.

Auth is a static API key sent as `Authorization: Bearer {api_key}`. A key is
generated by a user of the web app (Settings → API Keys), acts as that user,
and never expires until rerolled or deleted.

This module carries construction and transport; the calls live in the
`_api/` mixins, one per family: clinics & staff, calendar, service catalogue,
sales (quotes, invoices, payments, statistics, stock), CRM & settings.

## Scope of this client

The administrative side of a clinic, read — plus two calendar writes
(rescheduling and deleting an appointment).

The API also serves medical content — patient records and lists, medical
history, photos and media, prescriptions, consent forms, clinical treatments,
consultations, visits (clinical notes), health survey forms, post-treatment
follow-up configuration — and a chat whose contacts are patients. **None of
those endpoints has a method here.** Neither do the technical endpoints (VPS,
shell runs, AI-assistant skills). The one per-patient method is
`get_patient_stats`: financial totals and visit dates, by patient id.

⚠️ Some in-scope responses still EMBED personal data: an appointment, a
journey, a quote, an invoice or a payment carries a nested `patient` object
(birth date, gender, doctor comments, photograph…), an appointment request
and a lead carry the requester's name, email and phone, and many carry
free-text fields (`notes`, `free_text`, `details`, event titles). This client
returns responses as the API sends them; reducing them is the caller's
decision. Search parameters that match on a person's name (`search` on leads
and journeys, `order=patient_name`) are deliberately not exposed.

## Protocol facts that shape a caller

- Every list is paginated by `limit` (1-100, default 50) and `offset`, and
  answers `{count, next, previous, data: [...]}`. Detail endpoints answer
  `{data: {...}}`. Errors answer `{errors: [{code, message}]}`. A few lists
  are NOT paginated (statistics, user accounting distributions): `{data}`.
- Almost every resource hangs under a clinic: `list_clinics` gives the ids.
- `list_invoices` accepts no filter at all (no date, no patient), and the
  order of the list is not documented.
- The product stock is not linked to invoices nor to treatments: no endpoint
  says which lot an invoice consumed.
- A 403 `non_employee_access_denied` means the key's user is not an employee
  of that clinic.
- `reschedule_appointment` needs a `visit_type_opening_hour` id and its
  `time_slot`, both read from `search_time_slots`.
- Identifiers are UUIDs; the client refuses anything else before building a
  path, so an id can never rewrite the URL.
- Booleans travel as `true`/`false`; list filters as repeated parameters.
- Rate limits: none published; a 429 surfaces as `UpstreamHTTPError` like any
  other non-2xx — not retried here.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import requests

from ...config import require_secret
from ..common import raise_for_upstream
from ._api import _CalendarMixin, _CatalogMixin, _ClinicsMixin, _CrmMixin, _SalesMixin
from ._http import _page, _query

_HTTP_TIMEOUT = (10, 60)  # (connect, read) — never an unbounded wait
_BASE_URL = "https://api.nextmotion.net/open_api"


class NextmotionClient(_ClinicsMixin, _CalendarMixin, _CatalogMixin, _SalesMixin,
                       _CrmMixin):
    """Nextmotion External API client, Bearer API key."""

    BASE_URL = _BASE_URL

    def __init__(self, api_key: Optional[str] = None):
        """
        Args:
            api_key: Nextmotion API key (or secret `NEXTMOTION_API_KEY`),
                generated in the web app under Settings → API Keys.
        """
        self.api_key = api_key or require_secret("NEXTMOTION_API_KEY")
        self.session = requests.Session()
        # The key travels in a HEADER, never in the query string.
        self.session.headers["Authorization"] = f"Bearer {self.api_key}"
        self.session.headers["Accept"] = "application/json"

    # ------------------------------------------------------------------
    # transport
    # ------------------------------------------------------------------

    def _request(self, method: str, path: str, *,
                 params: Optional[Dict[str, Any]] = None,
                 json_body: Any = None) -> Any:
        resp = self.session.request(
            method, f"{self.BASE_URL}{path}", params=_query(params or {}),
            json=json_body, timeout=_HTTP_TIMEOUT)
        raise_for_upstream(resp, service="nextmotion")
        if resp.status_code == 204 or not (resp.content or b"").strip():
            return None
        return resp.json()

    def _get(self, path: str, **params: Any) -> Any:
        return self._request("GET", path, params=params)

    def _list(self, path: str, limit: int, offset: int, **filters: Any) -> Any:
        return self._request("GET", path, params={**_page(limit, offset), **filters})
