"""Nextmotion External API client (https://api.nextmotion.net/open_api/) —
practice-management software for aesthetic-medicine clinics.

Reference: https://api.nextmotion.net/open_api/docs/redoc (OpenAPI 3.0.3 served
at `/open_api/docs/schema`, read 2026-09-17). Paths, query parameters, bodies
and envelopes below come from that spec.

Auth is a static API key sent as `Authorization: Bearer {api_key}`. A key is
generated by a user of the web app (Settings → API Keys), acts as that user,
and never expires until rerolled or deleted.

## Scope of this client

The administrative side of a clinic only: the authenticated user, clinics,
practitioners, the calendar (appointments, free time slots, rescheduling,
deletion), the service catalogue (visit types, categories, sub-types,
treatment types, pricings), quotes and invoices, and — read only — the
clinic's product stock (lots, expiry dates, stock levels).

The API also serves medical content — patient records, medical history,
photos and media, prescriptions, consent forms, clinical treatments and
consultations. **None of those endpoints has a method here.**

⚠️ Some in-scope responses still EMBED patient data: an appointment, a quote
or an invoice carries a nested `patient` object (birth date, gender, doctor
comments, photograph…), and free-text fields (`notes`, `free_text`,
`details`). This client returns responses as the API sends them; reducing
them is the caller's decision.

## Protocol facts that shape a caller

- Every list is paginated by `limit` (1-100, default 50) and `offset`, and
  answers `{count, next, previous, data: [...]}`. Detail endpoints answer
  `{data: {...}}`. Errors answer `{errors: [{code, message}]}`.
- Almost every resource hangs under a clinic: `list_clinics` gives the ids.
- `list_invoices` accepts no filter at all (no date, no patient), and the
  order of the list is not documented.
- The product stock is not linked to invoices nor to treatments: no endpoint
  says which lot an invoice consumed. A product row embeds its catalogue
  entry (`global_product`: name, brand), so naming a lot needs no second call.
- A 403 `non_employee_access_denied` means the key's user is not an employee
  of that clinic.
- `reschedule_appointment` needs a `visit_type_opening_hour` id and its
  `time_slot`, both read from `search_time_slots`.
- Identifiers are UUIDs; the client refuses anything else before building a
  path, so an id can never rewrite the URL.
- Rate limits: none published; a 429 surfaces as `UpstreamHTTPError` like any
  other non-2xx — not retried here.
"""
from __future__ import annotations

import re
from typing import Any, Dict, Optional

import requests

from ...config import require_secret
from ..common import raise_for_upstream

_HTTP_TIMEOUT = (10, 60)  # (connect, read) — never an unbounded wait
_BASE_URL = "https://api.nextmotion.net/open_api"
_UUID = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")
_MAX_LIMIT = 100


def _clean(params: Dict[str, Any]) -> Dict[str, Any]:
    """Drops `None` values — an omitted kwarg must not become the literal
    string 'None' in the querystring, nor a null in a JSON body."""
    return {k: v for k, v in params.items() if v is not None}


def _id(value: Any, name: str) -> str:
    """A path identifier must be a UUID (the spec types every one of them so).
    Anything else — empty, `../`, a slash — is refused before the URL exists."""
    text = str(value) if value is not None else ""
    if not _UUID.fullmatch(text):
        raise ValueError(f"{name} doit être un UUID — reçu {value!r}.")
    return text


def _page(limit: int, offset: int) -> Dict[str, int]:
    if not 1 <= limit <= _MAX_LIMIT:
        raise ValueError(f"limit doit être entre 1 et {_MAX_LIMIT} — reçu {limit}.")
    if offset < 0:
        raise ValueError(f"offset doit être >= 0 — reçu {offset}.")
    return {"limit": limit, "offset": offset}


class NextmotionClient:
    """Nextmotion External API client, Bearer API key."""

    BASE_URL = _BASE_URL

    def __init__(self, api_key: Optional[str] = None):
        """
        Args:
            api_key: Nextmotion API key (or secret `NEXTMOTION_API_KEY`),
                generated in the web app under Settings → API Keys.
        """
        self.api_key = api_key or require_secret("NEXTMOTION_API_KEY")
        self.session = requests.Session()
        # The key travels in a HEADER, never in the query string.
        self.session.headers["Authorization"] = f"Bearer {self.api_key}"
        self.session.headers["Accept"] = "application/json"

    # ------------------------------------------------------------------
    # transport
    # ------------------------------------------------------------------

    def _request(self, method: str, path: str, *,
                 params: Optional[Dict[str, Any]] = None,
                 json_body: Any = None) -> Any:
        resp = self.session.request(
            method, f"{self.BASE_URL}{path}", params=_clean(params or {}),
            json=json_body, timeout=_HTTP_TIMEOUT)
        raise_for_upstream(resp, service="nextmotion")
        if resp.status_code == 204 or not (resp.content or b"").strip():
            return None
        return resp.json()

    def _get(self, path: str, **params: Any) -> Any:
        return self._request("GET", path, params=params)

    def _list(self, path: str, limit: int, offset: int, **filters: Any) -> Any:
        return self._request("GET", path, params={**_page(limit, offset), **filters})

    # ================================================================
    # Account
    # ================================================================

    def get_me(self) -> Any:
        """GET /v4/users/me — the user the key acts as."""
        return self._get("/v4/users/me")

    # ================================================================
    # Clinics & practitioners
    # ================================================================

    def list_clinics(self, *, limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics — the clinics this user belongs to."""
        return self._list("/v4/clinics", limit, offset)

    def list_doctors(self, clinic_id: str, *, limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/doctors — the clinic's practitioners."""
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/doctors",
                          limit, offset)

    def get_doctor(self, doctor_id: str) -> Any:
        """GET /v4/doctors/{doctor_id}."""
        return self._get(f"/v4/doctors/{_id(doctor_id, 'doctor_id')}")

    # ================================================================
    # Calendar
    # ================================================================

    def list_appointments(self, clinic_id: str, *, date: Optional[str] = None,
                          patient_id: Optional[str] = None,
                          limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/calendar_appointments.

        Args:
            date: `YYYY-MM-DD` — appointments on that day.
            patient_id: appointments of that patient (sent as `patient`).
        """
        if patient_id is not None:
            patient_id = _id(patient_id, "patient_id")
        return self._list(
            f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/calendar_appointments",
            limit, offset, date=date, patient=patient_id)

    def get_appointment(self, appointment_id: str) -> Any:
        """GET /v4/calendar_appointments/{calendar_appointment_id}."""
        return self._get(
            f"/v4/calendar_appointments/{_id(appointment_id, 'appointment_id')}")

    def reschedule_appointment(self, appointment_id: str, *,
                               visit_type_opening_hour_id: str,
                               time_slot: str) -> Any:
        """POST /v4/calendar_appointments/{id}/reschedule — moves the appointment.

        Both body fields are required by the spec and come from
        `search_time_slots`: the slot's `id` and its `time_slot` (date-time).
        """
        if not time_slot:
            raise ValueError("time_slot est requis.")
        body = {
            "visit_type_opening_hour": _id(visit_type_opening_hour_id,
                                           "visit_type_opening_hour_id"),
            "time_slot": time_slot,
        }
        return self._request(
            "POST",
            f"/v4/calendar_appointments/{_id(appointment_id, 'appointment_id')}/reschedule",
            json_body=body)

    def delete_appointment(self, appointment_id: str) -> Any:
        """DELETE /v4/calendar_appointments/{id} — answers 204."""
        return self._request(
            "DELETE", f"/v4/calendar_appointments/{_id(appointment_id, 'appointment_id')}")

    def search_time_slots(self, clinic_id: str, *, start_date: Optional[str] = None,
                          end_date: Optional[str] = None,
                          sub_visit_type_id: Optional[str] = None,
                          sub_visit_type_name: Optional[str] = None,
                          doctor_id: Optional[str] = None,
                          doctor_name: Optional[str] = None) -> Any:
        """POST /v4/clinics/{clinic_id}/visit_types/opening_hours — free slots.

        A read despite the verb. Dates are `YYYY-MM-DD`; omitted, the search
        spans the current month. Answers `{data: [{id, type, time_slot,
        utc_offset}]}`, unpaginated.
        """
        if sub_visit_type_id is not None:
            sub_visit_type_id = _id(sub_visit_type_id, "sub_visit_type_id")
        if doctor_id is not None:
            doctor_id = _id(doctor_id, "doctor_id")
        body = _clean({
            "start_date": start_date, "end_date": end_date,
            "sub_visit_type_id": sub_visit_type_id,
            "sub_visit_type_name": sub_visit_type_name,
            "doctor_id": doctor_id, "doctor_name": doctor_name,
        })
        return self._request(
            "POST", f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/visit_types/opening_hours",
            json_body=body)

    # ================================================================
    # Service catalogue
    # ================================================================

    def list_visit_types(self, clinic_id: str, *,
                         visit_type_category_id: Optional[str] = None,
                         limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/visit_types."""
        if visit_type_category_id is not None:
            visit_type_category_id = _id(visit_type_category_id, "visit_type_category_id")
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/visit_types",
                          limit, offset, visit_type_category=visit_type_category_id)

    def get_visit_type(self, visit_type_id: str) -> Any:
        """GET /v4/visit_types/{visit_type_id}."""
        return self._get(f"/v4/visit_types/{_id(visit_type_id, 'visit_type_id')}")

    def list_visit_type_categories(self, clinic_id: str, *,
                                   limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/visit_type_categories."""
        return self._list(
            f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/visit_type_categories",
            limit, offset)

    def get_visit_type_category(self, visit_type_category_id: str) -> Any:
        """GET /v4/visit_type_categories/{visit_type_category_id}."""
        return self._get("/v4/visit_type_categories/"
                         f"{_id(visit_type_category_id, 'visit_type_category_id')}")

    def list_sub_visit_types(self, clinic_id: str, *, visit_type_id: Optional[str] = None,
                             limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/sub_visit_types."""
        if visit_type_id is not None:
            visit_type_id = _id(visit_type_id, "visit_type_id")
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/sub_visit_types",
                          limit, offset, visit_type=visit_type_id)

    def get_sub_visit_type(self, sub_visit_type_id: str) -> Any:
        """GET /v4/sub_visit_types/{sub_visit_type_id}."""
        return self._get(
            f"/v4/sub_visit_types/{_id(sub_visit_type_id, 'sub_visit_type_id')}")

    def list_treatment_types(self, clinic_id: str, *, search: Optional[str] = None,
                             limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/treatment_types."""
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/treatment_types",
                          limit, offset, search=search)

    def get_treatment_type(self, treatment_type_id: str) -> Any:
        """GET /v4/treatment_types/{treatment_type_id}."""
        return self._get(
            f"/v4/treatment_types/{_id(treatment_type_id, 'treatment_type_id')}")

    def list_treatment_pricings(self, clinic_id: str, *,
                                treatment_type_id: Optional[str] = None,
                                limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/treatment_pricings."""
        if treatment_type_id is not None:
            treatment_type_id = _id(treatment_type_id, "treatment_type_id")
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/treatment_pricings",
                          limit, offset, treatment_type=treatment_type_id)

    def get_treatment_pricing(self, treatment_pricing_id: str) -> Any:
        """GET /v4/treatment_pricings/{treatment_pricing_id}."""
        return self._get(
            f"/v4/treatment_pricings/{_id(treatment_pricing_id, 'treatment_pricing_id')}")

    # ================================================================
    # Quotes & invoices
    # ================================================================

    def list_quotes(self, clinic_id: str, *, patient_id: Optional[str] = None,
                    limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/quotes (`patient` filter)."""
        if patient_id is not None:
            patient_id = _id(patient_id, "patient_id")
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/quotes",
                          limit, offset, patient=patient_id)

    def get_quote(self, quote_id: str) -> Any:
        """GET /v4/quotes/{quote_id}."""
        return self._get(f"/v4/quotes/{_id(quote_id, 'quote_id')}")

    def list_invoices(self, clinic_id: str, *, limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/invoices (no filter documented)."""
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/invoices",
                          limit, offset)

    def get_invoice(self, invoice_id: str) -> Any:
        """GET /v4/invoices/{invoice_id}."""
        return self._get(f"/v4/invoices/{_id(invoice_id, 'invoice_id')}")

    # ================================================================
    # Product stock (read only)
    # ================================================================

    def list_products(self, clinic_id: str, *, search: Optional[str] = None,
                      stock_state: Optional[str] = None,
                      expiring_within_days: Optional[int] = None,
                      order: Optional[str] = None,
                      limit: int = 50, offset: int = 0) -> Any:
        """GET /v4/clinics/{clinic_id}/products — the clinic's stock, one row per lot.

        Args:
            search: free-text search.
            stock_state: `low` | `out` | `ok`.
            expiring_within_days: >= 1 — lots expiring within that many days.
            order: `name`, `brand_name` (API default), `stock_level` or
                `warning_level`, each optionally prefixed by `-`.
        """
        return self._list(f"/v4/clinics/{_id(clinic_id, 'clinic_id')}/products",
                          limit, offset, search=search, stock_state=stock_state,
                          expiring_within_days=expiring_within_days, order=order)

    def get_product(self, product_id: str) -> Any:
        """GET /v4/products/{product_id}."""
        return self._get(f"/v4/products/{_id(product_id, 'product_id')}")
