"""Nextmotion External API client (https://api.nextmotion.net/open_api/) —
practice-management software for aesthetic-medicine clinics.

Reference: https://api.nextmotion.net/open_api/docs/redoc (OpenAPI 3.0.3 served
at `/open_api/docs/schema`, read 2026-09-17). Paths, query parameters, bodies
and envelopes come from that spec.

Auth is a static API key sent as `Authorization: Bearer {api_key}`. A key is
generated by a user of the web app (Settings → API Keys), acts as that user,
and never expires until rerolled or deleted.

This module carries construction and transport; the calls live in the
`_api/` mixins, one per family: clinics & staff, calendar, service catalogue,
sales (quotes, invoices, payments, statistics, stock), CRM & settings, and
the patient's identity.

## Scope of this client

Two axes, read AND write, and only those:

- **the administrative side of a clinic**: staff, calendar organisation
  (rooms, devices, opening hours, absences, appointments and online requests),
  the service catalogue (visit types, treatment types and pricings, packages,
  accounting distributions, post-treatment email configuration), sales
  (quotes, invoices, payments, credit notes, payment means, product stock),
  CRM (leads, call log, messages sent from a template) and settings
  (communication, document and survey-form TEMPLATES, webhooks);
- **the patient's identity**: list (with its look-up filters), record,
  creation and update (`get_patient`, `create_patient`, `update_patient`).

The API also serves medical content — medical history, photos and media,
prescriptions and their signature, consent-form uploads, clinical
treatments, consultations, visits (clinical notes), and the quotes or
invoices created under a consultation — and a chat whose contacts are
patients. **None of those endpoints has a method here.** Neither do the
technical endpoints (VPS, shell runs, AI-assistant skills, the schema), nor
the deletion of a patient, an invoice or a payment.

### Writing convention

Every write that sends a JSON object takes it as ONE keyword argument,
`body` (a dict); a JSON array body (reorder, replace a package's items, set
per-user distributions) is `items` (a list of dicts). The body is sent as
given minus its `None` values (`_clean`): a field cannot be set to null
through this client. The client checks the ids of the PATH (UUIDs) and the
body's shape (an object, a list of objects); the body's FIELDS are the
caller's — the spec names them, the client does not filter them. The two
writes that predate the convention (`reschedule_appointment`,
`search_time_slots`) keep their named arguments.

⚠️ Many responses EMBED personal data: a patient record carries the
practitioner's comments and a photograph; an appointment, a journey, a quote,
an invoice or a payment carries a nested `patient` object; an appointment
request and a lead carry the requester's name, email and phone; many carry
free-text fields (`notes`, `free_text`, `details`, event titles). This client
returns responses as the API sends them; reducing them is the caller's
decision. Search parameters that match on a person's name are exposed on the
patient list only — not on leads nor journeys (`search`, `order=patient_name`).

## Protocol facts that shape a caller

- Every list is paginated by `limit` (1-100, default 50) and `offset`, and
  answers `{count, next, previous, data: [...]}`. Detail endpoints answer
  `{data: {...}}`. Errors answer `{errors: [{code, message}]}`. A few lists
  are NOT paginated (statistics, user accounting distributions): `{data}`.
- Almost every resource hangs under a clinic: `list_clinics` gives the ids.
- `list_invoices` accepts no filter at all (no date, no patient), and the
  order of the list is not documented.
- The product stock is not linked to invoices nor to treatments: no endpoint
  says which lot an invoice consumed.
- Writes answer `{data: {...}}` (201 on creation); a deletion answers 204,
  except a product's (200, with the lot). Array writes answer a list (or 204
  when a package's items are replaced).
- A 403 `non_employee_access_denied` means the key's user is not an employee
  of that clinic.
- `reschedule_appointment` needs a `visit_type_opening_hour` id and its
  `time_slot`, both read from `search_time_slots`.
- Identifiers are UUIDs; the client refuses anything else before building a
  path, so an id can never rewrite the URL.
- Booleans travel as `true`/`false`; list filters as repeated parameters.
- Rate limits: none published; a 429 surfaces as `UpstreamHTTPError` like any
  other non-2xx — not retried here.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import requests

from ..common.credentials import require
from ..common import raise_for_upstream
from ._api import (_CalendarMixin, _CatalogMixin, _ClinicsMixin, _CrmMixin,
                   _PatientsMixin, _SalesMixin)
from ._http import _page, _query

_HTTP_TIMEOUT = (10, 60)  # (connect, read) — never an unbounded wait
_BASE_URL = "https://api.nextmotion.net/open_api"


class NextmotionClient(_ClinicsMixin, _CalendarMixin, _CatalogMixin, _SalesMixin,
                       _CrmMixin, _PatientsMixin):
    """Nextmotion External API client, Bearer API key."""

    BASE_URL = _BASE_URL

    def __init__(self, api_key: Optional[str] = None):
        """
        Args:
            api_key: Nextmotion API key (or secret `NEXTMOTION_API_KEY`),
                generated in the web app under Settings → API Keys.
        """
        self.api_key = require(api_key, "NEXTMOTION_API_KEY")
        self.session = requests.Session()
        # The key travels in a HEADER, never in the query string.
        self.session.headers["Authorization"] = f"Bearer {self.api_key}"
        self.session.headers["Accept"] = "application/json"

    # ------------------------------------------------------------------
    # transport
    # ------------------------------------------------------------------

    def _request(self, method: str, path: str, *,
                 params: Optional[Dict[str, Any]] = None,
                 json_body: Any = None) -> Any:
        resp = self.session.request(
            method, f"{self.BASE_URL}{path}", params=_query(params or {}),
            json=json_body, timeout=_HTTP_TIMEOUT)
        raise_for_upstream(resp, service="nextmotion")
        if resp.status_code == 204 or not (resp.content or b"").strip():
            return None
        return resp.json()

    def _get(self, path: str, **params: Any) -> Any:
        return self._request("GET", path, params=params)

    def _list(self, path: str, limit: int, offset: int, **filters: Any) -> Any:
        return self._request("GET", path, params={**_page(limit, offset), **filters})

    def _post(self, path: str, body: Any = None) -> Any:
        return self._request("POST", path, json_body=body)

    def _put(self, path: str, body: Any) -> Any:
        return self._request("PUT", path, json_body=body)

    def _delete(self, path: str) -> Any:
        return self._request("DELETE", path)
