"""Sortie TypeScript : un module par connecteur, et l'index.

Un module porte des définitions structurelles typées (`ts/src/types.ts`), sans
rien exécuter : le paquet d'un hôte les adapte à son contrat de fonction et
exécute la requête avec son client HTTP, son coffre et son journal. Le module ne
dépend que de `zod` et de `./types`.
"""
from __future__ import annotations

import copy
from dataclasses import dataclass, field

from .descriptions import PATH_PARAM, Description
from .zod import Untranslatable, js, translate_input

HEADER = "// Generated by the fabrique from {source}. Do not edit: run `python -m fabrique`."
GENERATED_MARK = "// Generated by the fabrique"
DEFAULT_TIMEOUT_S = 30
PAGINATION_ARGUMENTS = ("all_pages", "max_pages")
RESERVED = {
    "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum",
    "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "null",
    "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield",
    "let", "static", "implements", "interface", "package", "private", "protected", "public", "await", "connector",
}


@dataclass
class Skipped:
    function: str
    reason: str


@dataclass
class Module:
    connector: str
    identifier: str
    source: str
    generated: list[str] = field(default_factory=list)
    skipped: list[Skipped] = field(default_factory=list)


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def _served_input(function: dict) -> dict:
    """L'entrée servie : celle de la description, plus `all_pages` et `max_pages` quand la fonction pagine."""
    served = copy.deepcopy(function["input"])
    pagination = function.get("pagination")
    if not pagination:
        return served
    taken = [name for name in PAGINATION_ARGUMENTS if name in served["properties"]]
    if taken:
        raise Untranslatable(f"input declares {', '.join(taken)}, which pagination adds")
    limit = pagination["max_pages"]
    served["properties"]["all_pages"] = {
        "type": "boolean",
        "description": f"Read the following pages too, up to max_pages (at most {limit}).",
    }
    served["properties"]["max_pages"] = {
        "type": "integer", "minimum": 1, "maximum": limit, "default": limit,
        "description": "Pages read when all_pages is true.",
    }
    return served


def _object(entries: list[tuple[str, str]], indent: int) -> str:
    """Un objet littéral, une clé par ligne ; les valeurs sont déjà des expressions."""
    if not entries:
        return "{}"
    pad = "  " * (indent + 1)
    body = "\n".join(f"{pad}{key}: {value}," for key, value in entries)
    return "{\n" + body + "\n" + "  " * indent + "}"


def _request(call: dict) -> str:
    return _object([
        ("method", js(call["method"])),
        ("path", js(call["path"])),
        ("pathParams", js(PATH_PARAM.findall(call["path"]))),
        ("query", js(call.get("query") or {})),
        ("body", js(call.get("body") or {})),
        ("headers", js(call.get("headers") or {})),
    ], 1)


def _pagination(pagination: dict) -> str:
    entries = [
        ("kind", js(pagination["kind"])),
        ("requestParam", js(pagination["request_param"])),
        ("next", js(pagination["next"])),
    ]
    if "total" in pagination:
        entries.append(("total", js(pagination["total"])))
    entries.append(("maxPages", js(pagination["max_pages"])))
    return "{ " + ", ".join(f"{k}: {v}" for k, v in entries) + " }"


def _list(items: list[str], indent: int) -> str:
    if not items:
        return "[]"
    pad = "  " * (indent + 1)
    return "[\n" + "\n".join(f"{pad}{item}," for item in items) + "\n" + "  " * indent + "]"


def function_source(connector: str, function: dict) -> str:
    """La définition d'une fonction, ou `Untranslatable`."""
    if "handwritten" in function:
        raise Untranslatable("handwritten: the fabrique does not generate it")
    qualified = f"{connector}.{function['name']}"
    schema = translate_input(_served_input(function), "input")
    schema = schema.replace("\n", "\n  ")
    examples = [
        "{ title: " + js(example["title"]) + ", input: " + js(example["input"]) + " }"
        for example in function["examples"]
    ]
    refusals = [
        "{ code: " + js(r["code"]) + ", when: " + js(r["when"]) + ", message: " + js(r["message"]) + " }"
        for r in function.get("refusals", [])
    ]
    entries = [
        ("name", js(qualified)),
        ("connector", js(connector)),
        ("class", js(function["class"])),
        ("description", js(function["description"].strip())),
        ("schema", schema),
        ("examples", _list(examples, 1)),
        ("refusals", _list(refusals, 1)),
        ("request", _request(function["call"])),
    ]
    if "pagination" in function:
        entries.append(("pagination", _pagination(function["pagination"])))
    if "output" in function:
        output = function["output"]
        out = [(key, js(output[key])) for key in ("items", "strip", "projection") if key in output]
        if "schema" in output:
            out.append(("schema", js(output["schema"])))
        entries.append(("output", "{ " + ", ".join(f"{k}: {v}" for k, v in out) + " }"))
    if "cost" in function:
        entries.append(("cost", "{ per: " + js(function["cost"]["per"]) + " }"))
    if "confirm" in function:
        entries.append(("confirm", "{ summary: " + js(function["confirm"]["summary"]) + " }"))
    return f"export const {camel(function['name'])} = defineFunction({_object(entries, 0)})\n"


def _auth(auth: dict) -> str:
    renamed = {
        "token_url": "tokenUrl", "token_request": "tokenRequest", "client_id": "clientId",
        "client_secret": "clientSecret", "expires_in_default": "expiresInDefault",
    }
    entries = {}
    for key, value in auth.items():
        if key == "handwritten":
            entries["handwritten"] = value["typescript"]
        else:
            entries[renamed.get(key, key)] = value
    return js(entries)


def _errors(errors: list[dict]) -> str:
    rows = [
        "{ status: " + js(e["status"]) + ", code: " + js(e["code"]) + ", message: " + js(e["message"])
        + ", retryable: " + js(e["retryable"]) + " }"
        for e in errors
    ]
    return _list(rows, 1)


def connector_module(description: Description) -> Module:
    data = description.data
    connector = data["connector"]
    name = connector["name"]
    module = Module(connector=name, identifier=camel(name), source="")
    blocks = []
    exported = []
    for function in data["functions"]:
        qualified = f"{name}.{function['name']}"
        identifier = camel(function["name"])
        if identifier in RESERVED:
            raise Untranslatable(f"{qualified}: {identifier!r} cannot be an exported name")
        try:
            blocks.append(function_source(name, function))
        except Untranslatable as refusal:
            module.skipped.append(Skipped(qualified, str(refusal)))
            continue
        module.generated.append(qualified)
        exported.append(identifier)

    entries = [
        ("name", js(name)),
        ("label", js(connector["label"])),
        ("namespace", js(connector["namespace"])),
        ("version", js(connector["version"])),
        ("apiVersion", js(connector["api_version"])),
    ]
    if "base_url" in connector:
        entries.append(("baseUrl", js(connector["base_url"])))
    entries.append(("auth", _auth(connector["auth"])))
    entries.append(("credential", js(connector.get("credential", []))))
    entries.append(("modes", js(connector["modes"])))
    entries.append(("timeoutMs", js(connector.get("timeout_s", DEFAULT_TIMEOUT_S) * 1000)))
    if "query_arrays" in connector:
        entries.append(("queryArrays", js(connector["query_arrays"])))
    if "quota" in connector:
        entries.append(("quota", js(connector["quota"])))
    entries.append(("errors", _errors(connector["errors"])))
    if "exposure" in data:
        entries.append(("exposure", js(data["exposure"])))
    entries.append(("functions", _list(exported, 1)))

    source = f"connectors/{name}/connector.yaml"
    head = [HEADER.format(source=source)]
    if module.skipped:
        head.append("// Not generated:")
        head += [f"// - {s.function}: {s.reason}" for s in module.skipped]
    head += ['import * as z from "zod/v4"', 'import { defineConnector, defineFunction } from "./types"', ""]
    footer = f"export const connector = defineConnector({_object(entries, 0)})\n"
    module.source = "\n".join(head) + "\n" + "\n".join(blocks) + ("\n" if blocks else "") + footer
    return module


def index_source(modules: list[Module]) -> str:
    lines = [HEADER.format(source="connectors/*/connector.yaml")]
    lines += [f'import * as {m.identifier} from "./{m.connector}"' for m in modules]
    lines.append("")
    lines += [f"export {{ {m.identifier} }}" for m in modules]
    lines.append('export type * from "./types"')
    lines.append("")
    lines.append("/** Every generated connector, in name order. */")
    lines.append("export const connectors = " + _list([f"{m.identifier}.connector" for m in modules], 0) + " as const")
    return "\n".join(lines) + "\n"
