// Generated by the fabrique from connectors/affinity/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const getCurrentUser = defineFunction({
  name: "affinity.get_current_user",
  connector: "affinity",
  class: "read",
  description: "Get the tenant, the user and the grant (type, scopes) of the API key, through API v2. The key acts as this user: what it writes is attributed to them and their sharing rules decide what it sees. Free of the monthly account quota.",
  schema: {"type": "object", "additionalProperties": false, "properties": {}},
  examples: [
    { title: "Who the key acts as", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/auth/whoami",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
})

export const getCurrentUserV1 = defineFunction({
  name: "affinity.get_current_user_v1",
  connector: "affinity",
  class: "read",
  description: "Get the same identity through API v1, which most writes use: proves the key is accepted by v1 too. Free of the monthly account quota.",
  schema: {"type": "object", "additionalProperties": false, "properties": {}},
  examples: [
    { title: "Who the key acts as, through v1", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/auth/whoami",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
})

export const searchPersons = defineFunction({
  name: "affinity.search_persons",
  connector: "affinity",
  class: "read",
  description: "Search persons whose name or email contains term (API v1). Paged by page_size and page_token; the answer carries next_page_token. With with_interaction_dates, persons without any interaction are left out.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "term": {"type": "string", "description": "Part of a name or an email."},
      "with_interaction_dates": {"type": "boolean", "description": "Add interaction dates; leaves out persons without any interaction."},
      "page_size": {"type": "integer", "minimum": 1},
      "page_token": {"type": "string", "description": "next_page_token of the previous page."}
    }
  },
  examples: [
    { title: "Persons matching a name", input: {"term": "Jane Doe", "page_size": 20} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/persons",
    pathParams: [],
    query: {"term": "term", "with_interaction_dates": "with_interaction_dates", "page_size": "page_size", "page_token": "page_token"},
    body: {},
    headers: {},
  },
})

export const searchOrganizations = defineFunction({
  name: "affinity.search_organizations",
  connector: "affinity",
  class: "read",
  description: "Search organizations (companies) whose name or domain contains term (API v1). Paged by page_size and page_token; the answer carries next_page_token.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "term": {"type": "string", "description": "Part of a name or a domain."},
      "with_interaction_dates": {
        "type": "boolean",
        "description": "Add interaction dates; leaves out organizations without any interaction."
      },
      "page_size": {"type": "integer", "minimum": 1},
      "page_token": {"type": "string", "description": "next_page_token of the previous page."}
    }
  },
  examples: [
    { title: "Organizations matching a domain", input: {"term": "acme.com"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/organizations",
    pathParams: [],
    query: {"term": "term", "with_interaction_dates": "with_interaction_dates", "page_size": "page_size", "page_token": "page_token"},
    body: {},
    headers: {},
  },
})

export const getPerson = defineFunction({
  name: "affinity.get_person",
  connector: "affinity",
  class: "read",
  description: "Get one person by id (API v2). No field data comes back unless field_ids or field_types is given; list-specific fields are readable only through list entries.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["person_id"],
    "properties": {
      "person_id": {"type": "integer", "minimum": 1},
      "field_ids": {
        "type": "array",
        "items": {"type": "string", "minLength": 1},
        "description": "Field ids to return, e.g. field-1234."
      },
      "field_types": {
        "type": "array",
        "items": {"enum": ["enriched", "global", "list", "relationship-intelligence"]},
        "description": "Return every field of these types."
      }
    }
  },
  examples: [
    { title: "One person with its global fields", input: {"person_id": 1001, "field_types": ["global"]} },
  ],
  refusals: [
    { code: "person_not_found", when: 404, message: "No person with this id is visible to the key's user." },
  ],
  request: {
    method: "GET",
    path: "/v2/persons/{person_id}",
    pathParams: ["person_id"],
    query: {"fieldIds": "field_ids", "fieldTypes": "field_types"},
    body: {},
    headers: {},
  },
})

export const getCompany = defineFunction({
  name: "affinity.get_company",
  connector: "affinity",
  class: "read",
  description: "Get one company by id (API v2). No field data comes back unless field_ids or field_types is given.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id"],
    "properties": {
      "company_id": {"type": "integer", "minimum": 1},
      "field_ids": {
        "type": "array",
        "items": {"type": "string", "minLength": 1},
        "description": "Field ids to return, e.g. field-1234."
      },
      "field_types": {
        "type": "array",
        "items": {"enum": ["enriched", "global", "list", "relationship-intelligence"]},
        "description": "Return every field of these types."
      }
    }
  },
  examples: [
    { title: "One company with its enriched fields", input: {"company_id": 2002, "field_types": ["enriched"]} },
  ],
  refusals: [
    { code: "company_not_found", when: 404, message: "No company with this id is visible to the key's user." },
  ],
  request: {
    method: "GET",
    path: "/v2/companies/{company_id}",
    pathParams: ["company_id"],
    query: {"fieldIds": "field_ids", "fieldTypes": "field_types"},
    body: {},
    headers: {},
  },
})

export const getOpportunity = defineFunction({
  name: "affinity.get_opportunity",
  connector: "affinity",
  class: "read",
  description: "Get one opportunity by id (API v2): name and list. Opportunities have no global fields: their field values live on their list entry.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["opportunity_id"],
    "properties": {"opportunity_id": {"type": "integer", "minimum": 1}}
  },
  examples: [
    { title: "One opportunity", input: {"opportunity_id": 3003} },
  ],
  refusals: [
    { code: "opportunity_not_found", when: 404, message: "No opportunity with this id is visible to the key's user." },
  ],
  request: {
    method: "GET",
    path: "/v2/opportunities/{opportunity_id}",
    pathParams: ["opportunity_id"],
    query: {},
    body: {},
    headers: {},
  },
})

export const getEntityV1 = defineFunction({
  name: "affinity.get_entity_v1",
  connector: "affinity",
  class: "read",
  description: "Get a person, organization or opportunity through API v1: the record with its association ids (organization_ids, person_ids), which v2 does not return. Read it before a v1 update, since v1 updates REPLACE those arrays.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["entity_type", "entity_id"],
    "properties": {
      "entity_type": {"enum": ["persons", "organizations", "opportunities"]},
      "entity_id": {"type": "integer", "minimum": 1}
    }
  },
  examples: [
    { title: "An organization with its person ids", input: {"entity_type": "organizations", "entity_id": 2002} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/{entity_type}/{entity_id}",
    pathParams: ["entity_type", "entity_id"],
    query: {},
    body: {},
    headers: {},
  },
})

export const listEntityListEntries = defineFunction({
  name: "affinity.list_entity_list_entries",
  connector: "affinity",
  class: "read",
  description: "List every list a person or company is on, with ALL its field values (list fields included), through API v2. Paged by limit and cursor; the next cursor is in the query string of pagination.nextUrl. An opportunity has a single list entry: read it from its list.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["entity_type", "entity_id"],
    "properties": {
      "entity_type": {"enum": ["persons", "companies"]},
      "entity_id": {"type": "integer", "minimum": 1},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "The lists a company is on", input: {"entity_type": "companies", "entity_id": 2002, "limit": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/{entity_type}/{entity_id}/list-entries",
    pathParams: ["entity_type", "entity_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listRelationships = defineFunction({
  name: "affinity.list_relationships",
  connector: "affinity",
  class: "read",
  description: "List the connections of a person or company with their interactionScore (0 to 1, 0.7 and above is regular contact), strongest first, through API v2. Persons and companies only. Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["entity_type", "entity_id"],
    "properties": {
      "entity_type": {"enum": ["persons", "companies"]},
      "entity_id": {"type": "integer", "minimum": 1},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Strongest connections of a person", input: {"entity_type": "persons", "entity_id": 1001, "limit": 10} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/{entity_type}/{entity_id}/relationships",
    pathParams: ["entity_type", "entity_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listGlobalFields = defineFunction({
  name: "affinity.list_global_fields",
  connector: "affinity",
  class: "read",
  description: "List the global and enriched fields of persons or companies with their valueType, through API v2. Opportunities have no global fields: read the fields of their list. Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["entity_type"],
    "properties": {
      "entity_type": {"enum": ["persons", "companies"]},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Global fields of companies", input: {"entity_type": "companies", "limit": 100} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/{entity_type}/fields",
    pathParams: ["entity_type"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listGlobalFieldDropdownOptions = defineFunction({
  name: "affinity.list_global_field_dropdown_options",
  connector: "affinity",
  class: "read",
  description: "List the options of a dropdown global field of persons or companies, through API v2. A dropdown is written with an option id, never the option text.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["entity_type", "field_id"],
    "properties": {
      "entity_type": {"enum": ["persons", "companies"]},
      "field_id": {"type": "string", "minLength": 1, "description": "e.g. field-1234."},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Options of a company dropdown field", input: {"entity_type": "companies", "field_id": "field-1234"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/{entity_type}/fields/{field_id}/dropdown-options",
    pathParams: ["entity_type", "field_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const createPerson = defineFunction({
  name: "affinity.create_person",
  connector: "affinity",
  class: "write",
  description: "Create a person (API v1). Fails if one of the emails already belongs to another person: search first.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["first_name", "last_name"],
    "properties": {
      "first_name": {"type": "string", "minLength": 1, "pattern": "\\S"},
      "last_name": {"type": "string", "minLength": 1, "pattern": "\\S"},
      "emails": {"type": "array", "items": {"type": "string"}, "default": []},
      "organization_ids": {"type": "array", "items": {"type": "integer", "minimum": 1}}
    }
  },
  examples: [
    { title: "A person attached to a company", input: {"first_name": "Jane", "last_name": "Doe", "emails": ["jane.doe@acme.example"], "organization_ids": [2002]} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/persons",
    pathParams: [],
    query: {},
    body: {"first_name": "first_name", "last_name": "last_name", "emails": "emails", "organization_ids": "organization_ids"},
    headers: {},
  },
})

export const updatePerson = defineFunction({
  name: "affinity.update_person",
  connector: "affinity",
  class: "write",
  description: "Change a person's name, emails or organizations (API v1). emails and organization_ids REPLACE the current sets: send the existing values too to add one (get_entity_v1 returns them).",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["person_id"],
    "minProperties": 2,
    "properties": {
      "person_id": {"type": "integer", "minimum": 1},
      "first_name": {"type": "string", "minLength": 1},
      "last_name": {"type": "string", "minLength": 1},
      "emails": {"type": "array", "items": {"type": "string"}, "description": "Replaces every email of the person."},
      "organization_ids": {
        "type": "array",
        "items": {"type": "integer", "minimum": 1},
        "description": "Replaces every organization of the person."
      }
    }
  },
  examples: [
    { title: "Add a second email to a person", input: {"person_id": 1001, "emails": ["jane.doe@acme.example", "jane@example.org"]} },
  ],
  refusals: [
    { code: "nothing_to_update", when: "no field besides person_id is given", message: "Give at least one field to change." },
  ],
  request: {
    method: "PUT",
    path: "/persons/{person_id}",
    pathParams: ["person_id"],
    query: {},
    body: {"first_name": "first_name", "last_name": "last_name", "emails": "emails", "organization_ids": "organization_ids"},
    headers: {},
  },
})

export const createOrganization = defineFunction({
  name: "affinity.create_organization",
  connector: "affinity",
  class: "write",
  description: "Create an organization (company) through API v1. Affinity does NOT refuse a duplicate domain: search first.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["name"],
    "properties": {
      "name": {"type": "string", "minLength": 1, "pattern": "\\S"},
      "domain": {"type": "string"},
      "person_ids": {"type": "array", "items": {"type": "integer", "minimum": 1}}
    }
  },
  examples: [
    { title: "A company with its domain", input: {"name": "Acme", "domain": "acme.example"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/organizations",
    pathParams: [],
    query: {},
    body: {"name": "name", "domain": "domain", "person_ids": "person_ids"},
    headers: {},
  },
})

export const updateOrganization = defineFunction({
  name: "affinity.update_organization",
  connector: "affinity",
  class: "write",
  description: "Change an organization's name, domain or persons (API v1). person_ids REPLACES the current set. Global organizations cannot be changed.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["organization_id"],
    "minProperties": 2,
    "properties": {
      "organization_id": {"type": "integer", "minimum": 1},
      "name": {"type": "string", "minLength": 1},
      "domain": {"type": "string"},
      "person_ids": {
        "type": "array",
        "items": {"type": "integer", "minimum": 1},
        "description": "Replaces every person of the organization."
      }
    }
  },
  examples: [
    { title: "Rename a company", input: {"organization_id": 2002, "name": "Acme Group"} },
  ],
  refusals: [
    { code: "nothing_to_update", when: "no field besides organization_id is given", message: "Give at least one field to change." },
  ],
  request: {
    method: "PUT",
    path: "/organizations/{organization_id}",
    pathParams: ["organization_id"],
    query: {},
    body: {"name": "name", "domain": "domain", "person_ids": "person_ids"},
    headers: {},
  },
})

export const createOpportunity = defineFunction({
  name: "affinity.create_opportunity",
  connector: "affinity",
  class: "write",
  description: "Create an opportunity in an opportunity-type list (API v1): the only way an opportunity joins its list.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["name", "list_id"],
    "properties": {
      "name": {"type": "string", "minLength": 1, "pattern": "\\S"},
      "list_id": {"type": "integer", "minimum": 1, "description": "An opportunity-type list."},
      "person_ids": {"type": "array", "items": {"type": "integer", "minimum": 1}},
      "organization_ids": {"type": "array", "items": {"type": "integer", "minimum": 1}}
    }
  },
  examples: [
    { title: "A deal with a company", input: {"name": "Acme Series A", "list_id": 501, "organization_ids": [2002]} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/opportunities",
    pathParams: [],
    query: {},
    body: {"name": "name", "list_id": "list_id", "person_ids": "person_ids", "organization_ids": "organization_ids"},
    headers: {},
  },
})

export const updateOpportunity = defineFunction({
  name: "affinity.update_opportunity",
  connector: "affinity",
  class: "write",
  description: "Change an opportunity's name, persons or organizations (API v1). The association arrays REPLACE the current sets.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["opportunity_id"],
    "minProperties": 2,
    "properties": {
      "opportunity_id": {"type": "integer", "minimum": 1},
      "name": {"type": "string", "minLength": 1},
      "person_ids": {
        "type": "array",
        "items": {"type": "integer", "minimum": 1},
        "description": "Replaces every person of the opportunity."
      },
      "organization_ids": {
        "type": "array",
        "items": {"type": "integer", "minimum": 1},
        "description": "Replaces every organization of the opportunity."
      }
    }
  },
  examples: [
    { title: "Rename an opportunity", input: {"opportunity_id": 3003, "name": "Acme Series B"} },
  ],
  refusals: [
    { code: "nothing_to_update", when: "no field besides opportunity_id is given", message: "Give at least one field to change." },
  ],
  request: {
    method: "PUT",
    path: "/opportunities/{opportunity_id}",
    pathParams: ["opportunity_id"],
    query: {},
    body: {"name": "name", "person_ids": "person_ids", "organization_ids": "organization_ids"},
    headers: {},
  },
})

export const listLists = defineFunction({
  name: "affinity.list_lists",
  connector: "affinity",
  class: "read",
  description: "List the lists the key's user can see (API v2), optionally by name. Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "term": {"type": "string", "description": "Part of a list name."},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Lists whose name contains pipeline", input: {"term": "pipeline"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/lists",
    pathParams: [],
    query: {"term": "term", "cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const getList = defineFunction({
  name: "affinity.get_list",
  connector: "affinity",
  class: "read",
  description: "Get one list (API v2): name, type (person, company or opportunity), owner.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id"],
    "properties": {"list_id": {"type": "integer", "minimum": 1}}
  },
  examples: [
    { title: "One list", input: {"list_id": 501} },
  ],
  refusals: [
    { code: "list_not_found", when: 404, message: "No list with this id is visible to the key's user." },
  ],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}",
    pathParams: ["list_id"],
    query: {},
    body: {},
    headers: {},
  },
})

export const listListFields = defineFunction({
  name: "affinity.list_list_fields",
  connector: "affinity",
  class: "read",
  description: "List every field shown on a list (list, global, enriched…) with its valueType and isRequired (API v2). Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Fields of a list", input: {"list_id": 501, "limit": 100} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}/fields",
    pathParams: ["list_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listListFieldDropdownOptions = defineFunction({
  name: "affinity.list_list_field_dropdown_options",
  connector: "affinity",
  class: "read",
  description: "List the options of a dropdown field of a list (API v2). A dropdown is written with an option id, never the option text.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "field_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "field_id": {"type": "string", "minLength": 1, "description": "e.g. field-1234."},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Options of a stage field", input: {"list_id": 501, "field_id": "field-1234"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}/fields/{field_id}/dropdown-options",
    pathParams: ["list_id", "field_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listSavedViews = defineFunction({
  name: "affinity.list_saved_views",
  connector: "affinity",
  class: "read",
  description: "List the saved views of a list (API v2). Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Saved views of a list", input: {"list_id": 501} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}/saved-views",
    pathParams: ["list_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listListEntries = defineFunction({
  name: "affinity.list_list_entries",
  connector: "affinity",
  class: "read",
  description: "List the rows (entries) of a list with their entity (API v2). Needs the Export data from Lists permission. No field data comes back unless field_ids or field_types is given. Paged by limit and cursor; the next cursor is in the query string of pagination.nextUrl. A list entry id is not an entity id.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "field_ids": {
        "type": "array",
        "items": {"type": "string", "minLength": 1},
        "description": "Field ids to return, e.g. field-1234."
      },
      "field_types": {
        "type": "array",
        "items": {"enum": ["enriched", "global", "list", "relationship-intelligence"]},
        "description": "Return every field of these types."
      },
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "First rows of a list with their list fields", input: {"list_id": 501, "field_types": ["list"], "limit": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}/list-entries",
    pathParams: ["list_id"],
    query: {"fieldIds": "field_ids", "fieldTypes": "field_types", "cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listSavedViewEntries = defineFunction({
  name: "affinity.list_saved_view_entries",
  connector: "affinity",
  class: "read",
  description: "List the rows of a saved view, with the filters and columns saved in the app (API v2). Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "view_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "view_id": {"type": "integer", "minimum": 1},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Rows of a saved view", input: {"list_id": 501, "view_id": 77} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}/saved-views/{view_id}/list-entries",
    pathParams: ["list_id", "view_id"],
    query: {"cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const getListEntry = defineFunction({
  name: "affinity.get_list_entry",
  connector: "affinity",
  class: "read",
  description: "Get one row of a list with its entity (API v2). No field data comes back unless field_ids or field_types is given.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "entry_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "entry_id": {"type": "integer", "minimum": 1, "description": "List entry id, not the entity id."},
      "field_ids": {"type": "array", "items": {"type": "string", "minLength": 1}},
      "field_types": {"type": "array", "items": {"enum": ["enriched", "global", "list", "relationship-intelligence"]}}
    }
  },
  examples: [
    { title: "One row with its list fields", input: {"list_id": 501, "entry_id": 9001, "field_types": ["list"]} },
  ],
  refusals: [
    { code: "list_entry_not_found", when: 404, message: "No entry with this id in this list." },
  ],
  request: {
    method: "GET",
    path: "/v2/lists/{list_id}/list-entries/{entry_id}",
    pathParams: ["list_id", "entry_id"],
    query: {"fieldIds": "field_ids", "fieldTypes": "field_types"},
    body: {},
    headers: {},
  },
})

export const addListEntry = defineFunction({
  name: "affinity.add_list_entry",
  connector: "affinity",
  class: "write",
  description: "Add a person or organization to a list (API v1). Opportunities cannot be added: create them with create_opportunity. The same entity can be added twice: check its list entries first.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "entity_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "entity_id": {"type": "integer", "minimum": 1, "description": "Person or organization id."},
      "creator_id": {"type": "integer", "minimum": 1, "description": "Person id recorded as the creator."}
    }
  },
  examples: [
    { title: "Add a company to a list", input: {"list_id": 501, "entity_id": 2002} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/lists/{list_id}/list-entries",
    pathParams: ["list_id"],
    query: {},
    body: {"entity_id": "entity_id", "creator_id": "creator_id"},
    headers: {},
  },
})

export const removeListEntry = defineFunction({
  name: "affinity.remove_list_entry",
  connector: "affinity",
  class: "sensitive",
  description: "Remove a row from a list (API v1). Also deletes the entry's list-field values; on an OPPORTUNITY list, deletes the opportunity itself. Irreversible.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "entry_id"],
    "properties": {
      "list_id": {"type": "integer", "minimum": 1},
      "entry_id": {"type": "integer", "minimum": 1, "description": "List entry id, not the entity id."}
    }
  },
  examples: [
    { title: "Remove one row", input: {"list_id": 501, "entry_id": 9001} },
  ],
  refusals: [
    { code: "list_entry_not_found", when: 404, message: "No entry with this id in this list." },
  ],
  request: {
    method: "DELETE",
    path: "/lists/{list_id}/list-entries/{entry_id}",
    pathParams: ["list_id", "entry_id"],
    query: {},
    body: {},
    headers: {},
  },
  confirm: { summary: "Remove entry {entry_id} from list {list_id}: its list-field values are deleted, and on an opportunity list the opportunity too. Irreversible." },
})

export const listNotes = defineFunction({
  name: "affinity.list_notes",
  connector: "affinity",
  class: "read",
  description: "List the notes visible to the key's user (API v2). filter supports creator.id=, createdAt>… and updatedAt<…. Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {"type": "string", "description": "e.g. createdAt>2026-01-01T00:00:00Z."},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Notes created since a date", input: {"filter": "createdAt>2026-01-01T00:00:00Z", "limit": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/notes",
    pathParams: [],
    query: {"filter": "filter", "cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const listEntityNotes = defineFunction({
  name: "affinity.list_entity_notes",
  connector: "affinity",
  class: "read",
  description: "List the notes of one person, company or opportunity (API v2): direct notes, notes on its meetings, mentions. Same filter as list_notes. Paged by limit and cursor.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["entity_type", "entity_id"],
    "properties": {
      "entity_type": {"enum": ["persons", "companies", "opportunities"]},
      "entity_id": {"type": "integer", "minimum": 1},
      "filter": {"type": "string"},
      "cursor": {"type": "string"},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100}
    }
  },
  examples: [
    { title: "Notes on a company", input: {"entity_type": "companies", "entity_id": 2002} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/{entity_type}/{entity_id}/notes",
    pathParams: ["entity_type", "entity_id"],
    query: {"filter": "filter", "cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
})

export const getNote = defineFunction({
  name: "affinity.get_note",
  connector: "affinity",
  class: "read",
  description: "Get one note by id (API v2).",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["note_id"],
    "properties": {"note_id": {"type": "integer", "minimum": 1, "maximum": 2147483647}}
  },
  examples: [
    { title: "One note", input: {"note_id": 4004} },
  ],
  refusals: [
    { code: "note_not_found", when: 404, message: "No note with this id is visible to the key's user." },
  ],
  request: {
    method: "GET",
    path: "/v2/notes/{note_id}",
    pathParams: ["note_id"],
    query: {},
    body: {},
    headers: {},
  },
})

export const deleteNote = defineFunction({
  name: "affinity.delete_note",
  connector: "affinity",
  class: "sensitive",
  description: "Delete one note by id (API v2). Irreversible.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["note_id"],
    "properties": {"note_id": {"type": "integer", "minimum": 1, "maximum": 2147483647}}
  },
  examples: [
    { title: "Delete a note", input: {"note_id": 4004} },
  ],
  refusals: [
    { code: "note_not_found", when: 404, message: "No note with this id is visible to the key's user." },
  ],
  request: {
    method: "DELETE",
    path: "/v2/notes/{note_id}",
    pathParams: ["note_id"],
    query: {},
    body: {},
    headers: {},
  },
  confirm: { summary: "Delete note {note_id}: irreversible." },
})

export const listInteractions = defineFunction({
  name: "affinity.list_interactions",
  connector: "affinity",
  class: "read",
  description: "List the emails, meetings, calls or chat messages with ONE external person, organization or opportunity (API v1), within a window of at most one year. The answer is keyed by type (emails, events…) and paged by page_size and page_token.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["type", "start_time", "end_time"],
    "oneOf": [{"required": ["person_id"]}, {"required": ["organization_id"]}, {"required": ["opportunity_id"]}],
    "properties": {
      "type": {"enum": [0, 1, 2, 3], "description": "0 meeting, 1 call, 2 chat message, 3 email."},
      "start_time": {"type": "string", "format": "date-time", "description": "ISO 8601; at most one year before end_time."},
      "end_time": {"type": "string", "format": "date-time"},
      "person_id": {"type": "integer", "minimum": 1},
      "organization_id": {"type": "integer", "minimum": 1},
      "opportunity_id": {"type": "integer", "minimum": 1},
      "direction": {"enum": [0, 1], "description": "0 sent, 1 received."},
      "page_size": {"type": "integer", "minimum": 1},
      "page_token": {"type": "string"}
    }
  },
  examples: [
    { title: "Emails with a company over a quarter", input: {"type": 3, "organization_id": 2002, "start_time": "2026-01-01T00:00:00Z", "end_time": "2026-04-01T00:00:00Z"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/interactions",
    pathParams: [],
    query: {"type": "type", "start_time": "start_time", "end_time": "end_time", "person_id": "person_id", "organization_id": "organization_id", "opportunity_id": "opportunity_id", "direction": "direction", "page_size": "page_size", "page_token": "page_token"},
    body: {},
    headers: {},
  },
})

export const connector = defineConnector({
  name: "affinity",
  label: "Affinity",
  namespace: "affinity",
  version: "1.0.0",
  apiVersion: "v1 and v2 (2026-09-17)",
  baseUrl: "https://api.affinity.co",
  auth: {"kind": "bearer", "token": "api_key"},
  credential: [{"name": "api_key", "label": "API key", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  queryArrays: "repeat",
  errors: [
    { status: 400, code: "invalid_request", message: "Affinity rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Affinity refused the API key: it is invalid or revoked.", retryable: false },
    { status: 403, code: "permission_denied", message: "Affinity refused this action: the key's user lacks a permission (reading list entries and writing list fields need Export data from Lists, writing global fields needs Edit Global Field Values), or the plan has no API access.", retryable: false },
    { status: 404, code: "not_found", message: "Affinity found nothing with this id, or it is not visible to the key's user.", retryable: false },
    { status: 429, code: "rate_limited", message: "Affinity rate limit reached: 900 requests per user per minute, plus a monthly account quota shared with every other Affinity integration.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Affinity is temporarily unavailable: retry later.", retryable: true },
  ],
  functions: [
    getCurrentUser,
    getCurrentUserV1,
    searchPersons,
    searchOrganizations,
    getPerson,
    getCompany,
    getOpportunity,
    getEntityV1,
    listEntityListEntries,
    listRelationships,
    listGlobalFields,
    listGlobalFieldDropdownOptions,
    createPerson,
    updatePerson,
    createOrganization,
    updateOrganization,
    createOpportunity,
    updateOpportunity,
    listLists,
    getList,
    listListFields,
    listListFieldDropdownOptions,
    listSavedViews,
    listListEntries,
    listSavedViewEntries,
    getListEntry,
    addListEntry,
    removeListEntry,
    listNotes,
    listEntityNotes,
    getNote,
    deleteNote,
    listInteractions,
  ],
})
