// Generated by the fabrique from connectors/aircall/connector.yaml. Do not edit: run `python -m fabrique`.
// Not generated:
// - aircall.search_contacts: input: anyOf at the root needs a refinement
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const listCalls = defineFunction({
  name: "aircall.list_calls",
  connector: "aircall",
  class: "read",
  description: "List the calls of the Aircall company, bounded on their creation date: who called whom, when, how long, the line, the agent, tags, comments, and the recording or voicemail URLs. Six months of history only, and at most 10,000 calls through pagination: narrow with date_from to reach further. Ascending by creation date unless order is desc. Recording and voicemail URLs expire (direct mp3 one hour, short URLs three hours): fetch them right before use. duration includes ringing; talk time is ended_at - answered_at. Times are UNIX seconds, UTC. meta.next_page_link is null on the last page.",
  schema: z.strictObject({
    "date_from": z.int().gte(0).describe("Lower bound on the creation date, UNIX seconds (UTC).").optional(),
    "date_to": z.int().gte(0).describe("Upper bound on the creation date, UNIX seconds (UTC).").optional(),
    "order": z.enum(["asc", "desc"]).describe("Order by creation date; ascending when omitted.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "per_page": z.int().gte(1).lte(50).meta({"default": 20}).optional(),
    "fetch_contact": z.boolean().describe("Add the contact details of each call.").optional(),
    "fetch_short_urls": z.boolean().describe("Add the three-hour short URLs of recordings and voicemails.").optional(),
  }),
  examples: [
    { title: "Latest calls since 1 September 2026", input: {"date_from": 1788220800, "order": "desc", "per_page": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v1/calls",
    pathParams: [],
    query: {"from": "date_from", "to": "date_to", "order": "order", "page": "page", "per_page": "per_page", "fetch_contact": "fetch_contact", "fetch_short_urls": "fetch_short_urls"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const searchCalls = defineFunction({
  name: "aircall.search_calls",
  connector: "aircall",
  class: "read",
  description: "Search the calls of the Aircall company by direction, agent (user_id) or external phone number, bounded on their creation date. A call transferred from line A to line B is found by B only. Same history, limits and expiring URLs as list_calls.",
  schema: z.strictObject({
    "direction": z.enum(["inbound", "outbound"]).optional(),
    "user_id": z.int().gte(0).describe("The agent who made or received the calls (see list_users).").optional(),
    "phone_number": z.string().min(1).describe("The external number of the calls, E.164.").optional(),
    "date_from": z.int().gte(0).describe("Lower bound on the creation date, UNIX seconds (UTC).").optional(),
    "date_to": z.int().gte(0).describe("Upper bound on the creation date, UNIX seconds (UTC).").optional(),
    "order": z.enum(["asc", "desc"]).describe("Order by creation date; ascending when omitted.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "per_page": z.int().gte(1).lte(50).meta({"default": 20}).optional(),
    "fetch_contact": z.boolean().describe("Add the contact details of each call.").optional(),
    "fetch_short_urls": z.boolean().describe("Add the three-hour short URLs of recordings and voicemails.").optional(),
  }),
  examples: [
    { title: "Inbound calls from one number", input: {"direction": "inbound", "phone_number": "+33100000000"} },
    { title: "Outbound calls of one agent", input: {"direction": "outbound", "user_id": 123456, "order": "desc"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v1/calls/search",
    pathParams: [],
    query: {"direction": "direction", "user_id": "user_id", "phone_number": "phone_number", "from": "date_from", "to": "date_to", "order": "order", "page": "page", "per_page": "per_page", "fetch_contact": "fetch_contact", "fetch_short_urls": "fetch_short_urls"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCall = defineFunction({
  name: "aircall.get_call",
  connector: "aircall",
  class: "read",
  description: "Get one Aircall call by its id, with its recording and voicemail URLs when present. The direct URLs are valid one hour, the short URLs three hours: fetch them right before use, never store them.",
  schema: z.strictObject({
    "call_id": z.int().gte(0),
    "fetch_contact": z.boolean().describe("Add the contact details of each call.").optional(),
    "fetch_short_urls": z.boolean().describe("Add the three-hour short URLs of recordings and voicemails.").optional(),
  }),
  examples: [
    { title: "One call with its contact", input: {"call_id": 987654321, "fetch_contact": true} },
  ],
  refusals: [
    { code: "call_not_found", when: 404, message: "No call with this id in the last six months of this Aircall company." },
  ],
  request: {
    method: "GET",
    path: "/v1/calls/{call_id}",
    pathParams: ["call_id"],
    query: {"fetch_contact": "fetch_contact", "fetch_short_urls": "fetch_short_urls"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCallTranscription = defineFunction({
  name: "aircall.get_call_transcription",
  connector: "aircall",
  class: "read",
  description: "Get the transcription of one Aircall call: utterances in order, each with participant_type (internal = agent with user_id, external = caller with phone_number) and start/end offsets in seconds; content.language gives the language. Served only to companies on the Aircall AI package (AI Assist or AI Assist Pro); mode realtime needs AI Assist Pro.",
  schema: z.strictObject({
    "call_id": z.int().gte(0),
    "mode": z.enum(["async", "realtime"]).describe("async: post-call transcription; realtime: the one shown to the agent during the call.").optional(),
  }),
  examples: [
    { title: "Post-call transcription", input: {"call_id": 987654321, "mode": "async"} },
  ],
  refusals: [
    { code: "no_call_intelligence", when: 404, message: "No such content for this call: not analysed, or the company is not on the Aircall AI package." },
  ],
  request: {
    method: "GET",
    path: "/v1/calls/{call_id}/transcription",
    pathParams: ["call_id"],
    query: {"mode": "mode"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCallSummary = defineFunction({
  name: "aircall.get_call_summary",
  connector: "aircall",
  class: "read",
  description: "Get the AI summary of one Aircall call. Served only to companies on the Aircall AI package, for calls that were analysed.",
  schema: z.strictObject({
    "call_id": z.int().gte(0),
  }),
  examples: [
    { title: "Summary of a call", input: {"call_id": 987654321} },
  ],
  refusals: [
    { code: "no_call_intelligence", when: 404, message: "No such content for this call: not analysed, or the company is not on the Aircall AI package." },
  ],
  request: {
    method: "GET",
    path: "/v1/calls/{call_id}/summary",
    pathParams: ["call_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCallTopics = defineFunction({
  name: "aircall.get_call_topics",
  connector: "aircall",
  class: "read",
  description: "Get the key topics of one Aircall call, as a list of strings. Served only to companies on the Aircall AI package, for calls that were analysed.",
  schema: z.strictObject({
    "call_id": z.int().gte(0),
  }),
  examples: [
    { title: "Topics of a call", input: {"call_id": 987654321} },
  ],
  refusals: [
    { code: "no_call_intelligence", when: 404, message: "No such content for this call: not analysed, or the company is not on the Aircall AI package." },
  ],
  request: {
    method: "GET",
    path: "/v1/calls/{call_id}/topics",
    pathParams: ["call_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCallSentiments = defineFunction({
  name: "aircall.get_call_sentiments",
  connector: "aircall",
  class: "read",
  description: "Get the sentiment (POSITIVE, NEUTRAL, NEGATIVE) of each participant of one Aircall call. Served only to companies on the Aircall AI package, for calls that were analysed.",
  schema: z.strictObject({
    "call_id": z.int().gte(0),
  }),
  examples: [
    { title: "Sentiments of a call", input: {"call_id": 987654321} },
  ],
  refusals: [
    { code: "no_call_intelligence", when: 404, message: "No such content for this call: not analysed, or the company is not on the Aircall AI package." },
  ],
  request: {
    method: "GET",
    path: "/v1/calls/{call_id}/sentiments",
    pathParams: ["call_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCallActionItems = defineFunction({
  name: "aircall.get_call_action_items",
  connector: "aircall",
  class: "read",
  description: "Get the action items of one Aircall call; ai_generated false means written by an agent. Served only to companies on the Aircall AI package, for calls that were analysed.",
  schema: z.strictObject({
    "call_id": z.int().gte(0),
  }),
  examples: [
    { title: "Follow-ups of a call", input: {"call_id": 987654321} },
  ],
  refusals: [
    { code: "no_call_intelligence", when: 404, message: "No such content for this call: not analysed, or the company is not on the Aircall AI package." },
  ],
  request: {
    method: "GET",
    path: "/v1/calls/{call_id}/action_items",
    pathParams: ["call_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listUsers = defineFunction({
  name: "aircall.list_users",
  connector: "aircall",
  class: "read",
  description: "List the users (agents) of the Aircall company, bounded on their creation date: id, name, email, availability, time zone, extension. The id is the user_id of search_calls.",
  schema: z.strictObject({
    "date_from": z.int().gte(0).describe("Lower bound on the creation date, UNIX seconds (UTC).").optional(),
    "date_to": z.int().gte(0).describe("Upper bound on the creation date, UNIX seconds (UTC).").optional(),
    "order": z.enum(["asc", "desc"]).describe("Order by creation date; ascending when omitted.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "per_page": z.int().gte(1).lte(50).meta({"default": 20}).optional(),
  }),
  examples: [
    { title: "First page of users", input: {"per_page": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v2/users",
    pathParams: [],
    query: {"from": "date_from", "to": "date_to", "order": "order", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getUser = defineFunction({
  name: "aircall.get_user",
  connector: "aircall",
  class: "read",
  description: "Get one Aircall user by numeric id or by email address.",
  schema: z.strictObject({
    "user": z.string().regex(new RegExp("^([0-9]+|[^@\\s/]+@[^@\\s/]+)$")).describe("The user's numeric id or email address."),
  }),
  examples: [
    { title: "A user by email", input: {"user": "agent@acme.example"} },
    { title: "A user by id", input: {"user": "123456"} },
  ],
  refusals: [
    { code: "user_not_found", when: 404, message: "No user with this id or email in this Aircall company." },
  ],
  request: {
    method: "GET",
    path: "/v2/users/{user}",
    pathParams: ["user"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listTeams = defineFunction({
  name: "aircall.list_teams",
  connector: "aircall",
  class: "read",
  description: "List the Aircall teams (groups of users that route inbound calls), each with its users.",
  schema: z.strictObject({
    "order": z.enum(["asc", "desc"]).describe("Order by creation date; ascending when omitted.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "per_page": z.int().gte(1).lte(50).meta({"default": 20}).optional(),
  }),
  examples: [
    { title: "All teams, first page", input: {"per_page": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v1/teams",
    pathParams: [],
    query: {"order": "order", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getTeam = defineFunction({
  name: "aircall.get_team",
  connector: "aircall",
  class: "read",
  description: "Get one Aircall team with its users.",
  schema: z.strictObject({
    "team_id": z.int().gte(0),
  }),
  examples: [
    { title: "One team", input: {"team_id": 4242} },
  ],
  refusals: [
    { code: "team_not_found", when: 404, message: "No team with this id in this Aircall company." },
  ],
  request: {
    method: "GET",
    path: "/v1/teams/{team_id}",
    pathParams: ["team_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listNumbers = defineFunction({
  name: "aircall.list_numbers",
  connector: "aircall",
  class: "read",
  description: "List the phone numbers (lines) of the Aircall company, bounded on their creation date: digits, name, country, time zone, live recording, and the users on the line.",
  schema: z.strictObject({
    "date_from": z.int().gte(0).describe("Lower bound on the creation date, UNIX seconds (UTC).").optional(),
    "date_to": z.int().gte(0).describe("Upper bound on the creation date, UNIX seconds (UTC).").optional(),
    "order": z.enum(["asc", "desc"]).describe("Order by creation date; ascending when omitted.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "per_page": z.int().gte(1).lte(50).meta({"default": 20}).optional(),
  }),
  examples: [
    { title: "First page of lines", input: {"per_page": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v1/numbers",
    pathParams: [],
    query: {"from": "date_from", "to": "date_to", "order": "order", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getNumber = defineFunction({
  name: "aircall.get_number",
  connector: "aircall",
  class: "read",
  description: "Get one Aircall phone number (line) with its users.",
  schema: z.strictObject({
    "number_id": z.int().gte(0),
  }),
  examples: [
    { title: "One line", input: {"number_id": 31415} },
  ],
  refusals: [
    { code: "number_not_found", when: 404, message: "No phone number with this id in this Aircall company." },
  ],
  request: {
    method: "GET",
    path: "/v1/numbers/{number_id}",
    pathParams: ["number_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listContacts = defineFunction({
  name: "aircall.list_contacts",
  connector: "aircall",
  class: "read",
  description: "List the shared contacts of the Aircall company: name, company, phone numbers, emails. Contacts synced from third-party integrations (CRM) are not served by the API. At most 10,000 contacts through pagination: narrow with date_from beyond that.",
  schema: z.strictObject({
    "date_from": z.int().gte(0).describe("Lower bound on the creation date, UNIX seconds (UTC).").optional(),
    "date_to": z.int().gte(0).describe("Upper bound on the creation date, UNIX seconds (UTC).").optional(),
    "order": z.enum(["asc", "desc"]).describe("Order by creation date; ascending when omitted.").optional(),
    "order_by": z.enum(["created_at", "updated_at"]).describe("Sort field; created_at when omitted.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "per_page": z.int().gte(1).lte(50).meta({"default": 20}).optional(),
  }),
  examples: [
    { title: "Contacts by last update", input: {"order_by": "updated_at", "order": "desc"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v1/contacts",
    pathParams: [],
    query: {"from": "date_from", "to": "date_to", "order": "order", "order_by": "order_by", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getContact = defineFunction({
  name: "aircall.get_contact",
  connector: "aircall",
  class: "read",
  description: "Get one shared Aircall contact by its id.",
  schema: z.strictObject({
    "contact_id": z.int().gte(0),
  }),
  examples: [
    { title: "One contact", input: {"contact_id": 271828} },
  ],
  refusals: [
    { code: "contact_not_found", when: 404, message: "No shared contact with this id in this Aircall company." },
  ],
  request: {
    method: "GET",
    path: "/v1/contacts/{contact_id}",
    pathParams: ["contact_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCompany = defineFunction({
  name: "aircall.get_company",
  connector: "aircall",
  class: "read",
  description: "Get the Aircall company behind the API key: its name, number of users and number of phone numbers.",
  schema: z.strictObject({}),
  examples: [
    { title: "The connected company", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/v1/company",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "aircall",
  label: "Aircall",
  namespace: "aircall",
  version: "1.0.0",
  apiVersion: "v1 (users on v2)",
  baseUrl: "https://api.aircall.io",
  auth: {"kind": "basic", "username": "api_id", "password": "api_token"},
  credential: [{"name": "api_id", "label": "API ID", "secret": false}, {"name": "api_token", "label": "API Token", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  errors: [
    { status: 400, code: "invalid_request", message: "Aircall rejected the request as invalid: check the arguments.", retryable: false },
    { status: [401, 403], code: "access_rejected", message: "Aircall rejected the access: check api_id and api_token; the company may be inactive or not verified.", retryable: false },
    { status: 404, code: "not_found", message: "Aircall object not found: calls older than six months and contacts synced from integrations are not served.", retryable: false },
    { status: 429, code: "rate_limited", message: "Aircall rate limit reached (120 requests per minute per company): retry in a minute.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Aircall is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "aircall"},
  functions: [
    listCalls,
    searchCalls,
    getCall,
    getCallTranscription,
    getCallSummary,
    getCallTopics,
    getCallSentiments,
    getCallActionItems,
    listUsers,
    getUser,
    listTeams,
    getTeam,
    listNumbers,
    getNumber,
    listContacts,
    getContact,
    getCompany,
  ],
})
