// Generated by the fabrique from connectors/amplitude/connector.yaml. Do not edit: run `python -m fabrique`.
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const listEventTypes = defineFunction({
  name: "amplitude.list_event_types",
  connector: "amplitude",
  class: "read",
  description: "List the event types declared in this Amplitude project, with category, description and visibility. Read it before writing a query: a misspelt event name returns zeros, not an error.",
  schema: z.strictObject({}),
  examples: [
    { title: "All declared event types", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/taxonomy/event",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listEventProperties = defineFunction({
  name: "amplitude.list_event_properties",
  connector: "amplitude",
  class: "read",
  description: "List the event properties of this Amplitude project, or only those of one event type.",
  schema: z.strictObject({
    "event_type": z.string().min(1).describe("Only this event type's properties.").optional(),
  }),
  examples: [
    { title: "Properties of one event", input: {"event_type": "Sign Up"} },
    { title: "All event properties", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/taxonomy/event-property",
    pathParams: [],
    query: {"event_type": "event_type"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listUserProperties = defineFunction({
  name: "amplitude.list_user_properties",
  connector: "amplitude",
  class: "read",
  description: "List the user properties of this Amplitude project. Custom ones come back prefixed gp: — use that exact name in segments and group-bys.",
  schema: z.strictObject({}),
  examples: [
    { title: "All user properties", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/taxonomy/user-property",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listGroupProperties = defineFunction({
  name: "amplitude.list_group_properties",
  connector: "amplitude",
  class: "read",
  description: "List the group (account) properties of this Amplitude project, prefixed grp:. Empty when the project has no Accounts add-on.",
  schema: z.strictObject({}),
  examples: [
    { title: "All group properties", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/taxonomy/group-property",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listEvents = defineFunction({
  name: "amplitude.list_events",
  connector: "amplitude",
  class: "read",
  description: "List the event types with their weekly totals and uniques: what actually fires, not only what is declared.",
  schema: z.strictObject({}),
  examples: [
    { title: "Event volumes this week", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/events/list",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const getSegmentation = defineFunction({
  name: "amplitude.get_segmentation",
  connector: "amplitude",
  class: "read",
  description: "Compute one event's metric over time (event segmentation). Each query spends the project's hourly cost budget (days x conditions x query type): keep windows short or use a weekly or monthly interval. Prefer a saved chart (get_chart) when the team already has one.",
  schema: z.strictObject({
    "event": z.string().meta({"description": "JSON event object: {\"event_type\": \"Sign Up\", \"filters\": [...], \"group_by\": [{\"type\": \"event\", \"value\": \"plan\"}]}. _active is any active event, _all any event.", "contentMediaType": "application/json"}),
    "start": z.string().regex(new RegExp("^[0-9]{8}$")).describe("First day, YYYYMMDD."),
    "end": z.string().regex(new RegExp("^[0-9]{8}$")).describe("Last day, YYYYMMDD, inclusive."),
    "metric": z.enum(["uniques", "totals", "pct_dau", "average", "histogram", "sums", "value_avg", "formula"]).describe("Defaults to uniques on Amplitude's side.").optional(),
    "interval": z.literal([1, 7, 30, -3600000, -300000]).describe("1 daily (default), 7 weekly, 30 monthly, -3600000 hourly, -300000 realtime.").optional(),
    "segments": z.string().meta({"description": "JSON list of user segments to compare: [{\"prop\": \"country\", \"op\": \"is\", \"values\": [\"France\"]}].", "contentMediaType": "application/json"}).optional(),
    "group_by": z.string().min(1).describe("One property to break down by: country, gp:plan.").optional(),
    "limit": z.int().gte(1).lte(1000).describe("Group-by values returned.").optional(),
    "event2": z.string().meta({"description": "Second JSON event object, for metric formula.", "contentMediaType": "application/json"}).optional(),
    "formula": z.string().min(1).describe("Formula, for metric formula.").optional(),
  }),
  examples: [
    { title: "Daily unique sign-ups in September", input: {"event": "{\"event_type\":\"Sign Up\"}", "start": "20260901", "end": "20260930"} },
    { title: "Weekly totals by country, French users only", input: {"event": "{\"event_type\":\"Purchase\"}", "start": "20260801", "end": "20260930", "metric": "totals", "interval": 7, "segments": "[{\"prop\":\"country\",\"op\":\"is\",\"values\":[\"France\"]}]", "group_by": "city"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/events/segmentation",
    pathParams: [],
    query: {"e": "event", "e2": "event2", "m": "metric", "i": "interval", "limit": "limit", "formula": "formula", "start": "start", "end": "end", "s": "segments", "g": "group_by"},
    body: {},
    headers: {},
  },
})

export const getFunnel = defineFunction({
  name: "amplitude.get_funnel",
  connector: "amplitude",
  class: "read",
  description: "Compute the conversion through ordered steps (funnel). Spends the project's hourly cost budget. Prefer a saved chart (get_chart) when the team already has the funnel: conversion window, step order and exclusions rarely survive being re-specified.",
  schema: z.strictObject({
    "events": z.array(z.string().meta({"description": "JSON event object: {\"event_type\": \"Sign Up\", \"filters\": [...], \"group_by\": [{\"type\": \"event\", \"value\": \"plan\"}]}. _active is any active event, _all any event.", "contentMediaType": "application/json"})).min(2).describe("The steps, in order, each a JSON event object."),
    "start": z.string().regex(new RegExp("^[0-9]{8}$")).describe("First day, YYYYMMDD."),
    "end": z.string().regex(new RegExp("^[0-9]{8}$")).describe("Last day, YYYYMMDD, inclusive."),
    "mode": z.enum(["ordered", "unordered", "sequential"]).describe("Defaults to ordered.").optional(),
    "new_or_active": z.enum(["active", "new"]).describe("Defaults to active.").optional(),
    "conversion_window_seconds": z.int().gte(1).describe("Defaults to 2592000 (30 days).").optional(),
    "segments": z.string().meta({"description": "JSON list of user segments to compare: [{\"prop\": \"country\", \"op\": \"is\", \"values\": [\"France\"]}].", "contentMediaType": "application/json"}).optional(),
    "group_by": z.string().min(1).describe("One property to break down by: country, gp:plan.").optional(),
    "limit": z.int().gte(1).lte(1000).describe("Group-by values returned.").optional(),
  }),
  examples: [
    { title: "Sign-up to purchase in September", input: {"events": ["{\"event_type\":\"Sign Up\"}", "{\"event_type\":\"Purchase\"}"], "start": "20260901", "end": "20260930", "conversion_window_seconds": 604800} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/funnels",
    pathParams: [],
    query: {"e": "events", "mode": "mode", "n": "new_or_active", "cs": "conversion_window_seconds", "limit": "limit", "start": "start", "end": "end", "s": "segments", "g": "group_by"},
    body: {},
    headers: {},
  },
})

export const getRetention = defineFunction({
  name: "amplitude.get_retention",
  connector: "amplitude",
  class: "read",
  description: "Of the users who did start_event, how many came back to do return_event (use {\"event_type\": \"_active\"} for any event). Spends the project's hourly cost budget.",
  schema: z.strictObject({
    "start_event": z.string().meta({"description": "JSON event object: {\"event_type\": \"Sign Up\", \"filters\": [...], \"group_by\": [{\"type\": \"event\", \"value\": \"plan\"}]}. _active is any active event, _all any event.", "contentMediaType": "application/json"}),
    "return_event": z.string().meta({"description": "JSON event object: {\"event_type\": \"Sign Up\", \"filters\": [...], \"group_by\": [{\"type\": \"event\", \"value\": \"plan\"}]}. _active is any active event, _all any event.", "contentMediaType": "application/json"}),
    "start": z.string().regex(new RegExp("^[0-9]{8}$")).describe("First day, YYYYMMDD."),
    "end": z.string().regex(new RegExp("^[0-9]{8}$")).describe("Last day, YYYYMMDD, inclusive."),
    "mode": z.enum(["n-day", "rolling", "bracket"]).describe("Defaults to n-day.").optional(),
    "interval": z.literal([1, 7, 30]).describe("1 daily, 7 weekly, 30 monthly.").optional(),
    "segments": z.string().meta({"description": "JSON list of user segments to compare: [{\"prop\": \"country\", \"op\": \"is\", \"values\": [\"France\"]}].", "contentMediaType": "application/json"}).optional(),
    "group_by": z.string().min(1).describe("One property to break down by: country, gp:plan.").optional(),
  }),
  examples: [
    { title: "Weekly retention of new sign-ups", input: {"start_event": "{\"event_type\":\"Sign Up\"}", "return_event": "{\"event_type\":\"_active\"}", "start": "20260801", "end": "20260930", "interval": 7} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/retention",
    pathParams: [],
    query: {"se": "start_event", "re": "return_event", "rm": "mode", "i": "interval", "start": "start", "end": "end", "s": "segments", "g": "group_by"},
    body: {},
    headers: {},
  },
})

export const getActiveUsers = defineFunction({
  name: "amplitude.get_active_users",
  connector: "amplitude",
  class: "read",
  description: "Count active (default) or new users over time. Spends the project's hourly cost budget.",
  schema: z.strictObject({
    "start": z.string().regex(new RegExp("^[0-9]{8}$")).describe("First day, YYYYMMDD."),
    "end": z.string().regex(new RegExp("^[0-9]{8}$")).describe("Last day, YYYYMMDD, inclusive."),
    "metric": z.enum(["active", "new"]).describe("Defaults to active.").optional(),
    "interval": z.literal([1, 7, 30]).describe("1 daily, 7 weekly, 30 monthly.").optional(),
    "segments": z.string().meta({"description": "JSON list of user segments to compare: [{\"prop\": \"country\", \"op\": \"is\", \"values\": [\"France\"]}].", "contentMediaType": "application/json"}).optional(),
    "group_by": z.string().min(1).describe("One property to break down by: country, gp:plan.").optional(),
  }),
  examples: [
    { title: "Monthly new users this year", input: {"start": "20260101", "end": "20260930", "metric": "new", "interval": 30} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/users",
    pathParams: [],
    query: {"m": "metric", "i": "interval", "start": "start", "end": "end", "s": "segments", "g": "group_by"},
    body: {},
    headers: {},
  },
})

export const getSessions = defineFunction({
  name: "amplitude.get_sessions",
  connector: "amplitude",
  class: "read",
  description: "Session metrics over a window: length (distribution of session lengths), average (average session length) or peruser (sessions per user).",
  schema: z.strictObject({
    "kind": z.enum(["length", "average", "peruser"]),
    "start": z.string().regex(new RegExp("^[0-9]{8}$")).describe("First day, YYYYMMDD."),
    "end": z.string().regex(new RegExp("^[0-9]{8}$")).describe("Last day, YYYYMMDD, inclusive."),
  }),
  examples: [
    { title: "Average session length in September", input: {"kind": "average", "start": "20260901", "end": "20260930"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/sessions/{kind}",
    pathParams: ["kind"],
    query: {"start": "start", "end": "end"},
    body: {},
    headers: {},
  },
})

export const getChart = defineFunction({
  name: "amplitude.get_chart",
  connector: "amplitude",
  class: "read",
  description: "Run a saved Amplitude chart and return its results as JSON, computed by Amplitude with the chart's own definition: the number the team reads in Amplitude. The chart id is the last segment of the chart URL.",
  schema: z.strictObject({
    "chart_id": z.string().regex(new RegExp("^[^/?#\\s.][^/?#\\s]*$")),
  }),
  examples: [
    { title: "One saved chart", input: {"chart_id": "abc123x"} },
  ],
  refusals: [
    { code: "chart_not_found", when: 404, message: "No saved chart with this id in this Amplitude project." },
  ],
  request: {
    method: "GET",
    path: "/api/3/chart/{chart_id}/query",
    pathParams: ["chart_id"],
    query: {},
    body: {},
    headers: {},
  },
})

export const searchUsers = defineFunction({
  name: "amplitude.search_users",
  connector: "amplitude",
  class: "read",
  description: "Find a user by user id, device id or Amplitude id. Returns the matches with their amplitude_id, needed to read the user's activity. Shares a budget of 360 calls per hour with get_user_activity.",
  schema: z.strictObject({
    "user": z.string().min(1).describe("User id, device id or Amplitude id."),
  }),
  examples: [
    { title: "Find a user by their user id", input: {"user": "user-1042"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/usersearch",
    pathParams: [],
    query: {"user": "user"},
    body: {},
    headers: {},
  },
  output: { items: "matches" },
})

export const getUserActivity = defineFunction({
  name: "amplitude.get_user_activity",
  connector: "amplitude",
  class: "read",
  description: "Read one user's summary and event stream. Takes the amplitude_id returned by search_users, not the user id.",
  schema: z.strictObject({
    "amplitude_id": z.string().regex(new RegExp("^[0-9]+$")).describe("From search_users."),
    "offset": z.int().gte(0).optional(),
    "limit": z.int().gte(1).lte(1000).describe("Events returned, Amplitude default 1000.").optional(),
    "direction": z.enum(["latest", "earliest"]).describe("Defaults to latest.").optional(),
  }),
  examples: [
    { title: "Latest 50 events of a user", input: {"amplitude_id": "123456789", "limit": 50} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/2/useractivity",
    pathParams: [],
    query: {"user": "amplitude_id", "offset": "offset", "limit": "limit", "direction": "direction"},
    body: {},
    headers: {},
  },
})

export const listCohorts = defineFunction({
  name: "amplitude.list_cohorts",
  connector: "amplitude",
  class: "read",
  description: "List the project's behavioral cohorts: id, name, size, last computed.",
  schema: z.strictObject({}),
  examples: [
    { title: "All cohorts", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/3/cohorts",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { items: "cohorts" },
})

export const requestCohortDownload = defineFunction({
  name: "amplitude.request_cohort_download",
  connector: "amplitude",
  class: "write",
  description: "Start a download job for one cohort and return its request_id. Each request counts against the project's 500 cohort downloads per month. Poll get_cohort_download_status with the request_id until JOB COMPLETED.",
  schema: z.strictObject({
    "cohort_id": z.string().regex(new RegExp("^[^/?#\\s.][^/?#\\s]*$")).describe("From list_cohorts."),
    "props": z.literal([0, 1]).meta({"description": "1 includes user properties in the file.", "default": 0}).optional(),
  }),
  examples: [
    { title: "Download a cohort with user properties", input: {"cohort_id": "x7y8z9", "props": 1} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/5/cohorts/request/{cohort_id}",
    pathParams: ["cohort_id"],
    query: {"props": "props"},
    body: {},
    headers: {},
  },
})

export const getCohortDownloadStatus = defineFunction({
  name: "amplitude.get_cohort_download_status",
  connector: "amplitude",
  class: "read",
  description: "Read the status of a cohort download job: async_status is JOB INPROGRESS while running, JOB COMPLETED when the file is ready.",
  schema: z.strictObject({
    "request_id": z.string().regex(new RegExp("^[^/?#\\s.][^/?#\\s]*$")).describe("From request_cohort_download."),
  }),
  examples: [
    { title: "Status of a download job", input: {"request_id": "req-4f2a"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/api/5/cohorts/request-status/{request_id}",
    pathParams: ["request_id"],
    query: {},
    body: {},
    headers: {},
  },
})

export const connector = defineConnector({
  name: "amplitude",
  label: "Amplitude",
  namespace: "amplitude",
  version: "1.0.0",
  apiVersion: "Dashboard REST and Taxonomy api/2; charts and cohort list api/3; cohort download api/5",
  baseUrl: "https://amplitude.com",
  auth: {"kind": "basic", "username": "api_key", "password": "secret_key"},
  credential: [{"name": "api_key", "label": "API key", "secret": true}, {"name": "secret_key", "label": "Secret key", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  queryArrays: "repeat",
  errors: [
    { status: 400, code: "invalid_request", message: "Amplitude rejected the request as invalid: check the arguments and the exact event and property names.", retryable: false },
    { status: [401, 403], code: "access_rejected", message: "Amplitude refused the key pair: \"Invalid API Key\" means the key is unknown on this host (the project may live in the EU region); \"Invalid API/Secret Key combination\" means the secret key is wrong or missing.", retryable: false },
    { status: 404, code: "not_found", message: "Amplitude object not found: check the id.", retryable: false },
    { status: 429, code: "rate_limited", message: "Amplitude query budget or concurrency limit reached for this project: retry later, or query a shorter window.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Amplitude is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "amplitude"},
  functions: [
    listEventTypes,
    listEventProperties,
    listUserProperties,
    listGroupProperties,
    listEvents,
    getSegmentation,
    getFunnel,
    getRetention,
    getActiveUsers,
    getSessions,
    getChart,
    searchUsers,
    getUserActivity,
    listCohorts,
    requestCohortDownload,
    getCohortDownloadStatus,
  ],
})
