// Generated by the fabrique from connectors/claap/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const listRecordings = defineFunction({
  name: "claap.list_recordings",
  connector: "claap",
  class: "read",
  description: "List the Claap meeting and call recordings visible to the key, newest first, one page at a time; pass pagination.nextCursor back as cursor for the next page. The key belongs to the workspace, not to a person: without recorder_email or recorder_id it returns every recording visible in Claap's global search, colleagues' meetings included. view_id applies a saved view's filters and sort; other filters narrow within it. Signed URLs in the result (video, transcript files, thumbnail) expire after 24 hours: never store them.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "dependentRequired": {"labels": ["channel_id"]},
    "properties": {
      "recorder_email": {"type": "string", "minLength": 1, "description": "Only recordings by this author (email)."},
      "recorder_id": {"type": "string", "minLength": 1, "description": "Only recordings by this author (Claap user id)."},
      "created_after": {
        "type": "string",
        "minLength": 1,
        "description": "ISO 8601 date or date-time lower bound (2026-09-01, 2026-09-01T13:00Z)."
      },
      "created_before": {"type": "string", "minLength": 1, "description": "ISO 8601 date or date-time upper bound."},
      "channel_id": {"type": "string", "minLength": 1, "description": "Only recordings of this folder (channel)."},
      "labels": {
        "type": "array",
        "minItems": 1,
        "items": {"type": "string", "pattern": "^[^,]+$"},
        "description": "Label names, any match. Claap accepts labels only together with channel_id."
      },
      "sources": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "enum": [
            "Aircall",
            "Allo",
            "Api",
            "Call",
            "GoogleMeet",
            "LemlistVoip",
            "Loom",
            "MobileApp",
            "MsTeams",
            "Ringover",
            "Uploaded",
            "Zoom"
          ]
        },
        "description": "Platforms the recordings were captured from, any match."
      },
      "view_id": {"type": "string", "minLength": 1, "description": "A saved view id, from list_recording_views."},
      "sort": {
        "type": "string",
        "enum": ["created_asc", "created_desc", "duration_asc", "duration_desc", "title_asc", "title_desc"],
        "description": "Overrides the view's sort; created_desc when omitted and no view is set."
      },
      "cursor": {"type": "string", "minLength": 1, "description": "pagination.nextCursor of the previous page."},
      "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20}
    }
  },
  examples: [
    { title: "One person's latest recordings", input: {"recorder_email": "jane.doe@acme.example", "limit": 20} },
    { title: "Recordings of a folder with a label", input: {"channel_id": "ch_abc123", "labels": ["Demo"], "sources": ["GoogleMeet", "Zoom"]} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/recordings",
    pathParams: [],
    query: {"cursor": "cursor", "limit": "limit", "sort": "sort", "channelId": "channel_id", "labels": "labels", "sources": "sources", "recorderEmail": "recorder_email", "recorderId": "recorder_id", "createdAfter": "created_after", "createdBefore": "created_before", "viewId": "view_id"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getRecording = defineFunction({
  name: "claap.get_recording",
  connector: "claap",
  class: "read",
  description: "Get one Claap recording. Check state: only Ready carries the full payload (AI summary keyTakeaways and outlines, actionItems, aiFields, deal and companies, analytics, transcripts); Empty, Uploaded and Failed return a thin shape (id, title, author, upload). Signed URLs expire after 24 hours. A 404 can also mean the recording is private or hidden from global search.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["recording_id"],
    "properties": {"recording_id": {"type": "string", "minLength": 1, "not": {"enum": [".", ".."]}}}
  },
  examples: [
    { title: "One recording", input: {"recording_id": "rec_abc123"} },
  ],
  refusals: [
    { code: "recording_not_found", when: 404, message: "No recording with this id visible to this key: it may not exist, or be private or hidden from global search." },
  ],
  request: {
    method: "GET",
    path: "/recordings/{recording_id}",
    pathParams: ["recording_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getRecordingTranscript = defineFunction({
  name: "claap.get_recording_transcript",
  connector: "claap",
  class: "read",
  description: "Get the transcript of one Claap recording. format text returns plain text lines \"mm:ss speaker: text\", the readable choice; format json (the default) returns timed segments with per-word detail and is very heavy. lang picks a translation; the available languages are in transcripts[].langIso2 of get_recording.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["recording_id"],
    "properties": {
      "recording_id": {"type": "string", "minLength": 1, "not": {"enum": [".", ".."]}},
      "format": {"type": "string", "enum": ["json", "text"], "default": "json"},
      "lang": {
        "type": "string",
        "pattern": "^[a-z]{2}$",
        "description": "Two-letter code of a translation; the original when omitted."
      }
    }
  },
  examples: [
    { title: "Readable transcript", input: {"recording_id": "rec_abc123", "format": "text"} },
    { title: "English translation", input: {"recording_id": "rec_abc123", "format": "text", "lang": "en"} },
  ],
  refusals: [
    { code: "transcript_not_found", when: 404, message: "No transcript for this recording in this language, or the recording is not visible to this key." },
  ],
  request: {
    method: "GET",
    path: "/recordings/{recording_id}/transcript",
    pathParams: ["recording_id"],
    query: {"lang": "lang", "format": "format"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteRecording = defineFunction({
  name: "claap.delete_recording",
  connector: "claap",
  class: "sensitive",
  description: "Delete one Claap recording. Permanent: Claap has no trash and no undo. Read it with get_recording first to be sure of what is deleted.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["recording_id"],
    "properties": {"recording_id": {"type": "string", "minLength": 1, "not": {"enum": [".", ".."]}}}
  },
  examples: [
    { title: "Delete one recording", input: {"recording_id": "rec_abc123"} },
  ],
  refusals: [
    { code: "recording_not_found", when: 404, message: "No recording with this id visible to this key: it may not exist, or be private or hidden from global search." },
  ],
  request: {
    method: "DELETE",
    path: "/recordings/{recording_id}",
    pathParams: ["recording_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Delete Claap recording {recording_id}: permanent, cannot be undone." },
})

export const listRecordingViews = defineFunction({
  name: "claap.list_recording_views",
  connector: "claap",
  class: "read",
  description: "List the saved Claap recording views: public views first, then the built-in defaults (isDefault true). Private views are invisible to the API. A view filtering on Me matches the whole workspace here, since the key is nobody in particular. Pass a view id as view_id to list_recordings.",
  schema: {"type": "object", "additionalProperties": false, "properties": {}},
  examples: [
    { title: "All visible views", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/recordings/views",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getRecordingView = defineFunction({
  name: "claap.get_recording_view",
  connector: "claap",
  class: "read",
  description: "Get one saved Claap recording view: its columns, filters and sort.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["view_id"],
    "properties": {"view_id": {"type": "string", "minLength": 1, "not": {"enum": [".", ".."]}}}
  },
  examples: [
    { title: "One view", input: {"view_id": "view_abc123"} },
  ],
  refusals: [
    { code: "view_not_found", when: 404, message: "No public view with this id: a private view is not visible to the API." },
  ],
  request: {
    method: "GET",
    path: "/recordings/views/{view_id}",
    pathParams: ["view_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "claap",
  label: "Claap",
  namespace: "claap",
  version: "1.0.1",
  apiVersion: "v1",
  baseUrl: "https://api.claap.io/v1",
  auth: {"kind": "api_key", "in": "header", "name": "X-Claap-Key", "key": "api_key"},
  credential: [{"name": "api_key", "label": "Workspace API key", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  queryArrays: "comma",
  errors: [
    { status: 400, code: "invalid_request", message: "Claap rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Claap rejected the API key: check the workspace key.", retryable: false },
    { status: 403, code: "not_allowed", message: "Claap refused the operation: the workspace plan or the permissions do not allow it.", retryable: false },
    { status: 404, code: "not_found", message: "Claap object not found, or not visible to this key.", retryable: false },
    { status: 429, code: "rate_limited", message: "Claap rate limit reached (3 per second per endpoint, 3,000 per day per workspace): retry later.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Claap is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "claap"},
  functions: [
    listRecordings,
    getRecording,
    getRecordingTranscript,
    deleteRecording,
    listRecordingViews,
    getRecordingView,
  ],
})
