// Generated by the fabrique from connectors/claap/connector.yaml. Do not edit: run `python -m fabrique`.
// Not generated:
// - claap.list_recordings: input: dependentRequired at the root needs a refinement
// - claap.get_recording: input.recording_id: not needs a refinement
// - claap.get_recording_transcript: input.recording_id: not needs a refinement
// - claap.delete_recording: input.recording_id: not needs a refinement
// - claap.get_recording_view: input.view_id: not needs a refinement
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const listRecordingViews = defineFunction({
  name: "claap.list_recording_views",
  connector: "claap",
  class: "read",
  description: "List the saved Claap recording views: public views first, then the built-in defaults (isDefault true). Private views are invisible to the API. A view filtering on Me matches the whole workspace here, since the key is nobody in particular. Pass a view id as view_id to list_recordings.",
  schema: z.strictObject({}),
  examples: [
    { title: "All visible views", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/recordings/views",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "claap",
  label: "Claap",
  namespace: "claap",
  version: "1.0.0",
  apiVersion: "v1",
  baseUrl: "https://api.claap.io/v1",
  auth: {"kind": "api_key", "header": "X-Claap-Key", "key": "api_key"},
  credential: [{"name": "api_key", "label": "Workspace API key", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  queryArrays: "comma",
  errors: [
    { status: 400, code: "invalid_request", message: "Claap rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Claap rejected the API key: check the workspace key.", retryable: false },
    { status: 403, code: "not_allowed", message: "Claap refused the operation: the workspace plan or the permissions do not allow it.", retryable: false },
    { status: 404, code: "not_found", message: "Claap object not found, or not visible to this key.", retryable: false },
    { status: 429, code: "rate_limited", message: "Claap rate limit reached (3 per second per endpoint, 3,000 per day per workspace): retry later.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Claap is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "claap"},
  functions: [
    listRecordingViews,
  ],
})
