// Generated by the fabrique from connectors/*/connector.yaml. Do not edit: run `python -m fabrique`.
import * as affinity from "./affinity"
import * as aircall from "./aircall"
import * as amplitude from "./amplitude"
import * as claap from "./claap"
import * as mailpool from "./mailpool"
import * as metaAds from "./meta_ads"
import * as microsoft from "./microsoft"
import * as nextmotion from "./nextmotion"
import * as notion from "./notion"
import * as pennylane from "./pennylane"
import * as sellsy from "./sellsy"
import * as typeform from "./typeform"
import * as wttjAts from "./wttj_ats"
import type { Connector } from "./types"

export { affinity }
export { aircall }
export { amplitude }
export { claap }
export { mailpool }
export { metaAds }
export { microsoft }
export { nextmotion }
export { notion }
export { pennylane }
export { sellsy }
export { typeform }
export { wttjAts }
export type * from "./types"

/** Every generated connector, in name order; each module keeps its precise types. */
export const connectors: readonly Connector[] = [
  affinity.connector,
  aircall.connector,
  amplitude.connector,
  claap.connector,
  mailpool.connector,
  metaAds.connector,
  microsoft.connector,
  nextmotion.connector,
  notion.connector,
  pennylane.connector,
  sellsy.connector,
  typeform.connector,
  wttjAts.connector,
]
