// Generated by the fabrique from connectors/klaviyo/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const getAccount = defineFunction({
  name: "klaviyo.get_account",
  connector: "klaviyo",
  class: "read",
  description: "Get the Klaviyo account the private key belongs to: {data: [{type: account, id, attributes: {contact_information: {organization_name, default_sender_name, default_sender_email, website_url, street_address}, industry, timezone, preferred_currency, public_api_key, locale}}]}, always one account. Checks that the key works and which account it reaches. Scope accounts:read; at most 1 call per second and 15 per minute.",
  schema: {"type": "object", "additionalProperties": false, "properties": {}},
  examples: [
    { title: "The account of the key", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/accounts",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listProfiles = defineFunction({
  name: "klaviyo.list_profiles",
  connector: "klaviyo",
  class: "read",
  description: "List the profiles of the account: {data: [{type: profile, id, attributes: {email, phone_number, external_id, first_name, last_name, organization, title, locale, location, properties, created, updated, last_event_date}}], links: {self, next, prev}}. The id (26 characters, 01H...) is what get_profile, the list membership functions and filters on profile_id take. To find one person, filter equals(email,\"jane@example.com\") rather than paging. links.next is a full URL: for the next page, pass the value of its page[cursor] parameter as page_cursor; no links.next means the last page. Scope profiles:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Filter expression; clauses joined by a comma are ANDed. Fields: id, email, phone_number, external_id (equals, any); created, updated (greater-than, less-than); subscriptions.email.marketing.suppression.reason (equals) and .timestamp (greater-or-equal, greater-than, less-or-equal, less-than); subscriptions.email.marketing.list_suppressions.reason, .list_id (equals) and .timestamp (same comparisons). Strings are quoted, datetimes are not: equals(email,\"jane@example.com\"), greater-than(updated,2026-09-01T00:00:00Z), any(email,[\"a@example.com\",\"b@example.com\"])."
      },
      "sort": {
        "enum": [
          "created",
          "-created",
          "email",
          "-email",
          "id",
          "-id",
          "updated",
          "-updated",
          "subscriptions.email.marketing.suppression.timestamp",
          "-subscriptions.email.marketing.suppression.timestamp",
          "subscriptions.email.marketing.list_suppressions.timestamp",
          "-subscriptions.email.marketing.list_suppressions.timestamp"
        ],
        "description": "Sort key; a leading - sorts descending."
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      },
      "additional_fields": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {"enum": ["subscriptions", "predictive_analytics"]},
        "description": "Extra attributes: subscriptions (consent per channel, with suppressions), predictive_analytics (predicted CLV, churn, next order date). Requested extras are paced more strictly by Klaviyo."
      }
    }
  },
  examples: [
    { title: "The profile of one email address, with its consent", input: {"filter": "equals(email,\"jane@example.com\")", "additional_fields": ["subscriptions"]} },
    { title: "Profiles updated since 1 September 2026, newest first", input: {"filter": "greater-than(updated,2026-09-01T00:00:00Z)", "sort": "-updated", "page_size": 100} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/profiles",
    pathParams: [],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor", "additional-fields[profile]": "additional_fields"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getProfile = defineFunction({
  name: "klaviyo.get_profile",
  connector: "klaviyo",
  class: "read",
  description: "Get one profile by its id (from list_profiles or a list or segment): {data: {type: profile, id, attributes: {email, phone_number, external_id, first_name, last_name, organization, title, locale, location, properties, created, updated, last_event_date}}, included}. include: [lists, segments] adds the lists and segments it belongs to in included. Scopes profiles:read, plus lists:read or segments:read for include.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["profile_id"],
    "properties": {
      "profile_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo profile id (26 characters, 01H...), not an email address."
      },
      "additional_fields": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {"enum": ["subscriptions", "predictive_analytics"]},
        "description": "Extra attributes: subscriptions (consent per channel, with suppressions), predictive_analytics (predicted CLV, churn, next order date). Requested extras are paced more strictly by Klaviyo."
      },
      "include": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {"enum": ["lists", "segments"]},
        "description": "Related resources returned in included."
      }
    }
  },
  examples: [
    { title: "One profile with its lists and segments", input: {"profile_id": "01HZX8A6R0J3VQ2N9P4K7T5M1B", "include": ["lists", "segments"]} },
  ],
  refusals: [
    { code: "profile_not_found", when: 404, message: "No profile with this id in this Klaviyo account: read the ids from the list of profiles, filtered by email." },
  ],
  request: {
    method: "GET",
    path: "/profiles/{profile_id}",
    pathParams: ["profile_id"],
    query: {"additional-fields[profile]": "additional_fields", "include": "include"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const createOrUpdateProfile = defineFunction({
  name: "klaviyo.create_or_update_profile",
  connector: "klaviyo",
  class: "write",
  description: "Create a profile, or update the one that matches: data.id when given, else the email, phone_number or external_id in attributes. Returns {data: {type: profile, id, attributes}} with status 201 when created, 200 when updated. A field left out stays unchanged, a field set to null is cleared; properties merges custom properties. meta.patch_properties appends to, removes from or unsets custom properties. This does not change marketing consent. Scope profiles:write.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "anyOf": [
          {"required": ["id"]},
          {
            "properties": {
              "attributes": {
                "anyOf": [{"required": ["email"]}, {"required": ["phone_number"]}, {"required": ["external_id"]}]
              }
            }
          }
        ],
        "properties": {
          "type": {"const": "profile"},
          "id": {"type": "string", "pattern": "^[A-Za-z0-9]+$", "description": "Profile id: update this profile."},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "email": {"type": ["string", "null"]},
              "phone_number": {"type": ["string", "null"], "description": "E.164, e.g. +33612345678."},
              "external_id": {"type": ["string", "null"], "description": "Id of the person in another system."},
              "first_name": {"type": ["string", "null"]},
              "last_name": {"type": ["string", "null"]},
              "organization": {"type": ["string", "null"]},
              "title": {"type": ["string", "null"]},
              "locale": {"type": ["string", "null"], "description": "IETF BCP 47, e.g. fr-FR."},
              "image": {"type": ["string", "null"], "description": "URL of a picture."},
              "location": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "address1": {"type": ["string", "null"]},
                  "address2": {"type": ["string", "null"]},
                  "city": {"type": ["string", "null"]},
                  "region": {"type": ["string", "null"]},
                  "zip": {"type": ["string", "null"]},
                  "country": {"type": ["string", "null"]},
                  "timezone": {"type": ["string", "null"], "description": "IANA time zone, e.g. Europe/Paris."},
                  "ip": {"type": ["string", "null"]},
                  "latitude": {"type": ["string", "number", "null"]},
                  "longitude": {"type": ["string", "number", "null"]}
                }
              },
              "properties": {"type": ["object", "null"], "description": "Custom properties, merged into the existing ones."}
            }
          },
          "meta": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "patch_properties": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "append": {
                    "type": "object",
                    "description": "Values appended to array properties: {property: value or [values]}."
                  },
                  "unappend": {"type": "object", "description": "Values removed from array properties."},
                  "unset": {
                    "anyOf": [{"type": "string"}, {"type": "array", "items": {"type": "string"}}],
                    "description": "Property name or names removed entirely."
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  examples: [
    { title: "Create or update a profile by email", input: {"data": {"type": "profile", "attributes": {"email": "jane@example.com", "first_name": "Jane", "last_name": "Doe", "location": {"city": "Lyon", "country": "France"}, "properties": {"plan": "pro"}}}} },
    { title: "Clear the phone number of a known profile", input: {"data": {"type": "profile", "id": "01HZX8A6R0J3VQ2N9P4K7T5M1B", "attributes": {"phone_number": null}}} },
  ],
  refusals: [
    { code: "profile_conflict", when: 409, message: "Another profile already holds one of these identifiers (email, phone_number or external_id): read that profile from the list of profiles before writing." },
  ],
  request: {
    method: "POST",
    path: "/profile-import",
    pathParams: [],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
})

export const listLists = defineFunction({
  name: "klaviyo.list_lists",
  connector: "klaviyo",
  class: "read",
  description: "List the lists of the account, at most 10 per page: {data: [{type: list, id, attributes: {name, created, updated, opt_in_process}}], links: {next}}. The id (6 characters, e.g. Y6nRLr) is what get_list, list_profiles_in_list and the membership and consent functions take. For the next page, pass the page[cursor] value of links.next as page_cursor. Scope lists:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: name, id (equals, any); created, updated (greater-than). E.g. equals(name,\"Newsletter\")."
      },
      "sort": {"enum": ["created", "-created", "id", "-id", "name", "-name", "updated", "-updated"]},
      "page_size": {"type": "integer", "minimum": 1, "maximum": 10, "default": 10},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "The list named Newsletter", input: {"filter": "equals(name,\"Newsletter\")"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/lists",
    pathParams: [],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getList = defineFunction({
  name: "klaviyo.get_list",
  connector: "klaviyo",
  class: "read",
  description: "Get one list by its id: {data: {type: list, id, attributes: {name, created, updated, opt_in_process}}}. opt_in_process is double_opt_in when subscribing to it sends a confirmation message. additional_fields: [profile_count] adds the member count, paced by Klaviyo at 1 call per second and 15 per minute. Scope lists:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id"],
    "properties": {
      "list_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo list id (6 characters, e.g. Y6nRLr), from list_lists."
      },
      "additional_fields": {"type": "array", "minItems": 1, "uniqueItems": true, "items": {"enum": ["profile_count"]}}
    }
  },
  examples: [
    { title: "One list with its member count", input: {"list_id": "Y6nRLr", "additional_fields": ["profile_count"]} },
  ],
  refusals: [
    { code: "list_not_found", when: 404, message: "No list with this id in this Klaviyo account: read the ids from the list of lists." },
  ],
  request: {
    method: "GET",
    path: "/lists/{list_id}",
    pathParams: ["list_id"],
    query: {"additional-fields[list]": "additional_fields"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listProfilesInList = defineFunction({
  name: "klaviyo.list_profiles_in_list",
  connector: "klaviyo",
  class: "read",
  description: "List the profiles that belong to one list: {data: [{type: profile, id, attributes: {email, phone_number, external_id, first_name, last_name, properties, ...}}], links: {next}}. For the next page, pass the page[cursor] value of links.next as page_cursor. Scopes lists:read and profiles:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id"],
    "properties": {
      "list_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo list id (6 characters, e.g. Y6nRLr), from list_lists."
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: email, phone_number, push_token (equals, any); joined_group_at (greater-or-equal, greater-than, less-or-equal, less-than). E.g. greater-than(joined_group_at,2026-09-01T00:00:00Z)."
      },
      "sort": {"enum": ["joined_group_at", "-joined_group_at"]},
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "Members who joined since 1 September 2026", input: {"list_id": "Y6nRLr", "filter": "greater-than(joined_group_at,2026-09-01T00:00:00Z)", "page_size": 100} },
  ],
  refusals: [
    { code: "list_not_found", when: 404, message: "No list with this id in this Klaviyo account: read the ids from the list of lists." },
  ],
  request: {
    method: "GET",
    path: "/lists/{list_id}/profiles",
    pathParams: ["list_id"],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const addProfilesToList = defineFunction({
  name: "klaviyo.add_profiles_to_list",
  connector: "klaviyo",
  class: "sensitive",
  description: "Add existing profiles to a list, up to 1000 per call, by profile id (create_or_update_profile returns it). Answers 204 without a body. This does not give marketing consent: subscribe_profiles does. Flows triggered by this list (Added to List) start for the added profiles and may send them messages. Scopes lists:write and profiles:write.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "data"],
    "properties": {
      "list_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo list id (6 characters, e.g. Y6nRLr), from list_lists."
      },
      "data": {
        "type": "array",
        "minItems": 1,
        "maxItems": 1000,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": ["type", "id"],
          "properties": {"type": {"const": "profile"}, "id": {"type": "string", "pattern": "^[A-Za-z0-9]+$"}}
        },
        "description": "The profiles, each {type: profile, id}."
      }
    }
  },
  examples: [
    { title: "Add one profile to a list", input: {"list_id": "Y6nRLr", "data": [{"type": "profile", "id": "01HZX8A6R0J3VQ2N9P4K7T5M1B"}]} },
  ],
  refusals: [
    { code: "list_not_found", when: 404, message: "No list with this id in this Klaviyo account: read the ids from the list of lists." },
  ],
  request: {
    method: "POST",
    path: "/lists/{list_id}/relationships/profiles",
    pathParams: ["list_id"],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Add these profiles to Klaviyo list {list_id}: flows triggered by this list start for them and may send messages." },
})

export const removeProfilesFromList = defineFunction({
  name: "klaviyo.remove_profiles_from_list",
  connector: "klaviyo",
  class: "write",
  description: "Remove profiles from a list, up to 1000 per call, by profile id. Answers 204 without a body. Their consent is unchanged: they only stop receiving what targets this list (unsubscribe_profiles changes consent). Scopes lists:write and profiles:write.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["list_id", "data"],
    "properties": {
      "list_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo list id (6 characters, e.g. Y6nRLr), from list_lists."
      },
      "data": {
        "type": "array",
        "minItems": 1,
        "maxItems": 1000,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": ["type", "id"],
          "properties": {"type": {"const": "profile"}, "id": {"type": "string", "pattern": "^[A-Za-z0-9]+$"}}
        },
        "description": "The profiles, each {type: profile, id}."
      }
    }
  },
  examples: [
    { title: "Remove one profile from a list", input: {"list_id": "Y6nRLr", "data": [{"type": "profile", "id": "01HZX8A6R0J3VQ2N9P4K7T5M1B"}]} },
  ],
  refusals: [
    { code: "list_not_found", when: 404, message: "No list with this id in this Klaviyo account: read the ids from the list of lists." },
  ],
  request: {
    method: "DELETE",
    path: "/lists/{list_id}/relationships/profiles",
    pathParams: ["list_id"],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
})

export const listSegments = defineFunction({
  name: "klaviyo.list_segments",
  connector: "klaviyo",
  class: "read",
  description: "List the segments of the account, at most 10 per page: {data: [{type: segment, id, attributes: {name, created, updated, is_active, is_processing, is_starred}}], links: {next}}. A segment is computed from its definition: its members cannot be added or removed directly. For the next page, pass the page[cursor] value of links.next as page_cursor. Scope segments:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: name, id (equals, any); created, updated (greater-than); is_active (equals, any); is_starred (equals). E.g. equals(is_active,true)."
      },
      "sort": {"enum": ["created", "-created", "id", "-id", "name", "-name", "updated", "-updated"]},
      "page_size": {"type": "integer", "minimum": 1, "maximum": 10, "default": 10},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "Active segments", input: {"filter": "equals(is_active,true)"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/segments",
    pathParams: [],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getSegment = defineFunction({
  name: "klaviyo.get_segment",
  connector: "klaviyo",
  class: "read",
  description: "Get one segment by its id: {data: {type: segment, id, attributes: {name, definition, created, updated, is_active, is_processing, is_starred}}}. additional_fields: [profile_count] adds the member count, paced by Klaviyo at 1 call per second and 15 per minute. Scope segments:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["segment_id"],
    "properties": {
      "segment_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo segment id, from list_segments."
      },
      "additional_fields": {"type": "array", "minItems": 1, "uniqueItems": true, "items": {"enum": ["profile_count"]}}
    }
  },
  examples: [
    { title: "One segment with its member count", input: {"segment_id": "Xy12Ab", "additional_fields": ["profile_count"]} },
  ],
  refusals: [
    { code: "segment_not_found", when: 404, message: "No segment with this id in this Klaviyo account: read the ids from the list of segments." },
  ],
  request: {
    method: "GET",
    path: "/segments/{segment_id}",
    pathParams: ["segment_id"],
    query: {"additional-fields[segment]": "additional_fields"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listProfilesInSegment = defineFunction({
  name: "klaviyo.list_profiles_in_segment",
  connector: "klaviyo",
  class: "read",
  description: "List the profiles that belong to one segment: {data: [{type: profile, id, attributes: {email, phone_number, external_id, first_name, last_name, properties, ...}}], links: {next}}. For the next page, pass the page[cursor] value of links.next as page_cursor. Scopes segments:read and profiles:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["segment_id"],
    "properties": {
      "segment_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo segment id, from list_segments."
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: profile_id, email, phone_number, push_token (equals, any); joined_group_at (greater-or-equal, greater-than, less-or-equal, less-than). E.g. equals(email,\"jane@example.com\")."
      },
      "sort": {"enum": ["joined_group_at", "-joined_group_at"]},
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "Is this email in the segment", input: {"segment_id": "Xy12Ab", "filter": "equals(email,\"jane@example.com\")"} },
  ],
  refusals: [
    { code: "segment_not_found", when: 404, message: "No segment with this id in this Klaviyo account: read the ids from the list of segments." },
  ],
  request: {
    method: "GET",
    path: "/segments/{segment_id}/profiles",
    pathParams: ["segment_id"],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listCampaigns = defineFunction({
  name: "klaviyo.list_campaigns",
  connector: "klaviyo",
  class: "read",
  description: "List the campaigns of one channel: {data: [{type: campaign, id, attributes: {name, status, archived, audiences: {included, excluded}, send_options, tracking_options, send_strategy, created_at, scheduled_at, updated_at, send_time}}], links: {next}}. Klaviyo requires the channel in the filter: equals(messages.channel,'email'), 'sms' or 'mobile_push'. The id goes to get_campaign and to the campaign_id grouping of query_campaign_values. For the next page, pass the page[cursor] value of links.next as page_cursor. Scope campaigns:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["filter"],
    "properties": {
      "filter": {
        "type": "string",
        "pattern": "equals\\(messages\\.channel,\\s*['\"](email|sms|mobile_push)['\"]\\)",
        "description": "Must hold equals(messages.channel,'email'|'sms'|'mobile_push'); further clauses after a comma: id (any); name (contains); status (equals, any: 'Draft', 'Scheduled', 'Sending', 'Sent', 'Cancelled'...); archived (equals); created_at, scheduled_at, updated_at (greater-or-equal, greater-than, less-or-equal, less-than)."
      },
      "sort": {
        "enum": [
          "created_at",
          "-created_at",
          "id",
          "-id",
          "name",
          "-name",
          "scheduled_at",
          "-scheduled_at",
          "updated_at",
          "-updated_at"
        ]
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      },
      "include": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {"enum": ["campaign-messages", "tags"]},
        "description": "Related resources returned in included: the messages (subject, content) and tags."
      }
    }
  },
  examples: [
    { title: "Email campaigns sent since 1 September 2026, latest first", input: {"filter": "equals(messages.channel,'email'),equals(status,'Sent'),greater-or-equal(scheduled_at,2026-09-01T00:00:00Z)", "sort": "-scheduled_at"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/campaigns",
    pathParams: [],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor", "include": "include"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getCampaign = defineFunction({
  name: "klaviyo.get_campaign",
  connector: "klaviyo",
  class: "read",
  description: "Get one campaign by its id: {data: {type: campaign, id, attributes: {name, status, archived, audiences, send_options, tracking_options, send_strategy, created_at, scheduled_at, updated_at, send_time}, relationships: {campaign-messages, tags}}, included}. Read only: this connector neither sends nor edits a campaign. Scope campaigns:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["campaign_id"],
    "properties": {
      "campaign_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo campaign id, from list_campaigns."
      },
      "include": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {"enum": ["campaign-messages", "tags"]},
        "description": "Related resources returned in included: the messages (subject, content) and tags."
      }
    }
  },
  examples: [
    { title: "One campaign with its messages", input: {"campaign_id": "01J0CAMPAIGN0000000000000A", "include": ["campaign-messages"]} },
  ],
  refusals: [
    { code: "campaign_not_found", when: 404, message: "No campaign with this id in this Klaviyo account: read the ids from the list of campaigns." },
  ],
  request: {
    method: "GET",
    path: "/campaigns/{campaign_id}",
    pathParams: ["campaign_id"],
    query: {"include": "include"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listFlows = defineFunction({
  name: "klaviyo.list_flows",
  connector: "klaviyo",
  class: "read",
  description: "List the flows (automations) of the account, at most 50 per page: {data: [{type: flow, id, attributes: {name, status (draft, manual, live), archived, trigger_type, created, updated}}], links: {next}}. For the next page, pass the page[cursor] value of links.next as page_cursor. Scope flows:read; Klaviyo allows 3 calls per second and 60 per minute.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: id (any); name (contains, ends-with, equals, starts-with); status (equals); archived (equals); created, updated (equals, greater-or-equal, greater-than, less-or-equal, less-than); trigger_type (equals: 'Metric', 'Added to List', 'Date Based', 'Price Drop', 'Low Inventory', 'Unconfigured'). E.g. equals(status,'live')."
      },
      "sort": {
        "enum": [
          "created",
          "-created",
          "id",
          "-id",
          "name",
          "-name",
          "status",
          "-status",
          "trigger_type",
          "-trigger_type",
          "updated",
          "-updated"
        ]
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 50, "default": 50},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "Live flows triggered by a list", input: {"filter": "equals(status,'live'),equals(trigger_type,'Added to List')"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/flows",
    pathParams: [],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getFlow = defineFunction({
  name: "klaviyo.get_flow",
  connector: "klaviyo",
  class: "read",
  description: "Get one flow by its id: {data: {type: flow, id, attributes: {name, status, archived, trigger_type, created, updated}}}. additional_fields: [definition] adds its full definition (triggers, actions, branches). Read only: this connector neither creates nor edits a flow. Scope flows:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["flow_id"],
    "properties": {
      "flow_id": {"type": "string", "pattern": "^[A-Za-z0-9]+$", "description": "Klaviyo flow id, from list_flows."},
      "additional_fields": {"type": "array", "minItems": 1, "uniqueItems": true, "items": {"enum": ["definition"]}}
    }
  },
  examples: [
    { title: "One flow with its definition", input: {"flow_id": "Ab12Cd", "additional_fields": ["definition"]} },
  ],
  refusals: [
    { code: "flow_not_found", when: 404, message: "No flow with this id in this Klaviyo account: read the ids from the list of flows." },
  ],
  request: {
    method: "GET",
    path: "/flows/{flow_id}",
    pathParams: ["flow_id"],
    query: {"additional-fields[flow]": "additional_fields"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listMetrics = defineFunction({
  name: "klaviyo.list_metrics",
  connector: "klaviyo",
  class: "read",
  description: "List the metrics (event types) of the account: {data: [{type: metric, id, attributes: {name (Placed Order, Opened Email, Clicked Email...), created, updated, integration: {name, category}}}], links: {next}}. The id goes to get_metric, to the metric_id filter of list_events, to query_metric_aggregates, and to conversion_metric_id of the values reports (usually the Placed Order metric). For the next page, pass the page[cursor] value of links.next as page_cursor. Scope metrics:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: integration.name, integration.category (equals). E.g. equals(integration.name,'Shopify')."
      },
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "Every metric", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/metrics",
    pathParams: [],
    query: {"filter": "filter", "page[cursor]": "page_cursor"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getMetric = defineFunction({
  name: "klaviyo.get_metric",
  connector: "klaviyo",
  class: "read",
  description: "Get one metric by its id: {data: {type: metric, id, attributes: {name, created, updated, integration}}}. Scope metrics:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["metric_id"],
    "properties": {
      "metric_id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9]+$",
        "description": "Klaviyo metric id (6 characters), from list_metrics."
      }
    }
  },
  examples: [
    { title: "One metric", input: {"metric_id": "UxxK4u"} },
  ],
  refusals: [
    { code: "metric_not_found", when: 404, message: "No metric with this id in this Klaviyo account: read the ids from the list of metrics." },
  ],
  request: {
    method: "GET",
    path: "/metrics/{metric_id}",
    pathParams: ["metric_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listEvents = defineFunction({
  name: "klaviyo.list_events",
  connector: "klaviyo",
  class: "read",
  description: "List events (a profile did something at a time): {data: [{type: event, id, attributes: {timestamp, datetime, uuid, event_properties}, relationships: {profile, metric}}], included, links: {next}}. include: [metric, profile] returns the metric name and the profile in included. Filter by metric_id or profile_id and a datetime range rather than paging the whole account. For the next page, pass the page[cursor] value of links.next as page_cursor. Scope events:read.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "filter": {
        "type": "string",
        "minLength": 1,
        "description": "Fields: metric_id, profile_id (equals); datetime (ISO 8601) and timestamp (Unix seconds) (greater-or-equal, greater-than, less-or-equal, less-than); profile, metric (has). E.g. equals(metric_id,\"UxxK4u\"),greater-or-equal(datetime,2026-09-01T00:00:00Z)."
      },
      "sort": {"enum": ["datetime", "-datetime", "timestamp", "-timestamp"]},
      "page_size": {"type": "integer", "minimum": 1, "maximum": 1000, "default": 200},
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page[cursor] value read in links.next of the previous page."
      },
      "include": {"type": "array", "minItems": 1, "uniqueItems": true, "items": {"enum": ["metric", "profile"]}}
    }
  },
  examples: [
    { title: "Orders placed by one profile, latest first", input: {"filter": "equals(profile_id,\"01HZX8A6R0J3VQ2N9P4K7T5M1B\"),equals(metric_id,\"UxxK4u\")", "sort": "-datetime", "include": ["metric"]} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/events",
    pathParams: [],
    query: {"filter": "filter", "sort": "sort", "page[size]": "page_size", "page[cursor]": "page_cursor", "include": "include"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const createEvent = defineFunction({
  name: "klaviyo.create_event",
  connector: "klaviyo",
  class: "sensitive",
  description: "Record an event for a profile: the metric by name (created when new) and the profile by id, email, phone_number or external_id (created or updated with the attributes given). Answers 202 without a body: the event is queued, not yet visible. A unique_id makes a retry idempotent. Flows triggered by this metric start for the profile and may send messages, unless backfill is true. Scope events:write.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "properties": {
          "type": {"const": "event"},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "required": ["properties", "metric", "profile"],
            "properties": {
              "properties": {"type": "object", "description": "Event properties (at most 400), e.g. {order_id, items}."},
              "time": {
                "type": "string",
                "format": "date-time",
                "description": "When it happened (ISO 8601); now by default."
              },
              "value": {"type": "number", "description": "Monetary value, e.g. the order amount."},
              "value_currency": {"type": "string", "pattern": "^[A-Z]{3}$", "description": "ISO 4217 code of value."},
              "unique_id": {
                "type": "string",
                "minLength": 1,
                "description": "Deduplicates events of the same profile and metric."
              },
              "backfill": {"type": "boolean", "description": "True records a past event without starting flows."},
              "metric": {
                "type": "object",
                "additionalProperties": false,
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["type", "attributes"],
                    "properties": {
                      "type": {"const": "metric"},
                      "attributes": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["name"],
                        "properties": {
                          "name": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 127,
                            "description": "Metric name, e.g. Placed Order."
                          }
                        }
                      }
                    }
                  }
                }
              },
              "profile": {
                "type": "object",
                "additionalProperties": false,
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["type"],
                    "anyOf": [
                      {"required": ["id"]},
                      {
                        "required": ["attributes"],
                        "properties": {
                          "attributes": {
                            "anyOf": [
                              {"required": ["email"]},
                              {"required": ["phone_number"]},
                              {"required": ["external_id"]}
                            ]
                          }
                        }
                      }
                    ],
                    "properties": {
                      "type": {"const": "profile"},
                      "id": {"type": "string", "pattern": "^[A-Za-z0-9]+$"},
                      "attributes": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "email": {"type": ["string", "null"]},
                          "phone_number": {"type": ["string", "null"], "description": "E.164, e.g. +33612345678."},
                          "external_id": {"type": ["string", "null"], "description": "Id of the person in another system."},
                          "first_name": {"type": ["string", "null"]},
                          "last_name": {"type": ["string", "null"]},
                          "organization": {"type": ["string", "null"]},
                          "title": {"type": ["string", "null"]},
                          "locale": {"type": ["string", "null"], "description": "IETF BCP 47, e.g. fr-FR."},
                          "image": {"type": ["string", "null"], "description": "URL of a picture."},
                          "location": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "address1": {"type": ["string", "null"]},
                              "address2": {"type": ["string", "null"]},
                              "city": {"type": ["string", "null"]},
                              "region": {"type": ["string", "null"]},
                              "zip": {"type": ["string", "null"]},
                              "country": {"type": ["string", "null"]},
                              "timezone": {
                                "type": ["string", "null"],
                                "description": "IANA time zone, e.g. Europe/Paris."
                              },
                              "ip": {"type": ["string", "null"]},
                              "latitude": {"type": ["string", "number", "null"]},
                              "longitude": {"type": ["string", "number", "null"]}
                            }
                          },
                          "properties": {
                            "type": ["object", "null"],
                            "description": "Custom properties, merged into the existing ones."
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  examples: [
    { title: "A past order, recorded without starting flows", input: {"data": {"type": "event", "attributes": {"properties": {"order_id": "A-1001", "items": ["Mug"]}, "time": "2026-09-15T10:00:00Z", "value": 24.9, "value_currency": "EUR", "unique_id": "A-1001", "backfill": true, "metric": {"data": {"type": "metric", "attributes": {"name": "Placed Order"}}}, "profile": {"data": {"type": "profile", "attributes": {"email": "jane@example.com"}}}}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/events",
    pathParams: [],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Record this event in Klaviyo: flows triggered by its metric may start for the profile and send messages, unless backfill is true." },
})

export const queryMetricAggregates = defineFunction({
  name: "klaviyo.query_metric_aggregates",
  connector: "klaviyo",
  class: "read",
  description: "Aggregate the events of one metric over a time range (a POST that only reads): {data: {type: metric-aggregate, id, attributes: {dates: [...], data: [{dimensions: [...], measurements: {count: [...], unique: [...], sum_value: [...]}}]}}}, one value per date bucket and per grouping of by. filter must bound datetime with greater-or-equal and less-than. For the figures shown in Klaviyo's campaign and flow reports, prefer query_campaign_values and query_flow_values. Scope metrics:read; 3 calls per second and 60 per minute.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "properties": {
          "type": {"const": "metric-aggregate"},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "required": ["metric_id", "measurements", "filter"],
            "properties": {
              "metric_id": {
                "type": "string",
                "pattern": "^[A-Za-z0-9]+$",
                "description": "Klaviyo metric id (6 characters), from list_metrics."
              },
              "measurements": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {"enum": ["count", "sum_value", "unique"]}
              },
              "interval": {"enum": ["hour", "day", "week", "month"], "default": "day"},
              "filter": {
                "type": "array",
                "minItems": 2,
                "items": {"type": "string", "minLength": 1},
                "description": "One clause per item, the datetime range required: [\"greater-or-equal(datetime,2026-09-01T00:00:00)\", \"less-than(datetime,2026-10-01T00:00:00)\"], plus e.g. 'equals($attributed_flow,\"Ab12Cd\")'."
              },
              "by": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                  "enum": [
                    "$attributed_channel",
                    "$attributed_flow",
                    "$attributed_message",
                    "$attributed_variation",
                    "$campaign_channel",
                    "$flow",
                    "$flow_channel",
                    "$message",
                    "$message_send_cohort",
                    "$usage_amount",
                    "$value_currency",
                    "$variation",
                    "$variation_send_cohort",
                    "Bot Click",
                    "Bounce Type",
                    "Campaign Name",
                    "Client Canonical",
                    "Client Name",
                    "Client Type",
                    "Email Domain",
                    "Failure Source",
                    "Failure Type",
                    "From Number",
                    "From Phone Region",
                    "Inbox Provider",
                    "List",
                    "Message Format",
                    "Message Name",
                    "Message Type",
                    "Method",
                    "Segment Count",
                    "Subject",
                    "To Number",
                    "To Phone Region",
                    "URL",
                    "form_id"
                  ]
                },
                "description": "Dimensions to group by, e.g. $attributed_flow or $message."
              },
              "timezone": {
                "type": "string",
                "minLength": 1,
                "default": "UTC",
                "description": "IANA time zone of the buckets, e.g. Europe/Paris (case-sensitive)."
              },
              "page_size": {"type": "integer", "minimum": 1, "default": 500},
              "page_cursor": {
                "type": "string",
                "minLength": 1,
                "description": "Cursor of the next page, read in links.next of the previous one."
              },
              "sort": {
                "type": "string",
                "minLength": 1,
                "description": "A by dimension, - for descending, e.g. -$message."
              },
              "return_fields": {"type": "array", "minItems": 1, "items": {"type": "string"}}
            }
          }
        }
      }
    }
  },
  examples: [
    { title: "Orders per day in September 2026, with revenue", input: {"data": {"type": "metric-aggregate", "attributes": {"metric_id": "UxxK4u", "measurements": ["count", "sum_value"], "interval": "day", "timezone": "Europe/Paris", "filter": ["greater-or-equal(datetime,2026-09-01T00:00:00)", "less-than(datetime,2026-10-01T00:00:00)"]}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/metric-aggregates",
    pathParams: [],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
})

export const queryCampaignValues = defineFunction({
  name: "klaviyo.query_campaign_values",
  connector: "klaviyo",
  class: "read",
  description: "Campaign performance as shown in Klaviyo's reports (a POST that only reads): {data: {type: campaign-values-report, attributes: {results: [{groupings: {campaign_id, campaign_message_id, send_channel}, statistics: {opens, open_rate, clicks, click_rate, conversions, conversion_value, recipients, unsubscribes, ...}}]}}, links: {next}}. Rates are fractions between 0 and 1. conversion_metric_id is required even without conversion statistics: the id of the Placed Order metric, from list_metrics. The time frame spans at most one year. For the next page, pass the page_cursor value of links.next as page_cursor. Scope campaigns:read; Klaviyo allows 1 call per second, 2 per minute and 225 per day: ask for every statistic needed in one call.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "properties": {
          "type": {"const": "campaign-values-report"},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "required": ["statistics", "timeframe", "conversion_metric_id"],
            "properties": {
              "statistics": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                  "enum": [
                    "average_order_value",
                    "bounce_rate",
                    "bounced",
                    "bounced_or_failed",
                    "bounced_or_failed_rate",
                    "click_rate",
                    "click_to_open_rate",
                    "clicks",
                    "clicks_unique",
                    "conversion_rate",
                    "conversion_uniques",
                    "conversion_value",
                    "conversions",
                    "delivered",
                    "delivery_rate",
                    "failed",
                    "failed_rate",
                    "message_segment_count_sum",
                    "open_rate",
                    "opens",
                    "opens_unique",
                    "recipients",
                    "revenue_per_recipient",
                    "spam_complaint_rate",
                    "spam_complaints",
                    "text_message_credit_usage_amount",
                    "text_message_roi",
                    "text_message_spend",
                    "unsubscribe_rate",
                    "unsubscribe_uniques",
                    "unsubscribes"
                  ]
                }
              },
              "timeframe": {
                "oneOf": [
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["key"],
                    "properties": {
                      "key": {
                        "enum": [
                          "today",
                          "yesterday",
                          "this_week",
                          "last_week",
                          "this_month",
                          "last_month",
                          "this_year",
                          "last_year",
                          "last_7_days",
                          "last_30_days",
                          "last_90_days",
                          "last_3_months",
                          "last_12_months",
                          "last_365_days"
                        ]
                      }
                    }
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["start", "end"],
                    "properties": {
                      "start": {"type": "string", "format": "date-time"},
                      "end": {"type": "string", "format": "date-time"}
                    }
                  }
                ],
                "description": "A named key, or {start, end} (the offset is ignored: the account time zone applies)."
              },
              "conversion_metric_id": {
                "type": "string",
                "pattern": "^[A-Za-z0-9]+$",
                "description": "Klaviyo metric id (6 characters), from list_metrics."
              },
              "group_by": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                  "enum": [
                    "campaign_id",
                    "campaign_message_id",
                    "campaign_message_name",
                    "group",
                    "group_name",
                    "send_channel",
                    "tag_id",
                    "tag_name",
                    "text_message_format",
                    "variation",
                    "variation_name"
                  ]
                },
                "description": "Must keep campaign_id and campaign_message_id; campaign_id, campaign_message_id, send_channel by default."
              },
              "filter": {
                "type": "string",
                "minLength": 1,
                "description": "E.g. equals(send_channel,\"email\"), or contains-any(campaign_id,[\"01J...\",\"01K...\"]); clauses ANDed by a comma, one per attribute."
              }
            }
          }
        }
      },
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page_cursor value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "Email campaign performance over the last 30 days", input: {"data": {"type": "campaign-values-report", "attributes": {"statistics": ["recipients", "open_rate", "click_rate", "conversions", "conversion_value", "unsubscribes"], "timeframe": {"key": "last_30_days"}, "conversion_metric_id": "UxxK4u", "filter": "equals(send_channel,\"email\")"}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/campaign-values-reports",
    pathParams: [],
    query: {"page_cursor": "page_cursor"},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
})

export const queryFlowValues = defineFunction({
  name: "klaviyo.query_flow_values",
  connector: "klaviyo",
  class: "read",
  description: "Flow performance as shown in Klaviyo's reports (a POST that only reads): {data: {type: flow-values-report, attributes: {results: [{groupings: {flow_id, flow_message_id, send_channel}, statistics: {...}}]}}, links: {next}}. Same statistics, time frame and conversion_metric_id as query_campaign_values. For the next page, pass the page_cursor value of links.next as page_cursor. Scope flows:read; Klaviyo allows 1 call per second, 2 per minute and 225 per day.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "properties": {
          "type": {"const": "flow-values-report"},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "required": ["statistics", "timeframe", "conversion_metric_id"],
            "properties": {
              "statistics": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                  "enum": [
                    "average_order_value",
                    "bounce_rate",
                    "bounced",
                    "bounced_or_failed",
                    "bounced_or_failed_rate",
                    "click_rate",
                    "click_to_open_rate",
                    "clicks",
                    "clicks_unique",
                    "conversion_rate",
                    "conversion_uniques",
                    "conversion_value",
                    "conversions",
                    "delivered",
                    "delivery_rate",
                    "failed",
                    "failed_rate",
                    "message_segment_count_sum",
                    "open_rate",
                    "opens",
                    "opens_unique",
                    "recipients",
                    "revenue_per_recipient",
                    "spam_complaint_rate",
                    "spam_complaints",
                    "text_message_credit_usage_amount",
                    "text_message_roi",
                    "text_message_spend",
                    "unsubscribe_rate",
                    "unsubscribe_uniques",
                    "unsubscribes"
                  ]
                }
              },
              "timeframe": {
                "oneOf": [
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["key"],
                    "properties": {
                      "key": {
                        "enum": [
                          "today",
                          "yesterday",
                          "this_week",
                          "last_week",
                          "this_month",
                          "last_month",
                          "this_year",
                          "last_year",
                          "last_7_days",
                          "last_30_days",
                          "last_90_days",
                          "last_3_months",
                          "last_12_months",
                          "last_365_days"
                        ]
                      }
                    }
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["start", "end"],
                    "properties": {
                      "start": {"type": "string", "format": "date-time"},
                      "end": {"type": "string", "format": "date-time"}
                    }
                  }
                ],
                "description": "A named key, or {start, end} (the offset is ignored: the account time zone applies)."
              },
              "conversion_metric_id": {
                "type": "string",
                "pattern": "^[A-Za-z0-9]+$",
                "description": "Klaviyo metric id (6 characters), from list_metrics."
              },
              "group_by": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                  "enum": [
                    "flow_id",
                    "flow_message_id",
                    "flow_message_name",
                    "flow_name",
                    "send_channel",
                    "tag_id",
                    "tag_name",
                    "text_message_format",
                    "variation",
                    "variation_name"
                  ]
                },
                "description": "Must keep flow_id and flow_message_id; flow_id, flow_message_id, send_channel by default."
              },
              "filter": {
                "type": "string",
                "minLength": 1,
                "description": "E.g. equals(flow_id,\"Ab12Cd\"); clauses ANDed by a comma, one per attribute."
              }
            }
          }
        }
      },
      "page_cursor": {
        "type": "string",
        "minLength": 1,
        "description": "The page_cursor value read in links.next of the previous page."
      }
    }
  },
  examples: [
    { title: "One flow's performance this year", input: {"data": {"type": "flow-values-report", "attributes": {"statistics": ["recipients", "open_rate", "click_rate", "conversion_value"], "timeframe": {"key": "this_year"}, "conversion_metric_id": "UxxK4u", "filter": "equals(flow_id,\"Ab12Cd\")"}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/flow-values-reports",
    pathParams: [],
    query: {"page_cursor": "page_cursor"},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
})

export const subscribeProfiles = defineFunction({
  name: "klaviyo.subscribe_profiles",
  connector: "klaviyo",
  class: "sensitive",
  description: "Give email or SMS marketing consent to up to 1000 profiles, matched by email or phone_number (created when unknown), and add them to the list given in relationships. Answers 202: the job runs asynchronously. If the list uses double opt-in, Klaviyo sends each profile a confirmation message and subscribes it only once confirmed. Clears unsubscribe, spam report and manual suppressions. historical_import: true records consent gathered earlier (consented_at required on each channel), without confirmation message and without starting the list's flows. Only for people who did consent. Scopes subscriptions:write, profiles:write, lists:write.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "properties": {
          "type": {"const": "profile-subscription-bulk-create-job"},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "required": ["profiles"],
            "properties": {
              "custom_source": {
                "type": "string",
                "minLength": 1,
                "description": "Where the consent was gathered, stored on the consent record."
              },
              "historical_import": {"type": "boolean", "default": false},
              "profiles": {
                "type": "object",
                "additionalProperties": false,
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 1000,
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": ["type", "attributes"],
                      "properties": {
                        "type": {"const": "profile"},
                        "id": {"type": "string", "pattern": "^[A-Za-z0-9]+$"},
                        "attributes": {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["subscriptions"],
                          "anyOf": [{"required": ["email"]}, {"required": ["phone_number"]}],
                          "properties": {
                            "email": {"type": "string", "minLength": 3},
                            "phone_number": {"type": "string", "pattern": "^\\+[1-9][0-9]{6,14}$", "description": "E.164."},
                            "subscriptions": {
                              "type": "object",
                              "additionalProperties": false,
                              "minProperties": 1,
                              "properties": {
                                "email": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "required": ["marketing"],
                                  "properties": {
                                    "marketing": {
                                      "type": "object",
                                      "additionalProperties": false,
                                      "required": ["consent"],
                                      "properties": {
                                        "consent": {"const": "SUBSCRIBED"},
                                        "consented_at": {
                                          "type": "string",
                                          "format": "date-time",
                                          "description": "Only with historical_import: when consent was given, in the past."
                                        }
                                      }
                                    }
                                  }
                                },
                                "sms": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "required": ["marketing"],
                                  "properties": {
                                    "marketing": {
                                      "type": "object",
                                      "additionalProperties": false,
                                      "required": ["consent"],
                                      "properties": {
                                        "consent": {"const": "SUBSCRIBED"},
                                        "consented_at": {
                                          "type": "string",
                                          "format": "date-time",
                                          "description": "Only with historical_import: when consent was given, in the past."
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "relationships": {
            "type": "object",
            "additionalProperties": false,
            "required": ["list"],
            "properties": {
              "list": {
                "type": "object",
                "additionalProperties": false,
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["type", "id"],
                    "properties": {
                      "type": {"const": "list"},
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z0-9]+$",
                        "description": "Klaviyo list id (6 characters, e.g. Y6nRLr), from list_lists."
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  examples: [
    { title: "Subscribe one email address to a list", input: {"data": {"type": "profile-subscription-bulk-create-job", "attributes": {"custom_source": "Website signup form", "profiles": {"data": [{"type": "profile", "attributes": {"email": "jane@example.com", "subscriptions": {"email": {"marketing": {"consent": "SUBSCRIBED"}}}}}]}}, "relationships": {"list": {"data": {"type": "list", "id": "Y6nRLr"}}}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/profile-subscription-bulk-create-jobs",
    pathParams: [],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Give Klaviyo marketing consent to these profiles: it changes their consent, and a double opt-in list sends them a confirmation message." },
})

export const unsubscribeProfiles = defineFunction({
  name: "klaviyo.unsubscribe_profiles",
  connector: "klaviyo",
  class: "sensitive",
  description: "Withdraw email or SMS marketing consent from up to 100 profiles, matched by email or phone_number. Answers 202: the job runs asynchronously. With a list in relationships, profiles in that list are removed from it and unsubscribed; a profile NOT in that list, or any profile when no list is given, is unsubscribed globally, from all marketing. Check membership with list_profiles_in_list first. To only leave a list, use remove_profiles_from_list. Scopes subscriptions:write, profiles:write, lists:write.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data"],
    "properties": {
      "data": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "attributes"],
        "properties": {
          "type": {"const": "profile-subscription-bulk-delete-job"},
          "attributes": {
            "type": "object",
            "additionalProperties": false,
            "required": ["profiles"],
            "properties": {
              "profiles": {
                "type": "object",
                "additionalProperties": false,
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 100,
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": ["type", "attributes"],
                      "properties": {
                        "type": {"const": "profile"},
                        "attributes": {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["subscriptions"],
                          "anyOf": [{"required": ["email"]}, {"required": ["phone_number"]}],
                          "properties": {
                            "email": {"type": "string", "minLength": 3},
                            "phone_number": {"type": "string", "pattern": "^\\+[1-9][0-9]{6,14}$", "description": "E.164."},
                            "subscriptions": {
                              "type": "object",
                              "additionalProperties": false,
                              "minProperties": 1,
                              "properties": {
                                "email": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "required": ["marketing"],
                                  "properties": {
                                    "marketing": {
                                      "type": "object",
                                      "additionalProperties": false,
                                      "required": ["consent"],
                                      "properties": {"consent": {"const": "UNSUBSCRIBED"}}
                                    }
                                  }
                                },
                                "sms": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "required": ["marketing"],
                                  "properties": {
                                    "marketing": {
                                      "type": "object",
                                      "additionalProperties": false,
                                      "required": ["consent"],
                                      "properties": {"consent": {"const": "UNSUBSCRIBED"}}
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "relationships": {
            "type": "object",
            "additionalProperties": false,
            "required": ["list"],
            "properties": {
              "list": {
                "type": "object",
                "additionalProperties": false,
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["type", "id"],
                    "properties": {
                      "type": {"const": "list"},
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z0-9]+$",
                        "description": "Klaviyo list id (6 characters, e.g. Y6nRLr), from list_lists."
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  examples: [
    { title: "Unsubscribe one email address from a list's marketing", input: {"data": {"type": "profile-subscription-bulk-delete-job", "attributes": {"profiles": {"data": [{"type": "profile", "attributes": {"email": "jane@example.com", "subscriptions": {"email": {"marketing": {"consent": "UNSUBSCRIBED"}}}}}]}}, "relationships": {"list": {"data": {"type": "list", "id": "Y6nRLr"}}}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/profile-subscription-bulk-delete-jobs",
    pathParams: [],
    query: {},
    body: {"data": "data"},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Withdraw Klaviyo marketing consent from these profiles: those outside the given list, or all without a list, are unsubscribed globally." },
})

export const connector = defineConnector({
  name: "klaviyo",
  label: "Klaviyo",
  namespace: "klaviyo",
  version: "1.0.0",
  apiVersion: "2026-07-15",
  baseUrl: "https://a.klaviyo.com/api",
  auth: {"kind": "api_key", "in": "header", "name": "Authorization", "prefix": "Klaviyo-API-Key ", "key": "api_key"},
  credential: [{"name": "api_key", "label": "Private API key", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 30000,
  queryArrays: "comma",
  headers: {"revision": "2026-07-15", "Accept": "application/vnd.api+json", "Content-Type": "application/vnd.api+json"},
  rateLimit: { requests: 1, intervalMs: 1000 },
  errors: [
    { status: 400, code: "invalid_request", message: "Klaviyo rejected the request as invalid (filter syntax, unknown field or malformed body): errors[].detail and errors[].source name the faulty part.", retryable: false },
    { status: 401, code: "key_invalid", message: "Klaviyo did not accept the private API key: missing, revoked or mistyped. Retrying unchanged fails the same way.", retryable: false },
    { status: 403, code: "scope_missing", message: "The private API key lacks the scope this action needs. Scopes cannot be added to an existing key: a new key with that scope is needed.", retryable: false },
    { status: 404, code: "not_found", message: "No such object in this Klaviyo account: check the id.", retryable: false },
    { status: 409, code: "conflict", message: "Klaviyo refused the change because it conflicts with existing data, such as an identifier already held by another profile.", retryable: false },
    { status: 429, code: "rate_limited", message: "Klaviyo rate limit reached for this endpoint (limits are per account and per endpoint; the values reports allow 2 per minute and 225 per day): wait the Retry-After seconds before retrying.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Klaviyo is temporarily unavailable: retry later.", retryable: true },
  ],
  probe: { function: "klaviyo.get_account", nonEmpty: ["data"] },
  exposure: {"mode": "per_connector", "tool": "klaviyo"},
  functions: [
    getAccount,
    listProfiles,
    getProfile,
    createOrUpdateProfile,
    listLists,
    getList,
    listProfilesInList,
    addProfilesToList,
    removeProfilesFromList,
    listSegments,
    getSegment,
    listProfilesInSegment,
    listCampaigns,
    getCampaign,
    listFlows,
    getFlow,
    listMetrics,
    getMetric,
    listEvents,
    createEvent,
    queryMetricAggregates,
    queryCampaignValues,
    queryFlowValues,
    subscribeProfiles,
    unsubscribeProfiles,
  ],
})
