// Generated by the fabrique from connectors/mailpool/connector.yaml. Do not edit: run `python -m fabrique`.
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const listDomains = defineFunction({
  name: "mailpool.list_domains",
  connector: "mailpool",
  class: "read",
  description: "List the workspace's domains with their type (google, outlook, shared, private), status, expiry, owner and redirect URL. Mailpool requires limit and offset on every list.",
  schema: z.strictObject({
    "limit": z.int().gte(1).lte(100).describe("Page size."),
    "offset": z.int().gte(0).describe("Number of items to skip."),
  }),
  examples: [
    { title: "First page of domains", input: {"limit": 50, "offset": 0} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/domains/",
    pathParams: [],
    query: {"limit": "limit", "offset": "offset"},
    body: {},
    headers: {},
  },
  output: { items: "data", schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const getDomain = defineFunction({
  name: "mailpool.get_domain",
  connector: "mailpool",
  class: "read",
  description: "Get one domain by its id: type, status, expiry, owner, redirect URL.",
  schema: z.strictObject({
    "domain_id": z.int().gte(1).describe("Mailpool domain id."),
  }),
  examples: [
    { title: "One domain", input: {"domain_id": 1201} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/domains/{domain_id}",
    pathParams: ["domain_id"],
    query: {},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const getDomainDns = defineFunction({
  name: "mailpool.get_domain_dns",
  connector: "mailpool",
  class: "read",
  description: "Get the DNS records Mailpool holds for a domain, as {type, key, value, priority}; key is the host label, null for the apex. This is the stored configuration, not a live lookup. The _dmarc record is published from the domain's DMARC settings (set_dmarc_email, set_dmarc_policy).",
  schema: z.strictObject({
    "domain_id": z.int().gte(1).describe("Mailpool domain id."),
  }),
  examples: [
    { title: "DNS records of one domain", input: {"domain_id": 1201} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/domains/{domain_id}/dns",
    pathParams: ["domain_id"],
    query: {},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"type": {"enum": ["A", "AAAA", "CNAME", "MX", "TXT", "SRV"]}, "key": {"type": ["string", "null"], "description": "Host label, null for the apex."}, "value": {"type": "string"}, "priority": {"type": "integer"}, "port": {"type": "integer"}, "weight": {"type": "integer"}}} },
  cost: { per: "request" },
})

export const setDmarcEmail = defineFunction({
  name: "mailpool.set_dmarc_email",
  connector: "mailpool",
  class: "write",
  description: "Set the address that receives a domain's DMARC reports. It is written as both rua and ruf, and the stored _dmarc record is published with it.",
  schema: z.strictObject({
    "domain_id": z.int().gte(1).describe("Mailpool domain id."),
    "email": z.string().meta({"description": "Report address.", "format": "email"}),
  }),
  examples: [
    { title: "Send DMARC reports to one address", input: {"domain_id": 1201, "email": "dmarc@example.com"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/domains/{domain_id}/dmarc-email",
    pathParams: ["domain_id"],
    query: {},
    body: {"email": "email"},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const setDmarcPolicy = defineFunction({
  name: "mailpool.set_dmarc_policy",
  connector: "mailpool",
  class: "write",
  description: "Set a domain's DMARC policy: none, quarantine or reject.",
  schema: z.strictObject({
    "domain_id": z.int().gte(1).describe("Mailpool domain id."),
    "policy": z.enum(["none", "quarantine", "reject"]),
  }),
  examples: [
    { title: "Quarantine failing mail", input: {"domain_id": 1201, "policy": "quarantine"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/domains/{domain_id}/dmarc-policy",
    pathParams: ["domain_id"],
    query: {},
    body: {"policy": "policy"},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const setRedirectUrl = defineFunction({
  name: "mailpool.set_redirect_url",
  connector: "mailpool",
  class: "write",
  description: "Set where a web visit to the domain is redirected.",
  schema: z.strictObject({
    "domain_id": z.int().gte(1).describe("Mailpool domain id."),
    "url": z.string().min(1).describe("Target URL or host."),
  }),
  examples: [
    { title: "Redirect to the main site", input: {"domain_id": 1201, "url": "example.com"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/domains/{domain_id}/redirect-url",
    pathParams: ["domain_id"],
    query: {},
    body: {"url": "url"},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const getDomainInfo = defineFunction({
  name: "mailpool.get_domain_info",
  connector: "mailpool",
  class: "read",
  description: "Tell whether a domain can be registered through Mailpool, and its price. Nothing is bought.",
  schema: z.strictObject({
    "domain": z.string().min(3).describe("Domain name, such as example.com."),
  }),
  examples: [
    { title: "Availability of one name", input: {"domain": "example-outreach.com"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/domains/info",
    pathParams: [],
    query: {"domain": "domain"},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"available": {"type": "boolean"}, "price": {"type": "number"}}} },
  cost: { per: "request" },
})

export const getDomainSuggestions = defineFunction({
  name: "mailpool.get_domain_suggestions",
  connector: "mailpool",
  class: "read",
  description: "Suggest available domain names close to a name, with their price. Nothing is bought.",
  schema: z.strictObject({
    "domain": z.string().min(1).describe("Name to start from."),
    "limit": z.int().gte(1).lte(100).describe("Page size."),
    "offset": z.int().gte(0).describe("Number of items to skip."),
  }),
  examples: [
    { title: "Five variants of a brand", input: {"domain": "example", "limit": 5, "offset": 0} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/domains/suggestions",
    pathParams: [],
    query: {"domain": "domain", "limit": "limit", "offset": "offset"},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"domain": {"type": "string"}, "available": {"type": "boolean"}, "price": {"type": "number"}}} },
  cost: { per: "request" },
})

export const checkGoogleWorkspaceAvailability = defineFunction({
  name: "mailpool.check_google_workspace_availability",
  connector: "mailpool",
  class: "read",
  description: "Tell whether a domain is already used by a Google Workspace account. Must be enabled for the workspace, otherwise 403.",
  schema: z.strictObject({
    "domain": z.string().min(3).describe("Domain name, such as example.com."),
  }),
  examples: [
    { title: "Google Workspace check", input: {"domain": "example-outreach.com"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/domains/google-workspace-availability",
    pathParams: [],
    query: {},
    body: {"domain": "domain"},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"isAvailable": {"type": "boolean"}}} },
  cost: { per: "request" },
})

export const checkMicrosoft365Availability = defineFunction({
  name: "mailpool.check_microsoft_365_availability",
  connector: "mailpool",
  class: "read",
  description: "Tell whether a domain is already used by a Microsoft 365 tenant. Must be enabled for the workspace, otherwise 403.",
  schema: z.strictObject({
    "domain": z.string().min(3).describe("Domain name, such as example.com."),
  }),
  examples: [
    { title: "Microsoft 365 check", input: {"domain": "example-outreach.com"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/domains/microsoft-365-availability",
    pathParams: [],
    query: {},
    body: {"domain": "domain"},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"isAvailable": {"type": "boolean"}}} },
  cost: { per: "request" },
})

export const listDomainOwners = defineFunction({
  name: "mailpool.list_domain_owners",
  connector: "mailpool",
  class: "read",
  description: "List the saved registrant contacts used when registering domains.",
  schema: z.strictObject({}),
  examples: [
    { title: "Saved owners", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/domains/owners",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": ["integer", "string"]}, "company": {"type": "string"}, "firstName": {"type": "string"}, "lastName": {"type": "string"}, "email": {"type": "string"}, "streetAddress1": {"type": "string"}, "streetAddress2": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "postalCode": {"type": "string"}, "country": {"type": "string"}, "phone": {"type": ["string", "null"]}, "gtldVerified": {"type": ["boolean", "null"]}}} },
  cost: { per: "request" },
})

export const listMailboxes = defineFunction({
  name: "mailpool.list_mailboxes",
  connector: "mailpool",
  class: "read",
  description: "List the workspace's mailboxes: address, name, type (google, outlook, shared, private), status, domain and IMAP/SMTP hosts. Credentials are never returned.",
  schema: z.strictObject({
    "limit": z.int().gte(1).lte(100).describe("Page size."),
    "offset": z.int().gte(0).describe("Number of items to skip."),
    "domain_id": z.int().gte(1).describe("Mailpool domain id.").optional(),
  }),
  examples: [
    { title: "Mailboxes of one domain", input: {"limit": 50, "offset": 0, "domain_id": 1201} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/mailboxes",
    pathParams: [],
    query: {"limit": "limit", "offset": "offset", "domainId": "domain_id"},
    body: {},
    headers: {},
  },
  output: { items: "data", strip: ["password", "imapPassword", "smtpPassword", "secret", "authCode", "admin"], schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "email": {"type": "string"}, "firstName": {"type": "string"}, "lastName": {"type": "string"}, "signature": {"type": "string"}, "forwardTo": {"type": "string"}, "status": {"enum": ["active", "pending", "inactive"]}, "avatar": {"type": "string"}, "type": {"enum": ["google", "shared", "private", "outlook"]}, "isAdmin": {"type": "boolean"}, "domain": {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}}, "imapHost": {"type": "string"}, "imapPort": {"type": "integer"}, "imapTLS": {"type": "boolean"}, "imapUsername": {"type": "string"}, "smtpHost": {"type": "string"}, "smtpPort": {"type": "integer"}, "smtpTLS": {"type": "boolean"}, "smtpUsername": {"type": "string"}, "scheduledDeletionAt": {"type": ["string", "null"]}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const getMailbox = defineFunction({
  name: "mailpool.get_mailbox",
  connector: "mailpool",
  class: "read",
  description: "Get one mailbox by its id. Credentials are never returned.",
  schema: z.strictObject({
    "mailbox_id": z.int().gte(1).describe("Mailpool mailbox id."),
  }),
  examples: [
    { title: "One mailbox", input: {"mailbox_id": 5301} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/mailboxes/{mailbox_id}",
    pathParams: ["mailbox_id"],
    query: {},
    body: {},
    headers: {},
  },
  output: { strip: ["password", "imapPassword", "smtpPassword", "secret", "authCode", "admin"], schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "email": {"type": "string"}, "firstName": {"type": "string"}, "lastName": {"type": "string"}, "signature": {"type": "string"}, "forwardTo": {"type": "string"}, "status": {"enum": ["active", "pending", "inactive"]}, "avatar": {"type": "string"}, "type": {"enum": ["google", "shared", "private", "outlook"]}, "isAdmin": {"type": "boolean"}, "domain": {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "expireAt": {"type": "string", "format": "date-time"}, "domain": {"type": "string"}, "domainOwner": {"type": "object", "description": "Registrant contact."}, "redirectUrl": {"type": ["string", "null"]}, "type": {"enum": ["google", "shared", "private", "outlook", "unassigned"]}, "status": {"enum": ["active", "pending", "inactive"]}, "nameservers": {"type": ["array", "null"], "items": {"type": "string"}}, "error": {"type": ["object", "null"]}}}, "imapHost": {"type": "string"}, "imapPort": {"type": "integer"}, "imapTLS": {"type": "boolean"}, "imapUsername": {"type": "string"}, "smtpHost": {"type": "string"}, "smtpPort": {"type": "integer"}, "smtpTLS": {"type": "boolean"}, "smtpUsername": {"type": "string"}, "scheduledDeletionAt": {"type": ["string", "null"]}, "error": {"type": ["object", "null"]}}} },
  cost: { per: "request" },
})

export const listSpamChecks = defineFunction({
  name: "mailpool.list_spam_checks",
  connector: "mailpool",
  class: "read",
  description: "List past spam checks with their state and results (SPF, DKIM, DMARC, blacklists, SpamAssassin, score).",
  schema: z.strictObject({
    "limit": z.int().gte(1).lte(100).describe("Page size."),
    "offset": z.int().gte(0).describe("Number of items to skip."),
  }),
  examples: [
    { title: "Recent spam checks", input: {"limit": 20, "offset": 0} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/spam-checks/",
    pathParams: [],
    query: {"limit": "limit", "offset": "offset"},
    body: {},
    headers: {},
  },
  output: { items: "data", strip: ["mailbox"], schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "email": {"type": "string", "description": "Mailpool's test address the email was sent to."}, "fromEmail": {"type": "string"}, "state": {"enum": ["pending", "completed"]}, "result": {"type": ["object", "null"], "description": "score, and SPF, DKIM, DMARK, domainAge, reverseDNS, ipBlackList, domainBlackList, spamAssassin, shortUrls, brokenLinks, each with a status."}}} },
  cost: { per: "request" },
})

export const createSpamCheck = defineFunction({
  name: "mailpool.create_spam_check",
  connector: "mailpool",
  class: "write",
  description: "Run a spam check: Mailpool sends a test email from the mailbox and scores it. Free; the state goes from pending to completed within seconds. Read it with get_spam_check. Refused with 404 for mailbox types it does not support.",
  schema: z.strictObject({
    "mailbox_id": z.int().gte(1).describe("Mailpool mailbox id."),
  }),
  examples: [
    { title: "Check one mailbox", input: {"mailbox_id": 5301} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/spam-checks/",
    pathParams: [],
    query: {},
    body: {"mailboxId": "mailbox_id"},
    headers: {},
  },
  output: { strip: ["mailbox"], schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "email": {"type": "string", "description": "Mailpool's test address the email was sent to."}, "fromEmail": {"type": "string"}, "state": {"enum": ["pending", "completed"]}, "result": {"type": ["object", "null"], "description": "score, and SPF, DKIM, DMARK, domainAge, reverseDNS, ipBlackList, domainBlackList, spamAssassin, shortUrls, brokenLinks, each with a status."}}} },
  cost: { per: "request" },
})

export const getSpamCheck = defineFunction({
  name: "mailpool.get_spam_check",
  connector: "mailpool",
  class: "read",
  description: "Get one spam check with its state and detailed results.",
  schema: z.strictObject({
    "spam_check_id": z.int().gte(1).describe("Spam check id."),
  }),
  examples: [
    { title: "One spam check", input: {"spam_check_id": 880011} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/spam-checks/{spam_check_id}",
    pathParams: ["spam_check_id"],
    query: {},
    body: {},
    headers: {},
  },
  output: { strip: ["mailbox"], schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "email": {"type": "string", "description": "Mailpool's test address the email was sent to."}, "fromEmail": {"type": "string"}, "state": {"enum": ["pending", "completed"]}, "result": {"type": ["object", "null"], "description": "score, and SPF, DKIM, DMARK, domainAge, reverseDNS, ipBlackList, domainBlackList, spamAssassin, shortUrls, brokenLinks, each with a status."}}} },
  cost: { per: "request" },
})

export const deleteSpamCheck = defineFunction({
  name: "mailpool.delete_spam_check",
  connector: "mailpool",
  class: "write",
  description: "Delete one spam check from the history.",
  schema: z.strictObject({
    "spam_check_id": z.int().gte(1).describe("Spam check id."),
  }),
  examples: [
    { title: "Delete one spam check", input: {"spam_check_id": 880011} },
  ],
  refusals: [],
  request: {
    method: "DELETE",
    path: "/spam-checks/{spam_check_id}",
    pathParams: ["spam_check_id"],
    query: {},
    body: {},
    headers: {},
  },
  output: { strip: ["mailbox"], schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "createdAt": {"type": "string", "format": "date-time"}, "email": {"type": "string", "description": "Mailpool's test address the email was sent to."}, "fromEmail": {"type": "string"}, "state": {"enum": ["pending", "completed"]}, "result": {"type": ["object", "null"], "description": "score, and SPF, DKIM, DMARK, domainAge, reverseDNS, ipBlackList, domainBlackList, spamAssassin, shortUrls, brokenLinks, each with a status."}}} },
  cost: { per: "request" },
})

export const listWarmupInboxes = defineFunction({
  name: "mailpool.list_warmup_inboxes",
  connector: "mailpool",
  class: "read",
  description: "List the inboxes enrolled in Mailpool warmup, with their status.",
  schema: z.strictObject({
    "limit": z.int().gte(1).lte(100).describe("Page size."),
    "offset": z.int().gte(0).describe("Number of items to skip."),
  }),
  examples: [
    { title: "Warmup inboxes", input: {"limit": 50, "offset": 0} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/warmup",
    pathParams: [],
    query: {"limit": "limit", "offset": "offset"},
    body: {},
    headers: {},
  },
  output: { items: "data", schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "mailboxId": {"type": "integer"}, "email": {"type": "string"}, "fullName": {"type": "string"}, "type": {"type": "string"}, "status": {"type": "string"}, "warmboxId": {"type": ["integer", "string", "null"]}, "createdAt": {"type": "string", "format": "date-time"}}} },
  cost: { per: "request" },
})

export const getWarmupInbox = defineFunction({
  name: "mailpool.get_warmup_inbox",
  connector: "mailpool",
  class: "read",
  description: "Get one warmup inbox: settings and daily counters.",
  schema: z.strictObject({
    "warmup_id": z.int().gte(1).describe("Warmup inbox id."),
  }),
  examples: [
    { title: "One warmup inbox", input: {"warmup_id": 77} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/warmup/{warmup_id}",
    pathParams: ["warmup_id"],
    query: {},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "mailboxId": {"type": "integer"}, "email": {"type": "string"}, "status": {"type": "string"}, "dailyTarget": {"type": "number"}, "replyRate": {"type": "number"}, "duration": {"type": ["number", "null"]}, "counters": {"type": ["object", "array", "null"]}, "createdAt": {"type": "string", "format": "date-time"}}} },
  cost: { per: "request" },
})

export const listAvailableWarmupInboxes = defineFunction({
  name: "mailpool.list_available_warmup_inboxes",
  connector: "mailpool",
  class: "read",
  description: "List the active mailboxes that are not enrolled in warmup yet.",
  schema: z.strictObject({
    "limit": z.int().gte(1).lte(100).describe("Page size."),
    "offset": z.int().gte(0).describe("Number of items to skip."),
  }),
  examples: [
    { title: "Mailboxes that could be warmed up", input: {"limit": 50, "offset": 0} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/warmup/available-inboxes",
    pathParams: [],
    query: {"limit": "limit", "offset": "offset"},
    body: {},
    headers: {},
  },
  output: { items: "data", schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "email": {"type": "string"}, "fullName": {"type": "string"}, "type": {"type": "string"}}} },
  cost: { per: "request" },
})

export const getSubscriptionSlots = defineFunction({
  name: "mailpool.get_subscription_slots",
  connector: "mailpool",
  class: "read",
  description: "Get the mailboxes used and the slots paid, per mailbox type, and the warmup slots. A mailbox can only be created while a slot is free.",
  schema: z.strictObject({}),
  examples: [
    { title: "Slots in use", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/subscriptions/slots",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"mailboxes": {"type": "object", "description": "Mailboxes in use, per type."}, "slots": {"type": "object", "description": "Slots paid, per type."}, "warmup": {"type": "object", "description": "Warmup slots: used and paid."}}} },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "mailpool",
  label: "Mailpool",
  namespace: "mailpool",
  version: "1.0.0",
  apiVersion: "v1",
  baseUrl: "https://app.mailpool.io/v1/api",
  auth: {"kind": "api_key", "header": "X-Api-Authorization", "key": "api_key"},
  credential: [{"name": "api_key", "label": "Workspace API key", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 40000,
  errors: [
    { status: 400, code: "invalid_request", message: "Mailpool rejected the request as invalid: check the arguments (list calls need limit and offset).", retryable: false },
    { status: 401, code: "access_rejected", message: "Mailpool rejected the API key: check the workspace key.", retryable: false },
    { status: 403, code: "not_enabled", message: "Mailpool refused the operation: this feature is not enabled for the workspace.", retryable: false },
    { status: 404, code: "not_found", message: "Mailpool object not found in this workspace.", retryable: false },
    { status: 429, code: "rate_limited", message: "Mailpool rate limit reached: retry later.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Mailpool is temporarily unavailable: retry later.", retryable: true },
  ],
  functions: [
    listDomains,
    getDomain,
    getDomainDns,
    setDmarcEmail,
    setDmarcPolicy,
    setRedirectUrl,
    getDomainInfo,
    getDomainSuggestions,
    checkGoogleWorkspaceAvailability,
    checkMicrosoft365Availability,
    listDomainOwners,
    listMailboxes,
    getMailbox,
    listSpamChecks,
    createSpamCheck,
    getSpamCheck,
    deleteSpamCheck,
    listWarmupInboxes,
    getWarmupInbox,
    listAvailableWarmupInboxes,
    getSubscriptionSlots,
  ],
})
