// Generated by the fabrique from connectors/meta_ads/connector.yaml. Do not edit: run `python -m fabrique`.
// Not generated:
// - meta_ads.get_insights: input: not at the root needs a refinement
// - meta_ads.start_insights_report: input: not at the root needs a refinement
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const listCampaigns = defineFunction({
  name: "meta_ads.list_campaigns",
  connector: "meta_ads",
  class: "read",
  description: "List the campaigns of one ad account, one page at a time. Default fields: id, name, status, effective_status, objective, budgets and dates. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: z.strictObject({
    "ad_account_id": z.string().regex(new RegExp("^act_[0-9]+$")).describe("The ad account, act_ followed by digits."),
    "fields": z.string().meta({"description": "Comma-separated Graph fields; replaces the defaults.", "default": "id,name,status,effective_status,objective,daily_budget,lifetime_budget,start_time,stop_time,created_time"}).optional(),
    "effective_status": z.string().meta({"description": "JSON list of statuses, e.g. [\"ACTIVE\"], [\"PAUSED\"], [\"ARCHIVED\"].", "contentMediaType": "application/json"}).optional(),
    "filtering": z.string().meta({"description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}].", "contentMediaType": "application/json"}).optional(),
    "limit": z.int().gte(1).meta({"default": 50}).optional(),
    "after": z.string().min(1).describe("Cursor paging.cursors.after of the previous page.").optional(),
  }),
  examples: [
    { title: "Active campaigns of an ad account", input: {"ad_account_id": "act_1234567890", "effective_status": "[\"ACTIVE\"]"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{ad_account_id}/campaigns",
    pathParams: ["ad_account_id"],
    query: {"fields": "fields", "effective_status": "effective_status", "filtering": "filtering", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listAdsets = defineFunction({
  name: "meta_ads.list_adsets",
  connector: "meta_ads",
  class: "read",
  description: "List the ad sets of one ad account, one page at a time. Default fields: id, name, status, effective_status, campaign_id, budgets, optimization goal, billing event and dates. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: z.strictObject({
    "ad_account_id": z.string().regex(new RegExp("^act_[0-9]+$")).describe("The ad account, act_ followed by digits."),
    "fields": z.string().meta({"description": "Comma-separated Graph fields; replaces the defaults.", "default": "id,name,status,effective_status,campaign_id,daily_budget,lifetime_budget,optimization_goal,billing_event,start_time,end_time"}).optional(),
    "effective_status": z.string().meta({"description": "JSON list of statuses, e.g. [\"ACTIVE\"], [\"PAUSED\"], [\"ARCHIVED\"].", "contentMediaType": "application/json"}).optional(),
    "filtering": z.string().meta({"description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}].", "contentMediaType": "application/json"}).optional(),
    "limit": z.int().gte(1).meta({"default": 50}).optional(),
    "after": z.string().min(1).describe("Cursor paging.cursors.after of the previous page.").optional(),
  }),
  examples: [
    { title: "Ad sets of one campaign", input: {"ad_account_id": "act_1234567890", "filtering": "[{\"field\":\"campaign.id\",\"operator\":\"EQUAL\",\"value\":\"120200000000001\"}]"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{ad_account_id}/adsets",
    pathParams: ["ad_account_id"],
    query: {"fields": "fields", "effective_status": "effective_status", "filtering": "filtering", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listAds = defineFunction({
  name: "meta_ads.list_ads",
  connector: "meta_ads",
  class: "read",
  description: "List the ads of one ad account, one page at a time. Default fields: id, name, status, effective_status, campaign_id, adset_id, creative and created_time. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: z.strictObject({
    "ad_account_id": z.string().regex(new RegExp("^act_[0-9]+$")).describe("The ad account, act_ followed by digits."),
    "fields": z.string().meta({"description": "Comma-separated Graph fields; replaces the defaults.", "default": "id,name,status,effective_status,campaign_id,adset_id,creative{id,name},created_time"}).optional(),
    "effective_status": z.string().meta({"description": "JSON list of statuses, e.g. [\"ACTIVE\"], [\"PAUSED\"], [\"ARCHIVED\"].", "contentMediaType": "application/json"}).optional(),
    "filtering": z.string().meta({"description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}].", "contentMediaType": "application/json"}).optional(),
    "limit": z.int().gte(1).meta({"default": 50}).optional(),
    "after": z.string().min(1).describe("Cursor paging.cursors.after of the previous page.").optional(),
  }),
  examples: [
    { title: "Paused ads of an ad account", input: {"ad_account_id": "act_1234567890", "effective_status": "[\"PAUSED\"]", "limit": 25} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{ad_account_id}/ads",
    pathParams: ["ad_account_id"],
    query: {"fields": "fields", "effective_status": "effective_status", "filtering": "filtering", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const getObject = defineFunction({
  name: "meta_ads.get_object",
  connector: "meta_ads",
  class: "read",
  description: "Read one object of the ad tree by its id: a campaign, an ad set, an ad, or an ad account (act_ followed by digits).",
  schema: z.strictObject({
    "object_id": z.string().regex(new RegExp("^(act_)?[0-9]+$")).describe("A campaign, ad set or ad id (digits), or an ad account (act_ followed by digits)."),
    "fields": z.string().min(1).describe("Comma-separated Graph fields.").optional(),
  }),
  examples: [
    { title: "One campaign with its budget", input: {"object_id": "120200000000001", "fields": "id,name,status,daily_budget"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{object_id}",
    pathParams: ["object_id"],
    query: {"fields": "fields"},
    body: {},
    headers: {},
  },
})

export const getReportStatus = defineFunction({
  name: "meta_ads.get_report_status",
  connector: "meta_ads",
  class: "read",
  description: "Read the status of an asynchronous insights report: async_status (Job Completed, Job Failed, or still running) and async_percent_completion.",
  schema: z.strictObject({
    "report_run_id": z.string().regex(new RegExp("^[0-9]+$")).describe("From start_insights_report."),
    "fields": z.string().meta({"description": "Comma-separated report fields.", "default": "id,async_status,async_percent_completion,date_start,date_stop"}).optional(),
  }),
  examples: [
    { title: "Status of a report", input: {"report_run_id": "6000000000001"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{report_run_id}",
    pathParams: ["report_run_id"],
    query: {"fields": "fields"},
    body: {},
    headers: {},
  },
})

export const getReportInsights = defineFunction({
  name: "meta_ads.get_report_insights",
  connector: "meta_ads",
  class: "read",
  description: "Read the rows of a completed asynchronous insights report, one page at a time. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: z.strictObject({
    "report_run_id": z.string().regex(new RegExp("^[0-9]+$")).describe("From start_insights_report."),
    "limit": z.int().gte(1).meta({"default": 100}).optional(),
    "after": z.string().min(1).describe("Cursor paging.cursors.after of the previous page.").optional(),
  }),
  examples: [
    { title: "First page of a completed report", input: {"report_run_id": "6000000000001", "limit": 100} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{report_run_id}/insights",
    pathParams: ["report_run_id"],
    query: {"limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const connector = defineConnector({
  name: "meta_ads",
  label: "Meta Ads",
  namespace: "meta_ads",
  version: "1.0.0",
  apiVersion: "v25.0",
  baseUrl: "https://graph.facebook.com/v25.0",
  auth: {"kind": "bearer", "token": "access_token"},
  credential: [{"name": "access_token", "label": "Access token", "secret": true}],
  modes: ["byo_user"],
  timeoutMs: 30000,
  errors: [
    { status: 400, code: "invalid_request", message: "Meta rejected the request: check the ids, fields and parameters.", retryable: false },
    { status: 401, code: "authorization_expired", message: "Meta no longer accepts this authorization: reconnect the account and check that the ad accounts are still granted.", retryable: false },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Meta is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "meta_ads"},
  functions: [
    listCampaigns,
    listAdsets,
    listAds,
    getObject,
    getReportStatus,
    getReportInsights,
  ],
})
