// Generated by the fabrique from connectors/meta_ads/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const listCampaigns = defineFunction({
  name: "meta_ads.list_campaigns",
  connector: "meta_ads",
  class: "read",
  description: "List the campaigns of one ad account, one page at a time. Default fields: id, name, status, effective_status, objective, budgets and dates. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["ad_account_id"],
    "properties": {
      "ad_account_id": {"type": "string", "pattern": "^act_[0-9]+$", "description": "The ad account, act_ followed by digits."},
      "fields": {
        "type": "string",
        "default": "id,name,status,effective_status,objective,daily_budget,lifetime_budget,start_time,stop_time,created_time",
        "description": "Comma-separated Graph fields; replaces the defaults."
      },
      "effective_status": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of statuses, e.g. [\"ACTIVE\"], [\"PAUSED\"], [\"ARCHIVED\"]."
      },
      "filtering": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}]."
      },
      "limit": {"type": "integer", "minimum": 1, "default": 50},
      "after": {"type": "string", "minLength": 1, "description": "Cursor paging.cursors.after of the previous page."}
    }
  },
  examples: [
    { title: "Active campaigns of an ad account", input: {"ad_account_id": "act_1234567890", "effective_status": "[\"ACTIVE\"]"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{ad_account_id}/campaigns",
    pathParams: ["ad_account_id"],
    query: {"fields": "fields", "effective_status": "effective_status", "filtering": "filtering", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listAdsets = defineFunction({
  name: "meta_ads.list_adsets",
  connector: "meta_ads",
  class: "read",
  description: "List the ad sets of one ad account, one page at a time. Default fields: id, name, status, effective_status, campaign_id, budgets, optimization goal, billing event and dates. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["ad_account_id"],
    "properties": {
      "ad_account_id": {"type": "string", "pattern": "^act_[0-9]+$", "description": "The ad account, act_ followed by digits."},
      "fields": {
        "type": "string",
        "default": "id,name,status,effective_status,campaign_id,daily_budget,lifetime_budget,optimization_goal,billing_event,start_time,end_time",
        "description": "Comma-separated Graph fields; replaces the defaults."
      },
      "effective_status": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of statuses, e.g. [\"ACTIVE\"], [\"PAUSED\"], [\"ARCHIVED\"]."
      },
      "filtering": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}]."
      },
      "limit": {"type": "integer", "minimum": 1, "default": 50},
      "after": {"type": "string", "minLength": 1, "description": "Cursor paging.cursors.after of the previous page."}
    }
  },
  examples: [
    { title: "Ad sets of one campaign", input: {"ad_account_id": "act_1234567890", "filtering": "[{\"field\":\"campaign.id\",\"operator\":\"EQUAL\",\"value\":\"120200000000001\"}]"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{ad_account_id}/adsets",
    pathParams: ["ad_account_id"],
    query: {"fields": "fields", "effective_status": "effective_status", "filtering": "filtering", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const listAds = defineFunction({
  name: "meta_ads.list_ads",
  connector: "meta_ads",
  class: "read",
  description: "List the ads of one ad account, one page at a time. Default fields: id, name, status, effective_status, campaign_id, adset_id, creative and created_time. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["ad_account_id"],
    "properties": {
      "ad_account_id": {"type": "string", "pattern": "^act_[0-9]+$", "description": "The ad account, act_ followed by digits."},
      "fields": {
        "type": "string",
        "default": "id,name,status,effective_status,campaign_id,adset_id,creative{id,name},created_time",
        "description": "Comma-separated Graph fields; replaces the defaults."
      },
      "effective_status": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of statuses, e.g. [\"ACTIVE\"], [\"PAUSED\"], [\"ARCHIVED\"]."
      },
      "filtering": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}]."
      },
      "limit": {"type": "integer", "minimum": 1, "default": 50},
      "after": {"type": "string", "minLength": 1, "description": "Cursor paging.cursors.after of the previous page."}
    }
  },
  examples: [
    { title: "Paused ads of an ad account", input: {"ad_account_id": "act_1234567890", "effective_status": "[\"PAUSED\"]", "limit": 25} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{ad_account_id}/ads",
    pathParams: ["ad_account_id"],
    query: {"fields": "fields", "effective_status": "effective_status", "filtering": "filtering", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const getObject = defineFunction({
  name: "meta_ads.get_object",
  connector: "meta_ads",
  class: "read",
  description: "Read one object of the ad tree by its id: a campaign, an ad set, an ad, or an ad account (act_ followed by digits).",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["object_id"],
    "properties": {
      "object_id": {
        "type": "string",
        "pattern": "^(act_)?[0-9]+$",
        "description": "A campaign, ad set or ad id (digits), or an ad account (act_ followed by digits)."
      },
      "fields": {"type": "string", "minLength": 1, "description": "Comma-separated Graph fields."}
    }
  },
  examples: [
    { title: "One campaign with its budget", input: {"object_id": "120200000000001", "fields": "id,name,status,daily_budget"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{object_id}",
    pathParams: ["object_id"],
    query: {"fields": "fields"},
    body: {},
    headers: {},
  },
})

export const getInsights = defineFunction({
  name: "meta_ads.get_insights",
  connector: "meta_ads",
  class: "read",
  description: "Read performance insights (spend, reach, clicks, conversions) of an ad account, campaign, ad set or ad, synchronously, one page at a time. For long ranges, many breakdowns or ad level over a whole account, start an asynchronous report instead. Pass date_preset or time_range, not both. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["object_id"],
    "not": {"required": ["date_preset", "time_range"]},
    "properties": {
      "object_id": {
        "type": "string",
        "pattern": "^(act_)?[0-9]+$",
        "description": "A campaign, ad set or ad id (digits), or an ad account (act_ followed by digits)."
      },
      "level": {
        "type": "string",
        "enum": ["account", "campaign", "adset", "ad"],
        "description": "Aggregation level of the rows."
      },
      "fields": {
        "type": "string",
        "default": "spend,impressions,reach,frequency,clicks,cpc,cpm,ctr,actions,cost_per_action_type",
        "description": "Comma-separated metrics; replaces the defaults."
      },
      "date_preset": {
        "type": "string",
        "minLength": 1,
        "description": "e.g. today, yesterday, last_7d, last_30d, this_month, last_month, maximum."
      },
      "time_range": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON object {\"since\": \"YYYY-MM-DD\", \"until\": \"YYYY-MM-DD\"}."
      },
      "time_increment": {
        "anyOf": [
          {"type": "integer", "minimum": 1, "maximum": 90},
          {"type": "string", "enum": ["monthly", "all_days"]}
        ],
        "description": "1 = daily rows, 7 = weekly (any 1-90), monthly, all_days."
      },
      "breakdowns": {
        "type": "string",
        "minLength": 1,
        "description": "Comma-separated, e.g. age,gender or publisher_platform,platform_position."
      },
      "action_attribution_windows": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list, e.g. [\"7d_click\", \"1d_view\"]."
      },
      "filtering": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}]."
      },
      "sort": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list, e.g. [\"spend_descending\"]."
      },
      "limit": {"type": "integer", "minimum": 1, "default": 100},
      "after": {"type": "string", "minLength": 1, "description": "Cursor paging.cursors.after of the previous page."}
    }
  },
  examples: [
    { title: "Daily spend of a campaign over the last 7 days", input: {"object_id": "120200000000001", "date_preset": "last_7d", "time_increment": 1} },
    { title: "Account spend by age and gender in September", input: {"object_id": "act_1234567890", "level": "account", "fields": "spend,impressions,clicks", "time_range": "{\"since\":\"2026-09-01\",\"until\":\"2026-09-30\"}", "breakdowns": "age,gender"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
    { code: "too_much_data", when: "Graph error code 100 with subcode 1487534", message: "Meta refused: too much data for one call. Narrow the date range or breakdowns, or use an asynchronous report." },
  ],
  request: {
    method: "GET",
    path: "/{object_id}/insights",
    pathParams: ["object_id"],
    query: {"level": "level", "fields": "fields", "date_preset": "date_preset", "time_range": "time_range", "time_increment": "time_increment", "breakdowns": "breakdowns", "action_attribution_windows": "action_attribution_windows", "filtering": "filtering", "sort": "sort", "limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const startInsightsReport = defineFunction({
  name: "meta_ads.start_insights_report",
  connector: "meta_ads",
  class: "write",
  description: "Start an asynchronous insights report on Meta's side and return its report_run_id (valid 30 days). Then poll get_report_status until async_status is Job Completed, and read the rows with get_report_insights. Same parameters as get_insights; the attribution windows default to those of the synchronous call (7d_click, 1d_view), so both modes give the same figures.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["object_id"],
    "not": {"required": ["date_preset", "time_range"]},
    "properties": {
      "object_id": {
        "type": "string",
        "pattern": "^(act_)?[0-9]+$",
        "description": "A campaign, ad set or ad id (digits), or an ad account (act_ followed by digits)."
      },
      "level": {
        "type": "string",
        "enum": ["account", "campaign", "adset", "ad"],
        "description": "Aggregation level of the rows."
      },
      "fields": {
        "type": "string",
        "default": "spend,impressions,reach,frequency,clicks,cpc,cpm,ctr,actions,cost_per_action_type",
        "description": "Comma-separated metrics; replaces the defaults."
      },
      "date_preset": {
        "type": "string",
        "minLength": 1,
        "description": "e.g. today, yesterday, last_7d, last_30d, this_month, last_month, maximum."
      },
      "time_range": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON object {\"since\": \"YYYY-MM-DD\", \"until\": \"YYYY-MM-DD\"}."
      },
      "time_increment": {
        "anyOf": [
          {"type": "integer", "minimum": 1, "maximum": 90},
          {"type": "string", "enum": ["monthly", "all_days"]}
        ],
        "description": "1 = daily rows, 7 = weekly (any 1-90), monthly, all_days."
      },
      "breakdowns": {"type": "string", "minLength": 1, "description": "Comma-separated, e.g. age,gender."},
      "action_attribution_windows": {
        "type": "string",
        "contentMediaType": "application/json",
        "default": "[\"7d_click\",\"1d_view\"]",
        "description": "JSON list. Defaults to [\"7d_click\",\"1d_view\"], the synchronous default."
      },
      "filtering": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list of Graph filters, e.g. [{\"field\": \"campaign.id\", \"operator\": \"EQUAL\", \"value\": \"120200000000001\"}]."
      },
      "sort": {
        "type": "string",
        "contentMediaType": "application/json",
        "description": "JSON list, e.g. [\"spend_descending\"]."
      }
    }
  },
  examples: [
    { title: "Ad-level report over a whole account for last month", input: {"object_id": "act_1234567890", "level": "ad", "date_preset": "last_month", "time_increment": 1} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
    { code: "too_much_data", when: "Graph error code 100 with subcode 1487534", message: "Meta refused: too much data for one call. Narrow the date range or breakdowns, or use an asynchronous report." },
  ],
  request: {
    method: "POST",
    path: "/{object_id}/insights",
    pathParams: ["object_id"],
    query: {},
    body: {"level": "level", "fields": "fields", "date_preset": "date_preset", "time_range": "time_range", "time_increment": "time_increment", "breakdowns": "breakdowns", "action_attribution_windows": "action_attribution_windows", "filtering": "filtering", "sort": "sort"},
    headers: {},
  },
})

export const getReportStatus = defineFunction({
  name: "meta_ads.get_report_status",
  connector: "meta_ads",
  class: "read",
  description: "Read the status of an asynchronous insights report: async_status (Job Completed, Job Failed, or still running) and async_percent_completion.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["report_run_id"],
    "properties": {
      "report_run_id": {"type": "string", "pattern": "^[0-9]+$", "description": "From start_insights_report."},
      "fields": {
        "type": "string",
        "default": "id,async_status,async_percent_completion,date_start,date_stop",
        "description": "Comma-separated report fields."
      }
    }
  },
  examples: [
    { title: "Status of a report", input: {"report_run_id": "6000000000001"} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{report_run_id}",
    pathParams: ["report_run_id"],
    query: {"fields": "fields"},
    body: {},
    headers: {},
  },
})

export const getReportInsights = defineFunction({
  name: "meta_ads.get_report_insights",
  connector: "meta_ads",
  class: "read",
  description: "Read the rows of a completed asynchronous insights report, one page at a time. To get the next page, pass paging.cursors.after as after, only when paging.next is present.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["report_run_id"],
    "properties": {
      "report_run_id": {"type": "string", "pattern": "^[0-9]+$", "description": "From start_insights_report."},
      "limit": {"type": "integer", "minimum": 1, "default": 100},
      "after": {"type": "string", "minLength": 1, "description": "Cursor paging.cursors.after of the previous page."}
    }
  },
  examples: [
    { title: "First page of a completed report", input: {"report_run_id": "6000000000001", "limit": 100} },
  ],
  refusals: [
    { code: "authorization_expired", when: "Graph error code 190 or 102", message: "Meta no longer accepts this authorization: reconnect the account." },
    { code: "rate_limited", when: "Graph error code 4, 17, 32, 613 or 80000 to 80014", message: "Meta rate limit reached: wait a few minutes before retrying." },
  ],
  request: {
    method: "GET",
    path: "/{report_run_id}/insights",
    pathParams: ["report_run_id"],
    query: {"limit": "limit", "after": "after"},
    body: {},
    headers: {},
  },
  output: { items: "data" },
})

export const connector = defineConnector({
  name: "meta_ads",
  label: "Meta Ads",
  namespace: "meta_ads",
  version: "1.0.0",
  apiVersion: "v25.0",
  baseUrl: "https://graph.facebook.com/v25.0",
  auth: {"kind": "bearer", "token": "access_token"},
  credential: [{"name": "access_token", "label": "Access token", "secret": true}],
  modes: ["byo_user"],
  timeoutMs: 30000,
  errors: [
    { status: 400, code: "invalid_request", message: "Meta rejected the request: check the ids, fields and parameters.", retryable: false },
    { status: 401, code: "authorization_expired", message: "Meta no longer accepts this authorization: reconnect the account and check that the ad accounts are still granted.", retryable: false },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Meta is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "meta_ads"},
  functions: [
    listCampaigns,
    listAdsets,
    listAds,
    getObject,
    getInsights,
    startInsightsReport,
    getReportStatus,
    getReportInsights,
  ],
})
