// Generated by the fabrique from connectors/microsoft/connector.yaml. Do not edit: run `python -m fabrique`.
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const searchSites = defineFunction({
  name: "microsoft.search_sites",
  connector: "microsoft",
  class: "read",
  description: "Search the SharePoint sites whose name or description matches a query. Only the sites the signed-in person can open are returned.",
  schema: z.strictObject({
    "query": z.string().min(1).describe("Words to look for."),
    "limit": z.int().gte(1).lte(200).meta({"description": "Maximum number of results in the page.", "default": 50}).optional(),
  }),
  examples: [
    { title: "Sites about marketing", input: {"query": "marketing"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/sites",
    pathParams: [],
    query: {"search": "query", "$top": "limit"},
    body: {},
    headers: {},
  },
  output: { items: "value" },
  cost: { per: "request" },
})

export const getSite = defineFunction({
  name: "microsoft.get_site",
  connector: "microsoft",
  class: "read",
  description: "Get one SharePoint site by its composite id ({hostname},{site-collection-id},{web-id}), as returned by search_sites.",
  schema: z.strictObject({
    "site_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Composite site id: {hostname},{site-collection-id},{web-id}."),
  }),
  examples: [
    { title: "One site by id", input: {"site_id": "acme.sharepoint.com,0f1e2d3c-4b5a-6978-8796-a5b4c3d2e1f0,1a2b3c4d-5e6f-7081-92a3-b4c5d6e7f809"} },
  ],
  refusals: [
    { code: "site_not_found", when: 404, message: "No SharePoint site with this id that the signed-in person can open." },
  ],
  request: {
    method: "GET",
    path: "/sites/{site_id}",
    pathParams: ["site_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getSiteByPath = defineFunction({
  name: "microsoft.get_site_by_path",
  connector: "microsoft",
  class: "read",
  description: "Get one SharePoint site by the host name and server-relative path read in its URL: https://acme.sharepoint.com/sites/Marketing gives hostname acme.sharepoint.com and site_path sites/Marketing.",
  schema: z.strictObject({
    "hostname": z.string().regex(new RegExp("^[A-Za-z0-9.-]+$")).describe("SharePoint host name, e.g. acme.sharepoint.com."),
    "site_path": z.string().regex(new RegExp("^[^/?#:]([^?#:]*[^/?#:])?$")).describe("Site path without leading or trailing slash, e.g. sites/Marketing. Its slashes are kept."),
  }),
  examples: [
    { title: "The marketing site of Acme", input: {"hostname": "acme.sharepoint.com", "site_path": "sites/Marketing"} },
  ],
  refusals: [
    { code: "site_not_found", when: 404, message: "No SharePoint site at this path that the signed-in person can open." },
  ],
  request: {
    method: "GET",
    path: "/sites/{hostname}:/{site_path}",
    pathParams: ["hostname", "site_path"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listSiteDrives = defineFunction({
  name: "microsoft.list_site_drives",
  connector: "microsoft",
  class: "read",
  description: "List the document libraries of a SharePoint site. A library is a drive: its id is the drive_id of the item functions.",
  schema: z.strictObject({
    "site_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Composite site id: {hostname},{site-collection-id},{web-id}."),
    "limit": z.int().gte(1).lte(200).meta({"description": "Maximum number of libraries in the page.", "default": 100}).optional(),
  }),
  examples: [
    { title: "Libraries of one site", input: {"site_id": "acme.sharepoint.com,0f1e2d3c-4b5a-6978-8796-a5b4c3d2e1f0,1a2b3c4d-5e6f-7081-92a3-b4c5d6e7f809"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/sites/{site_id}/drives",
    pathParams: ["site_id"],
    query: {"$top": "limit"},
    body: {},
    headers: {},
  },
  output: { items: "value" },
  cost: { per: "request" },
})

export const getMe = defineFunction({
  name: "microsoft.get_me",
  connector: "microsoft",
  class: "read",
  description: "Get the signed-in person: id, displayName, mail and userPrincipalName. Every other function acts on their behalf and sees what they see.",
  schema: z.strictObject({}),
  examples: [
    { title: "Who the token acts as", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/me",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getMyDrive = defineFunction({
  name: "microsoft.get_my_drive",
  connector: "microsoft",
  class: "read",
  description: "Get the OneDrive of the signed-in person. Its id is the drive_id of the item functions.",
  schema: z.strictObject({}),
  examples: [
    { title: "My OneDrive", input: {} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/me/drive",
    pathParams: [],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getUserDrive = defineFunction({
  name: "microsoft.get_user_drive",
  connector: "microsoft",
  class: "read",
  description: "Get the OneDrive of a colleague, by user id or userPrincipalName (usually the work email), if they shared it with the signed-in person. Its id is the drive_id of the item functions.",
  schema: z.strictObject({
    "user": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("User id or userPrincipalName, e.g. jane.doe@acme.example."),
  }),
  examples: [
    { title: "The OneDrive of one person", input: {"user": "jane.doe@acme.example"} },
  ],
  refusals: [
    { code: "drive_not_found", when: 404, message: "No such user, or this user has no OneDrive." },
  ],
  request: {
    method: "GET",
    path: "/users/{user}/drive",
    pathParams: ["user"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getItem = defineFunction({
  name: "microsoft.get_item",
  connector: "microsoft",
  class: "read",
  description: "Get the metadata of one file or folder of a drive by its item id.",
  schema: z.strictObject({
    "drive_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Drive id, from list_site_drives, get_my_drive or get_user_drive."),
    "item_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Item id, as returned by the other item functions."),
  }),
  examples: [
    { title: "One file by id", input: {"drive_id": "b!AcmeDrive0001", "item_id": "01ACMEITEM0000000000000000000001"} },
  ],
  refusals: [
    { code: "item_not_found", when: 404, message: "No item with this id in this drive." },
  ],
  request: {
    method: "GET",
    path: "/drives/{drive_id}/items/{item_id}",
    pathParams: ["drive_id", "item_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const getItemByPath = defineFunction({
  name: "microsoft.get_item_by_path",
  connector: "microsoft",
  class: "read",
  description: "Get the metadata of one file or folder of a drive by its path from the drive root, e.g. Contracts/2026/nda.docx.",
  schema: z.strictObject({
    "drive_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Drive id, from list_site_drives, get_my_drive or get_user_drive."),
    "path": z.string().regex(new RegExp("^[^/?#:]([^?#:]*[^/?#:])?$")).describe("Path from the drive root, without leading or trailing slash. Its slashes are kept."),
  }),
  examples: [
    { title: "One contract by path", input: {"drive_id": "b!AcmeDrive0001", "path": "Contracts/2026/nda.docx"} },
  ],
  refusals: [
    { code: "item_not_found", when: 404, message: "No item at this path in this drive." },
  ],
  request: {
    method: "GET",
    path: "/drives/{drive_id}/root:/{path}:",
    pathParams: ["drive_id", "path"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listRootChildren = defineFunction({
  name: "microsoft.list_root_children",
  connector: "microsoft",
  class: "read",
  description: "List the files and folders at the root of a drive.",
  schema: z.strictObject({
    "drive_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Drive id, from list_site_drives, get_my_drive or get_user_drive."),
    "limit": z.int().gte(1).lte(200).meta({"description": "Maximum number of items in the page.", "default": 200}).optional(),
  }),
  examples: [
    { title: "Root of a library", input: {"drive_id": "b!AcmeDrive0001"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/drives/{drive_id}/root/children",
    pathParams: ["drive_id"],
    query: {"$top": "limit"},
    body: {},
    headers: {},
  },
  output: { items: "value" },
  cost: { per: "request" },
})

export const listChildren = defineFunction({
  name: "microsoft.list_children",
  connector: "microsoft",
  class: "read",
  description: "List the files and folders inside one folder of a drive, by the folder's item id.",
  schema: z.strictObject({
    "drive_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Drive id, from list_site_drives, get_my_drive or get_user_drive."),
    "item_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Item id, as returned by the other item functions."),
    "limit": z.int().gte(1).lte(200).meta({"description": "Maximum number of items in the page.", "default": 200}).optional(),
  }),
  examples: [
    { title: "Content of one folder by id", input: {"drive_id": "b!AcmeDrive0001", "item_id": "01ACMEFOLDER00000000000000000001", "limit": 50} },
  ],
  refusals: [
    { code: "folder_not_found", when: 404, message: "No folder with this id in this drive." },
  ],
  request: {
    method: "GET",
    path: "/drives/{drive_id}/items/{item_id}/children",
    pathParams: ["drive_id", "item_id"],
    query: {"$top": "limit"},
    body: {},
    headers: {},
  },
  output: { items: "value" },
  cost: { per: "request" },
})

export const listChildrenByPath = defineFunction({
  name: "microsoft.list_children_by_path",
  connector: "microsoft",
  class: "read",
  description: "List the files and folders inside one folder of a drive, by the folder's path from the drive root, e.g. Contracts/2026.",
  schema: z.strictObject({
    "drive_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Drive id, from list_site_drives, get_my_drive or get_user_drive."),
    "path": z.string().regex(new RegExp("^[^/?#:]([^?#:]*[^/?#:])?$")).describe("Path from the drive root, without leading or trailing slash. Its slashes are kept."),
    "limit": z.int().gte(1).lte(200).meta({"description": "Maximum number of items in the page.", "default": 200}).optional(),
  }),
  examples: [
    { title: "Content of one folder by path", input: {"drive_id": "b!AcmeDrive0001", "path": "Contracts/2026"} },
  ],
  refusals: [
    { code: "folder_not_found", when: 404, message: "No folder at this path in this drive." },
  ],
  request: {
    method: "GET",
    path: "/drives/{drive_id}/root:/{path}:/children",
    pathParams: ["drive_id", "path"],
    query: {"$top": "limit"},
    body: {},
    headers: {},
  },
  output: { items: "value" },
  cost: { per: "request" },
})

export const searchItems = defineFunction({
  name: "microsoft.search_items",
  connector: "microsoft",
  class: "read",
  description: "Search the files of a whole drive by name, metadata and content. Results come from the SharePoint index, not a live scan: a file added seconds ago may not show yet. The query cannot contain an apostrophe.",
  schema: z.strictObject({
    "drive_id": z.string().regex(new RegExp("^[^\\s/?#]+$")).describe("Drive id, from list_site_drives, get_my_drive or get_user_drive."),
    "query": z.string().min(1).regex(new RegExp("^[^'/?#]+$")).describe("Words to look for, without apostrophe."),
    "limit": z.int().gte(1).lte(200).meta({"description": "Maximum number of results in the page.", "default": 50}).optional(),
  }),
  examples: [
    { title: "Files about a supplier contract", input: {"drive_id": "b!AcmeDrive0001", "query": "supplier contract"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/drives/{drive_id}/root/search(q='{query}')",
    pathParams: ["drive_id", "query"],
    query: {"$top": "limit"},
    body: {},
    headers: {},
  },
  output: { items: "value" },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "microsoft",
  label: "Microsoft 365 (SharePoint, OneDrive)",
  namespace: "microsoft",
  version: "2.0.0",
  apiVersion: "v1.0",
  baseUrl: "https://graph.microsoft.com/v1.0",
  auth: {"kind": "bearer", "token": "access_token"},
  credential: [{"name": "access_token", "label": "Delegated access token", "secret": true}],
  modes: ["byo_user"],
  timeoutMs: 120000,
  errors: [
    { status: 400, code: "invalid_request", message: "Microsoft Graph rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "authorization_expired", message: "Microsoft no longer accepts this access token (expired or revoked): renew it, or have the person sign in again.", retryable: false },
    { status: 403, code: "permission_missing", message: "The signed-in person has no access to this resource, or a delegated scope is missing (offline_access, User.Read, Files.ReadWrite.All, Sites.ReadWrite.All). It does not mean the resource is absent.", retryable: false },
    { status: 404, code: "not_found", message: "Microsoft Graph object not found: check the id or path.", retryable: false },
    { status: 429, code: "rate_limited", message: "Microsoft Graph is throttling these requests: retry after the delay it gives.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Microsoft Graph is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "microsoft"},
  functions: [
    searchSites,
    getSite,
    getSiteByPath,
    listSiteDrives,
    getMe,
    getMyDrive,
    getUserDrive,
    getItem,
    getItemByPath,
    listRootChildren,
    listChildren,
    listChildrenByPath,
    searchItems,
  ],
})
