// Generated by the fabrique from connectors/notion/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const searchWorkspace = defineFunction({
  name: "notion.search_workspace",
  connector: "notion",
  class: "read",
  description: "Search the pages and databases shared with the integration, one page of results at a time (at most 100). The integration sees only what was shared with it in Notion: an empty result with an empty query and no filter means nothing is shared, not that the workspace is empty. Databases come back as data_source objects. Pass next_cursor as start_cursor to read the next page.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "query": {"type": "string", "description": "Text to match; empty lists everything the integration can see."},
      "filter": {
        "type": "object",
        "additionalProperties": false,
        "required": ["value", "property"],
        "properties": {"value": {"enum": ["page", "data_source"]}, "property": {"const": "object"}},
        "description": "Restrict to pages or to databases (data_source)."
      },
      "sort": {
        "type": "object",
        "additionalProperties": false,
        "required": ["direction", "timestamp"],
        "properties": {"direction": {"enum": ["ascending", "descending"]}, "timestamp": {"const": "last_edited_time"}},
        "description": "Sort by last edit; omit for relevance."
      },
      "start_cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "Pages about the roadmap, most recently edited first", input: {"query": "roadmap", "filter": {"value": "page", "property": "object"}, "sort": {"direction": "descending", "timestamp": "last_edited_time"}} },
    { title: "Everything shared with the integration", input: {"query": ""} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/search",
    pathParams: [],
    query: {},
    body: {"query": "query", "filter": "filter", "sort": "sort", "start_cursor": "start_cursor"},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const getPage = defineFunction({
  name: "notion.get_page",
  connector: "notion",
  class: "read",
  description: "Get a page's metadata and property values, not its content (see get_page_markdown or list_block_children for the content).",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["page_id"],
    "properties": {
      "page_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      }
    }
  },
  examples: [
    { title: "One page", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [
    { code: "page_not_found", when: 404, message: "No page with this id shared with the integration." },
  ],
  request: {
    method: "GET",
    path: "/pages/{page_id}",
    pathParams: ["page_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listBlockChildren = defineFunction({
  name: "notion.list_block_children",
  connector: "notion",
  class: "read",
  description: "List the blocks directly inside a page or a block, one level only, one page of results at a time. A block with has_children true is read the same way with its own id.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["block_id"],
    "properties": {
      "block_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "start_cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 50)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 50,
        "default": 50,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "Top-level content of a page", input: {"block_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/blocks/{block_id}/children",
    pathParams: ["block_id"],
    query: {"page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", more: "has_more", maxPages: 50 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const queryDataSource = defineFunction({
  name: "notion.query_data_source",
  connector: "notion",
  class: "read",
  description: "Query the rows of a database through its data source, one page at a time. Pass the data source id that search_workspace returns for a database, not the database id.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["data_source_id"],
    "properties": {
      "data_source_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "filter": {
        "type": "object",
        "description": "Notion filter object, e.g. {\"property\": \"Status\", \"select\": {\"equals\": \"Done\"}}."
      },
      "sorts": {
        "type": "array",
        "items": {"type": "object"},
        "description": "Notion sorts, e.g. [{\"property\": \"Due\", \"direction\": \"ascending\"}]."
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "start_cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "Rows whose status is Done", input: {"data_source_id": "2a3b4c5d6e7f80912a3b4c5d6e7f8091", "filter": {"property": "Status", "select": {"equals": "Done"}}, "page_size": 50} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/data_sources/{data_source_id}/query",
    pathParams: ["data_source_id"],
    query: {},
    body: {"filter": "filter", "sorts": "sorts", "page_size": "page_size", "start_cursor": "start_cursor"},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const createPage = defineFunction({
  name: "notion.create_page",
  connector: "notion",
  class: "write",
  description: "Create a page under a page, or a row in a database through its data source. For a row, properties are keyed by column name and must set the title column (whatever its name). children holds at most 100 blocks; add more with append_block_children.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["parent", "properties"],
    "properties": {
      "parent": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["page_id"],
            "properties": {
              "page_id": {
                "type": "string",
                "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                "description": "Notion id: 32 hexadecimal characters, dashes allowed."
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "data_source_id"],
            "properties": {
              "type": {"const": "data_source_id"},
              "data_source_id": {
                "type": "string",
                "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                "description": "Notion id: 32 hexadecimal characters, dashes allowed."
              }
            }
          }
        ],
        "description": "{page_id} for a sub-page, {type: data_source_id, data_source_id} for a database row."
      },
      "properties": {
        "type": "object",
        "description": "Property values. Under a page: {\"title\": {\"title\": [{\"text\": {\"content\": \"...\"}}]}}. In a database: keyed by column name."
      },
      "children": {
        "type": "array",
        "minItems": 1,
        "maxItems": 100,
        "items": {"type": "object"},
        "description": "Notion block objects, at most 100."
      }
    }
  },
  examples: [
    { title: "A sub-page with one paragraph", input: {"parent": {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"}, "properties": {"title": {"title": [{"text": {"content": "Meeting notes"}}]}}, "children": [{"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Agenda"}}]}}]} },
    { title: "A row in a task database", input: {"parent": {"type": "data_source_id", "data_source_id": "2a3b4c5d6e7f80912a3b4c5d6e7f8091"}, "properties": {"Name": {"title": [{"text": {"content": "Call Acme"}}]}, "Status": {"select": {"name": "Todo"}}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/pages",
    pathParams: [],
    query: {},
    body: {"parent": "parent", "properties": "properties", "children": "children"},
    headers: {},
  },
  cost: { per: "request" },
})

export const updatePage = defineFunction({
  name: "notion.update_page",
  connector: "notion",
  class: "write",
  description: "Update a page's property values, icon or cover, or move it to the trash (in_trash true) and back (in_trash false). The trash can be emptied from Notion.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["page_id"],
    "minProperties": 2,
    "properties": {
      "page_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "properties": {"type": "object", "description": "Property values to set, keyed by property name."},
      "in_trash": {"type": "boolean"},
      "icon": {"type": "object", "description": "e.g. {\"type\": \"emoji\", \"emoji\": \"...\"}."},
      "cover": {
        "type": "object",
        "description": "e.g. {\"type\": \"external\", \"external\": {\"url\": \"https://...\"}}."
      }
    }
  },
  examples: [
    { title: "Mark a task done", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "properties": {"Status": {"select": {"name": "Done"}}}} },
    { title: "Restore a page from the trash", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "in_trash": false} },
  ],
  refusals: [],
  request: {
    method: "PATCH",
    path: "/pages/{page_id}",
    pathParams: ["page_id"],
    query: {},
    body: {"properties": "properties", "in_trash": "in_trash", "icon": "icon", "cover": "cover"},
    headers: {},
  },
  cost: { per: "request" },
})

export const movePage = defineFunction({
  name: "notion.move_page",
  connector: "notion",
  class: "write",
  description: "Move a page under another page, or into a database through its data source.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["page_id", "parent"],
    "properties": {
      "page_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "parent": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "page_id"],
            "properties": {
              "type": {"const": "page_id"},
              "page_id": {
                "type": "string",
                "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                "description": "Notion id: 32 hexadecimal characters, dashes allowed."
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "data_source_id"],
            "properties": {
              "type": {"const": "data_source_id"},
              "data_source_id": {
                "type": "string",
                "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                "description": "Notion id: 32 hexadecimal characters, dashes allowed."
              }
            }
          }
        ]
      }
    }
  },
  examples: [
    { title: "Move a page under another page", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "parent": {"type": "page_id", "page_id": "3c4d5e6f7a8b9c0d3c4d5e6f7a8b9c0d"}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/pages/{page_id}/move",
    pathParams: ["page_id"],
    query: {},
    body: {"parent": "parent"},
    headers: {},
  },
  cost: { per: "request" },
})

export const appendBlockChildren = defineFunction({
  name: "notion.append_block_children",
  connector: "notion",
  class: "write",
  description: "Add at most 100 blocks inside a page or a block: at the end (default), at the start, or right after an existing child block.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["block_id", "children"],
    "properties": {
      "block_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "children": {
        "type": "array",
        "minItems": 1,
        "maxItems": 100,
        "items": {"type": "object"},
        "description": "Notion block objects, at most 100."
      },
      "position": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type"],
            "properties": {"type": {"enum": ["start", "end"]}}
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "after_block"],
            "properties": {
              "type": {"const": "after_block"},
              "after_block": {
                "type": "object",
                "additionalProperties": false,
                "required": ["id"],
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                    "description": "Notion id: 32 hexadecimal characters, dashes allowed."
                  }
                }
              }
            }
          }
        ],
        "description": "{type: start|end}, or {type: after_block, after_block: {id}}."
      }
    }
  },
  examples: [
    { title: "A to-do at the top of a page", input: {"block_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "children": [{"object": "block", "type": "to_do", "to_do": {"rich_text": [{"type": "text", "text": {"content": "Send the quote to Acme"}}], "checked": false}}], "position": {"type": "start"}} },
  ],
  refusals: [],
  request: {
    method: "PATCH",
    path: "/blocks/{block_id}/children",
    pathParams: ["block_id"],
    query: {},
    body: {"children": "children", "position": "position"},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteBlock = defineFunction({
  name: "notion.delete_block",
  connector: "notion",
  class: "sensitive",
  description: "Move one block to the trash, with its children. It can be restored from Notion until the trash is emptied.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["block_id"],
    "properties": {
      "block_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      }
    }
  },
  examples: [
    { title: "Delete one block", input: {"block_id": "4d5e6f7a8b9c0d1e4d5e6f7a8b9c0d1e"} },
  ],
  refusals: [
    { code: "block_not_found", when: 404, message: "No block with this id shared with the integration." },
  ],
  request: {
    method: "DELETE",
    path: "/blocks/{block_id}",
    pathParams: ["block_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Move Notion block {block_id} and its children to the trash." },
})

export const getPageMarkdown = defineFunction({
  name: "notion.get_page_markdown",
  connector: "notion",
  class: "read",
  description: "Get a page's whole content as Notion-flavoured Markdown, lighter than reading blocks. truncated true with unknown_block_ids: some parts were not loaded (very large page, or child pages not shared); each id can be read the same way.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["page_id"],
    "properties": {
      "page_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      }
    }
  },
  examples: [
    { title: "One page as Markdown", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [
    { code: "page_not_found", when: 404, message: "No page with this id shared with the integration." },
  ],
  request: {
    method: "GET",
    path: "/pages/{page_id}/markdown",
    pathParams: ["page_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const editPageMarkdown = defineFunction({
  name: "notion.edit_page_markdown",
  connector: "notion",
  class: "write",
  description: "Edit a page's content as Markdown, in exactly one mode named by type: update_content (search and replace, at most 100 replacements, each old_str matching once unless replace_all_matches), replace_content (the whole page) or insert_content (at the start or the end). An edit that would remove child pages or databases is refused unless allow_deleting_content is true.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["page_id", "type"],
    "properties": {
      "page_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "type": {"enum": ["update_content", "replace_content", "insert_content"]},
      "update_content": {
        "type": "object",
        "additionalProperties": false,
        "required": ["content_updates"],
        "properties": {
          "content_updates": {
            "type": "array",
            "minItems": 1,
            "maxItems": 100,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": ["old_str", "new_str"],
              "properties": {
                "old_str": {"type": "string", "minLength": 1},
                "new_str": {"type": "string"},
                "replace_all_matches": {"type": "boolean", "default": false}
              }
            }
          },
          "allow_deleting_content": {"type": "boolean", "default": false}
        }
      },
      "replace_content": {
        "type": "object",
        "additionalProperties": false,
        "required": ["new_str"],
        "properties": {"new_str": {"type": "string"}, "allow_deleting_content": {"type": "boolean", "default": false}}
      },
      "insert_content": {
        "type": "object",
        "additionalProperties": false,
        "required": ["content", "position"],
        "properties": {
          "content": {"type": "string", "minLength": 1},
          "position": {
            "type": "object",
            "additionalProperties": false,
            "required": ["type"],
            "properties": {"type": {"enum": ["start", "end"]}}
          }
        }
      }
    },
    "oneOf": [
      {
        "properties": {"type": {"const": "update_content"}},
        "required": ["update_content"],
        "not": {"anyOf": [{"required": ["replace_content"]}, {"required": ["insert_content"]}]}
      },
      {
        "properties": {"type": {"const": "replace_content"}},
        "required": ["replace_content"],
        "not": {"anyOf": [{"required": ["update_content"]}, {"required": ["insert_content"]}]}
      },
      {
        "properties": {"type": {"const": "insert_content"}},
        "required": ["insert_content"],
        "not": {"anyOf": [{"required": ["update_content"]}, {"required": ["replace_content"]}]}
      }
    ]
  },
  examples: [
    { title: "Fix one sentence", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "type": "update_content", "update_content": {"content_updates": [{"old_str": "Due on Monday", "new_str": "Due on Tuesday"}]}} },
    { title: "Add a section at the end", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "type": "insert_content", "insert_content": {"content": "## Next steps\n- Call Acme", "position": {"type": "end"}}} },
  ],
  refusals: [],
  request: {
    method: "PATCH",
    path: "/pages/{page_id}/markdown",
    pathParams: ["page_id"],
    query: {},
    body: {"type": "type", "update_content": "update_content", "replace_content": "replace_content", "insert_content": "insert_content"},
    headers: {},
  },
  cost: { per: "request" },
})

export const listComments = defineFunction({
  name: "notion.list_comments",
  connector: "notion",
  class: "read",
  description: "List the open (unresolved) comments on a page or a block, one page at a time. Each comment carries its discussion_id, to reply in the thread with add_comment. The integration needs the read comments capability, off by default in Notion.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["block_id"],
    "properties": {
      "block_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "start_cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "Comments on a page", input: {"block_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Reading comments is a capability turned off by default: turn it on in the integration's settings." },
  ],
  request: {
    method: "GET",
    path: "/comments",
    pathParams: [],
    query: {"block_id": "block_id", "page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const addComment = defineFunction({
  name: "notion.add_comment",
  connector: "notion",
  class: "write",
  description: "Comment on a page or a block, or reply in an existing discussion: give parent or discussion_id, not both. text is Markdown, inline formatting only. The integration needs the insert comments capability, off by default in Notion.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["text"],
    "properties": {
      "text": {"type": "string", "minLength": 1},
      "parent": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["page_id"],
            "properties": {
              "page_id": {
                "type": "string",
                "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                "description": "Notion id: 32 hexadecimal characters, dashes allowed."
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["block_id"],
            "properties": {
              "block_id": {
                "type": "string",
                "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
                "description": "Notion id: 32 hexadecimal characters, dashes allowed."
              }
            }
          }
        ],
        "description": "{page_id} or {block_id}."
      },
      "discussion_id": {"type": "string", "minLength": 1, "description": "discussion_id of a comment, to reply in its thread."}
    },
    "oneOf": [{"required": ["parent"]}, {"required": ["discussion_id"]}]
  },
  examples: [
    { title: "Comment on a page", input: {"text": "Validated with **Acme**.", "parent": {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"}} },
    { title: "Reply in a discussion", input: {"text": "Done.", "discussion_id": "5e6f7a8b-9c0d-1e2f-5e6f-7a8b9c0d1e2f"} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Inserting comments is a capability turned off by default: turn it on in the integration's settings." },
  ],
  request: {
    method: "POST",
    path: "/comments",
    pathParams: [],
    query: {},
    body: {"markdown": "text", "parent": "parent", "discussion_id": "discussion_id"},
    headers: {},
  },
  cost: { per: "request" },
})

export const updateComment = defineFunction({
  name: "notion.update_comment",
  connector: "notion",
  class: "write",
  description: "Rewrite a comment the integration wrote. text is Markdown, inline formatting only.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["comment_id", "text"],
    "properties": {
      "comment_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "text": {"type": "string", "minLength": 1}
    }
  },
  examples: [
    { title: "Rewrite a comment", input: {"comment_id": "6f7a8b9c0d1e2f306f7a8b9c0d1e2f30", "text": "Validated with **Acme** on Monday."} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Editing comments needs the comment capabilities, turned off by default: turn them on in the integration's settings." },
  ],
  request: {
    method: "PATCH",
    path: "/comments/{comment_id}",
    pathParams: ["comment_id"],
    query: {},
    body: {"markdown": "text"},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteComment = defineFunction({
  name: "notion.delete_comment",
  connector: "notion",
  class: "sensitive",
  description: "Delete a comment the integration wrote.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["comment_id"],
    "properties": {
      "comment_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      }
    }
  },
  examples: [
    { title: "Delete a comment", input: {"comment_id": "6f7a8b9c0d1e2f306f7a8b9c0d1e2f30"} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Deleting comments needs the comment capabilities, turned off by default: turn them on in the integration's settings." },
  ],
  request: {
    method: "DELETE",
    path: "/comments/{comment_id}",
    pathParams: ["comment_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Delete Notion comment {comment_id}." },
})

export const createDatabase = defineFunction({
  name: "notion.create_database",
  connector: "notion",
  class: "write",
  description: "Create a database inside a page, with its column schema (initial_data_source.properties, which must contain one title column) or with one of Notion's own schemas (database_type), not both.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["parent"],
    "properties": {
      "parent": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type", "page_id"],
        "properties": {
          "type": {"const": "page_id"},
          "page_id": {
            "type": "string",
            "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
            "description": "Notion id: 32 hexadecimal characters, dashes allowed."
          }
        }
      },
      "title": {
        "type": "array",
        "items": {"type": "object"},
        "description": "Rich text, e.g. [{\"type\": \"text\", \"text\": {\"content\": \"Tasks\"}}]."
      },
      "is_inline": {
        "type": "boolean",
        "default": false,
        "description": "Show it inside the page rather than as a sub-page."
      },
      "initial_data_source": {
        "type": "object",
        "additionalProperties": false,
        "required": ["properties"],
        "properties": {
          "properties": {
            "type": "object",
            "description": "Column schema, e.g. {\"Name\": {\"title\": {}}, \"Status\": {\"select\": {\"options\": [{\"name\": \"Todo\"}]}}, \"Due\": {\"date\": {}}}."
          }
        }
      },
      "database_type": {"enum": ["tasks", "projects", "skills"]}
    },
    "not": {"required": ["initial_data_source", "database_type"]}
  },
  examples: [
    { title: "A task database with a status column", input: {"parent": {"type": "page_id", "page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"}, "title": [{"type": "text", "text": {"content": "Acme tasks"}}], "initial_data_source": {"properties": {"Name": {"title": {}}, "Status": {"select": {"options": [{"name": "Todo"}, {"name": "Done"}]}}}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/databases",
    pathParams: [],
    query: {},
    body: {"parent": "parent", "title": "title", "is_inline": "is_inline", "initial_data_source": "initial_data_source", "database_type": "database_type"},
    headers: {},
  },
  cost: { per: "request" },
})

export const listViews = defineFunction({
  name: "notion.list_views",
  connector: "notion",
  class: "read",
  description: "List the views (tabs) of a database, by database id or by data source id, not both.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "database_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "data_source_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "start_cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    },
    "oneOf": [{"required": ["database_id"]}, {"required": ["data_source_id"]}]
  },
  examples: [
    { title: "Views of a database", input: {"database_id": "7a8b9c0d1e2f30417a8b9c0d1e2f3041"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/views",
    pathParams: [],
    query: {"database_id": "database_id", "data_source_id": "data_source_id", "page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const getView = defineFunction({
  name: "notion.get_view",
  connector: "notion",
  class: "read",
  description: "Get one database view: its type, filter, sorts and configuration.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["view_id"],
    "properties": {
      "view_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      }
    }
  },
  examples: [
    { title: "One view", input: {"view_id": "8b9c0d1e2f3041528b9c0d1e2f304152"} },
  ],
  refusals: [
    { code: "view_not_found", when: 404, message: "No view with this id shared with the integration." },
  ],
  request: {
    method: "GET",
    path: "/views/{view_id}",
    pathParams: ["view_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const createView = defineFunction({
  name: "notion.create_view",
  connector: "notion",
  class: "write",
  description: "Add a view (tab) to a database, on one of its data sources. filter and sorts take the same format as query_data_source; configuration holds type-specific settings (shown columns, group by) as get_view returns them.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["database_id", "data_source_id", "name", "type"],
    "properties": {
      "database_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "data_source_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "name": {"type": "string", "minLength": 1},
      "type": {
        "enum": ["table", "board", "list", "calendar", "timeline", "gallery", "form", "chart", "map", "dashboard"]
      },
      "filter": {"type": "object"},
      "sorts": {"type": "array", "items": {"type": "object"}},
      "configuration": {"type": "object"}
    }
  },
  examples: [
    { title: "A board of open tasks", input: {"database_id": "7a8b9c0d1e2f30417a8b9c0d1e2f3041", "data_source_id": "2a3b4c5d6e7f80912a3b4c5d6e7f8091", "name": "Open tasks", "type": "board", "filter": {"property": "Status", "select": {"does_not_equal": "Done"}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/views",
    pathParams: [],
    query: {},
    body: {"database_id": "database_id", "data_source_id": "data_source_id", "name": "name", "type": "type", "filter": "filter", "sorts": "sorts", "configuration": "configuration"},
    headers: {},
  },
  cost: { per: "request" },
})

export const updateView = defineFunction({
  name: "notion.update_view",
  connector: "notion",
  class: "write",
  description: "Change a view's name, filter, sorts or configuration. filter or sorts set to null resets them.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["view_id"],
    "minProperties": 2,
    "properties": {
      "view_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      },
      "name": {"type": "string", "minLength": 1},
      "filter": {"type": ["object", "null"]},
      "sorts": {"type": ["array", "null"], "items": {"type": "object"}},
      "configuration": {"type": "object"}
    }
  },
  examples: [
    { title: "Remove the filter of a view", input: {"view_id": "8b9c0d1e2f3041528b9c0d1e2f304152", "filter": null} },
  ],
  refusals: [],
  request: {
    method: "PATCH",
    path: "/views/{view_id}",
    pathParams: ["view_id"],
    query: {},
    body: {"name": "name", "filter": "filter", "sorts": "sorts", "configuration": "configuration"},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteView = defineFunction({
  name: "notion.delete_view",
  connector: "notion",
  class: "sensitive",
  description: "Delete a database view. The data is untouched; the last view of a database cannot be deleted.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["view_id"],
    "properties": {
      "view_id": {
        "type": "string",
        "pattern": "^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        "description": "Notion id: 32 hexadecimal characters, dashes allowed."
      }
    }
  },
  examples: [
    { title: "Delete one view", input: {"view_id": "8b9c0d1e2f3041528b9c0d1e2f304152"} },
  ],
  refusals: [],
  request: {
    method: "DELETE",
    path: "/views/{view_id}",
    pathParams: ["view_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Delete Notion view {view_id}." },
})

export const listUsers = defineFunction({
  name: "notion.list_users",
  connector: "notion",
  class: "read",
  description: "List the workspace members, guests and bots, one page at a time: their ids fill people properties and mentions.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "start_cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "First page of users", input: {"page_size": 100} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/users",
    pathParams: [],
    query: {"page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "notion",
  label: "Notion",
  namespace: "notion",
  version: "1.1.0",
  apiVersion: "2025-09-03",
  baseUrl: "https://api.notion.com/v1",
  auth: {"kind": "bearer", "token": "token"},
  credential: [{"name": "token", "label": "Integration token", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  headers: {"Notion-Version": "2025-09-03"},
  errors: [
    { status: 400, code: "invalid_request", message: "Notion rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Notion rejected the integration token: check that it is valid.", retryable: false },
    { status: 403, code: "permission_missing", message: "The integration lacks the capability for this action on this resource.", retryable: false },
    { status: 404, code: "not_found", message: "Notion object not found, or not shared with the integration.", retryable: false },
    { status: 409, code: "conflict", message: "Notion saw a conflicting edit: retry.", retryable: true },
    { status: 429, code: "rate_limited", message: "Notion request rate exceeded: retry later.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Notion is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "notion"},
  functions: [
    searchWorkspace,
    getPage,
    listBlockChildren,
    queryDataSource,
    createPage,
    updatePage,
    movePage,
    appendBlockChildren,
    deleteBlock,
    getPageMarkdown,
    editPageMarkdown,
    listComments,
    addComment,
    updateComment,
    deleteComment,
    createDatabase,
    listViews,
    getView,
    createView,
    updateView,
    deleteView,
    listUsers,
  ],
})
