// Generated by the fabrique from connectors/notion/connector.yaml. Do not edit: run `python -m fabrique`.
// Not generated:
// - notion.update_page: input: minProperties at the root needs a refinement
// - notion.edit_page_markdown: input: oneOf at the root needs a refinement
// - notion.add_comment: input: oneOf at the root needs a refinement
// - notion.create_database: input: not at the root needs a refinement
// - notion.list_views: input: oneOf at the root needs a refinement
// - notion.update_view: input: minProperties at the root needs a refinement
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const searchWorkspace = defineFunction({
  name: "notion.search_workspace",
  connector: "notion",
  class: "read",
  description: "Search the pages and databases shared with the integration, one page of results at a time (at most 100). The integration sees only what was shared with it in Notion: an empty result with an empty query and no filter means nothing is shared, not that the workspace is empty. Databases come back as data_source objects. Pass next_cursor as start_cursor to read the next page.",
  schema: z.strictObject({
    "query": z.string().describe("Text to match; empty lists everything the integration can see.").optional(),
    "filter": z.strictObject({
      "value": z.enum(["page", "data_source"]),
      "property": z.literal("object"),
    }).describe("Restrict to pages or to databases (data_source).").optional(),
    "sort": z.strictObject({
      "direction": z.enum(["ascending", "descending"]),
      "timestamp": z.literal("last_edited_time"),
    }).describe("Sort by last edit; omit for relevance.").optional(),
    "start_cursor": z.string().describe("next_cursor of the previous page.").optional(),
    "all_pages": z.boolean().describe("Read the following pages too, up to max_pages (at most 10).").optional(),
    "max_pages": z.int().gte(1).lte(10).meta({"description": "Pages read when all_pages is true.", "default": 10}).optional(),
  }),
  examples: [
    { title: "Pages about the roadmap, most recently edited first", input: {"query": "roadmap", "filter": {"value": "page", "property": "object"}, "sort": {"direction": "descending", "timestamp": "last_edited_time"}} },
    { title: "Everything shared with the integration", input: {"query": ""} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/search",
    pathParams: [],
    query: {},
    body: {"query": "query", "filter": "filter", "sort": "sort", "start_cursor": "start_cursor"},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const getPage = defineFunction({
  name: "notion.get_page",
  connector: "notion",
  class: "read",
  description: "Get a page's metadata and property values, not its content (see get_page_markdown or list_block_children for the content).",
  schema: z.strictObject({
    "page_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
  }),
  examples: [
    { title: "One page", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [
    { code: "page_not_found", when: 404, message: "No page with this id shared with the integration." },
  ],
  request: {
    method: "GET",
    path: "/pages/{page_id}",
    pathParams: ["page_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listBlockChildren = defineFunction({
  name: "notion.list_block_children",
  connector: "notion",
  class: "read",
  description: "List the blocks directly inside a page or a block, one level only, one page of results at a time. A block with has_children true is read the same way with its own id.",
  schema: z.strictObject({
    "block_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "page_size": z.int().gte(1).lte(100).meta({"default": 100}).optional(),
    "start_cursor": z.string().describe("next_cursor of the previous page.").optional(),
    "all_pages": z.boolean().describe("Read the following pages too, up to max_pages (at most 50).").optional(),
    "max_pages": z.int().gte(1).lte(50).meta({"description": "Pages read when all_pages is true.", "default": 50}).optional(),
  }),
  examples: [
    { title: "Top-level content of a page", input: {"block_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/blocks/{block_id}/children",
    pathParams: ["block_id"],
    query: {"page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", maxPages: 50 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const queryDataSource = defineFunction({
  name: "notion.query_data_source",
  connector: "notion",
  class: "read",
  description: "Query the rows of a database through its data source, one page at a time. Pass the data source id that search_workspace returns for a database, not the database id.",
  schema: z.strictObject({
    "data_source_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "filter": z.looseObject({}).describe("Notion filter object, e.g. {\"property\": \"Status\", \"select\": {\"equals\": \"Done\"}}.").optional(),
    "sorts": z.array(z.looseObject({})).describe("Notion sorts, e.g. [{\"property\": \"Due\", \"direction\": \"ascending\"}].").optional(),
    "page_size": z.int().gte(1).lte(100).meta({"default": 100}).optional(),
    "start_cursor": z.string().describe("next_cursor of the previous page.").optional(),
    "all_pages": z.boolean().describe("Read the following pages too, up to max_pages (at most 10).").optional(),
    "max_pages": z.int().gte(1).lte(10).meta({"description": "Pages read when all_pages is true.", "default": 10}).optional(),
  }),
  examples: [
    { title: "Rows whose status is Done", input: {"data_source_id": "2a3b4c5d6e7f80912a3b4c5d6e7f8091", "filter": {"property": "Status", "select": {"equals": "Done"}}, "page_size": 50} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/data_sources/{data_source_id}/query",
    pathParams: ["data_source_id"],
    query: {},
    body: {"filter": "filter", "sorts": "sorts", "page_size": "page_size", "start_cursor": "start_cursor"},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const createPage = defineFunction({
  name: "notion.create_page",
  connector: "notion",
  class: "write",
  description: "Create a page under a page, or a row in a database through its data source. For a row, properties are keyed by column name and must set the title column (whatever its name). children holds at most 100 blocks; add more with append_block_children.",
  schema: z.strictObject({
    "parent": z.union([z.strictObject({
      "page_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    }), z.strictObject({
      "type": z.literal("data_source_id"),
      "data_source_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    })]).describe("{page_id} for a sub-page, {type: data_source_id, data_source_id} for a database row."),
    "properties": z.looseObject({}).describe("Property values. Under a page: {\"title\": {\"title\": [{\"text\": {\"content\": \"...\"}}]}}. In a database: keyed by column name."),
    "children": z.array(z.looseObject({})).min(1).max(100).describe("Notion block objects, at most 100.").optional(),
  }),
  examples: [
    { title: "A sub-page with one paragraph", input: {"parent": {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"}, "properties": {"title": {"title": [{"text": {"content": "Meeting notes"}}]}}, "children": [{"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": "Agenda"}}]}}]} },
    { title: "A row in a task database", input: {"parent": {"type": "data_source_id", "data_source_id": "2a3b4c5d6e7f80912a3b4c5d6e7f8091"}, "properties": {"Name": {"title": [{"text": {"content": "Call Acme"}}]}, "Status": {"select": {"name": "Todo"}}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/pages",
    pathParams: [],
    query: {},
    body: {"parent": "parent", "properties": "properties", "children": "children"},
    headers: {},
  },
  cost: { per: "request" },
})

export const movePage = defineFunction({
  name: "notion.move_page",
  connector: "notion",
  class: "write",
  description: "Move a page under another page, or into a database through its data source.",
  schema: z.strictObject({
    "page_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "parent": z.union([z.strictObject({
      "type": z.literal("page_id"),
      "page_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    }), z.strictObject({
      "type": z.literal("data_source_id"),
      "data_source_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    })]),
  }),
  examples: [
    { title: "Move a page under another page", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "parent": {"type": "page_id", "page_id": "3c4d5e6f7a8b9c0d3c4d5e6f7a8b9c0d"}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/pages/{page_id}/move",
    pathParams: ["page_id"],
    query: {},
    body: {"parent": "parent"},
    headers: {},
  },
  cost: { per: "request" },
})

export const appendBlockChildren = defineFunction({
  name: "notion.append_block_children",
  connector: "notion",
  class: "write",
  description: "Add at most 100 blocks inside a page or a block: at the end (default), at the start, or right after an existing child block.",
  schema: z.strictObject({
    "block_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "children": z.array(z.looseObject({})).min(1).max(100).describe("Notion block objects, at most 100."),
    "position": z.union([z.strictObject({
      "type": z.enum(["start", "end"]),
    }), z.strictObject({
      "type": z.literal("after_block"),
      "after_block": z.strictObject({
        "id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
      }),
    })]).describe("{type: start|end}, or {type: after_block, after_block: {id}}.").optional(),
  }),
  examples: [
    { title: "A to-do at the top of a page", input: {"block_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988", "children": [{"object": "block", "type": "to_do", "to_do": {"rich_text": [{"type": "text", "text": {"content": "Send the quote to Acme"}}], "checked": false}}], "position": {"type": "start"}} },
  ],
  refusals: [],
  request: {
    method: "PATCH",
    path: "/blocks/{block_id}/children",
    pathParams: ["block_id"],
    query: {},
    body: {"children": "children", "position": "position"},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteBlock = defineFunction({
  name: "notion.delete_block",
  connector: "notion",
  class: "sensitive",
  description: "Move one block to the trash, with its children. It can be restored from Notion until the trash is emptied.",
  schema: z.strictObject({
    "block_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
  }),
  examples: [
    { title: "Delete one block", input: {"block_id": "4d5e6f7a8b9c0d1e4d5e6f7a8b9c0d1e"} },
  ],
  refusals: [
    { code: "block_not_found", when: 404, message: "No block with this id shared with the integration." },
  ],
  request: {
    method: "DELETE",
    path: "/blocks/{block_id}",
    pathParams: ["block_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Move Notion block {block_id} and its children to the trash." },
})

export const getPageMarkdown = defineFunction({
  name: "notion.get_page_markdown",
  connector: "notion",
  class: "read",
  description: "Get a page's whole content as Notion-flavoured Markdown, lighter than reading blocks. truncated true with unknown_block_ids: some parts were not loaded (very large page, or child pages not shared); each id can be read the same way.",
  schema: z.strictObject({
    "page_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
  }),
  examples: [
    { title: "One page as Markdown", input: {"page_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [
    { code: "page_not_found", when: 404, message: "No page with this id shared with the integration." },
  ],
  request: {
    method: "GET",
    path: "/pages/{page_id}/markdown",
    pathParams: ["page_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listComments = defineFunction({
  name: "notion.list_comments",
  connector: "notion",
  class: "read",
  description: "List the open (unresolved) comments on a page or a block, one page at a time. Each comment carries its discussion_id, to reply in the thread with add_comment. The integration needs the read comments capability, off by default in Notion.",
  schema: z.strictObject({
    "block_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "page_size": z.int().gte(1).lte(100).meta({"default": 100}).optional(),
    "start_cursor": z.string().describe("next_cursor of the previous page.").optional(),
    "all_pages": z.boolean().describe("Read the following pages too, up to max_pages (at most 10).").optional(),
    "max_pages": z.int().gte(1).lte(10).meta({"description": "Pages read when all_pages is true.", "default": 10}).optional(),
  }),
  examples: [
    { title: "Comments on a page", input: {"block_id": "1f2e3d4c5b6a79881f2e3d4c5b6a7988"} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Reading comments is a capability turned off by default: turn it on in the integration's settings." },
  ],
  request: {
    method: "GET",
    path: "/comments",
    pathParams: [],
    query: {"block_id": "block_id", "page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const updateComment = defineFunction({
  name: "notion.update_comment",
  connector: "notion",
  class: "write",
  description: "Rewrite a comment the integration wrote. text is Markdown, inline formatting only.",
  schema: z.strictObject({
    "comment_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "text": z.string().min(1),
  }),
  examples: [
    { title: "Rewrite a comment", input: {"comment_id": "6f7a8b9c0d1e2f306f7a8b9c0d1e2f30", "text": "Validated with **Acme** on Monday."} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Editing comments needs the comment capabilities, turned off by default: turn them on in the integration's settings." },
  ],
  request: {
    method: "PATCH",
    path: "/comments/{comment_id}",
    pathParams: ["comment_id"],
    query: {},
    body: {"markdown": "text"},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteComment = defineFunction({
  name: "notion.delete_comment",
  connector: "notion",
  class: "sensitive",
  description: "Delete a comment the integration wrote.",
  schema: z.strictObject({
    "comment_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
  }),
  examples: [
    { title: "Delete a comment", input: {"comment_id": "6f7a8b9c0d1e2f306f7a8b9c0d1e2f30"} },
  ],
  refusals: [
    { code: "comments_capability_missing", when: 403, message: "Deleting comments needs the comment capabilities, turned off by default: turn them on in the integration's settings." },
  ],
  request: {
    method: "DELETE",
    path: "/comments/{comment_id}",
    pathParams: ["comment_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Delete Notion comment {comment_id}." },
})

export const getView = defineFunction({
  name: "notion.get_view",
  connector: "notion",
  class: "read",
  description: "Get one database view: its type, filter, sorts and configuration.",
  schema: z.strictObject({
    "view_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
  }),
  examples: [
    { title: "One view", input: {"view_id": "8b9c0d1e2f3041528b9c0d1e2f304152"} },
  ],
  refusals: [
    { code: "view_not_found", when: 404, message: "No view with this id shared with the integration." },
  ],
  request: {
    method: "GET",
    path: "/views/{view_id}",
    pathParams: ["view_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const createView = defineFunction({
  name: "notion.create_view",
  connector: "notion",
  class: "write",
  description: "Add a view (tab) to a database, on one of its data sources. filter and sorts take the same format as query_data_source; configuration holds type-specific settings (shown columns, group by) as get_view returns them.",
  schema: z.strictObject({
    "database_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "data_source_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
    "name": z.string().min(1),
    "type": z.enum(["table", "board", "list", "calendar", "timeline", "gallery", "form", "chart", "map", "dashboard"]),
    "filter": z.looseObject({}).optional(),
    "sorts": z.array(z.looseObject({})).optional(),
    "configuration": z.looseObject({}).optional(),
  }),
  examples: [
    { title: "A board of open tasks", input: {"database_id": "7a8b9c0d1e2f30417a8b9c0d1e2f3041", "data_source_id": "2a3b4c5d6e7f80912a3b4c5d6e7f8091", "name": "Open tasks", "type": "board", "filter": {"property": "Status", "select": {"does_not_equal": "Done"}}} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/views",
    pathParams: [],
    query: {},
    body: {"database_id": "database_id", "data_source_id": "data_source_id", "name": "name", "type": "type", "filter": "filter", "sorts": "sorts", "configuration": "configuration"},
    headers: {},
  },
  cost: { per: "request" },
})

export const deleteView = defineFunction({
  name: "notion.delete_view",
  connector: "notion",
  class: "sensitive",
  description: "Delete a database view. The data is untouched; the last view of a database cannot be deleted.",
  schema: z.strictObject({
    "view_id": z.string().regex(new RegExp("^([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$")).describe("Notion id: 32 hexadecimal characters, dashes allowed."),
  }),
  examples: [
    { title: "Delete one view", input: {"view_id": "8b9c0d1e2f3041528b9c0d1e2f304152"} },
  ],
  refusals: [],
  request: {
    method: "DELETE",
    path: "/views/{view_id}",
    pathParams: ["view_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
  confirm: { summary: "Delete Notion view {view_id}." },
})

export const listUsers = defineFunction({
  name: "notion.list_users",
  connector: "notion",
  class: "read",
  description: "List the workspace members, guests and bots, one page at a time: their ids fill people properties and mentions.",
  schema: z.strictObject({
    "page_size": z.int().gte(1).lte(100).meta({"default": 100}).optional(),
    "start_cursor": z.string().describe("next_cursor of the previous page.").optional(),
    "all_pages": z.boolean().describe("Read the following pages too, up to max_pages (at most 10).").optional(),
    "max_pages": z.int().gte(1).lte(10).meta({"description": "Pages read when all_pages is true.", "default": 10}).optional(),
  }),
  examples: [
    { title: "First page of users", input: {"page_size": 100} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/users",
    pathParams: [],
    query: {"page_size": "page_size", "start_cursor": "start_cursor"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "start_cursor", next: "next_cursor", maxPages: 10 },
  output: { items: "results" },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "notion",
  label: "Notion",
  namespace: "notion",
  version: "1.0.0",
  apiVersion: "2025-09-03",
  baseUrl: "https://api.notion.com/v1",
  auth: {"kind": "bearer", "token": "token"},
  credential: [{"name": "token", "label": "Integration token", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  errors: [
    { status: 400, code: "invalid_request", message: "Notion rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Notion rejected the integration token: check that it is valid.", retryable: false },
    { status: 403, code: "permission_missing", message: "The integration lacks the capability for this action on this resource.", retryable: false },
    { status: 404, code: "not_found", message: "Notion object not found, or not shared with the integration.", retryable: false },
    { status: 409, code: "conflict", message: "Notion saw a conflicting edit: retry.", retryable: true },
    { status: 429, code: "rate_limited", message: "Notion request rate exceeded: retry later.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Notion is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "notion"},
  functions: [
    searchWorkspace,
    getPage,
    listBlockChildren,
    queryDataSource,
    createPage,
    movePage,
    appendBlockChildren,
    deleteBlock,
    getPageMarkdown,
    listComments,
    updateComment,
    deleteComment,
    getView,
    createView,
    deleteView,
    listUsers,
  ],
})
