// Generated by the fabrique from connectors/pennylane_firm/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const listCompanies = defineFunction({
  name: "pennylane_firm.list_companies",
  connector: "pennylane_firm",
  class: "read",
  description: "List the companies of the firm the token belongs to: id, name, billing_company_name, siren, address, city, postal_code, activity_nomenclature, activity_code, external_id, client_code. The id is the company_id every other function takes; it is the firm-side id and means nothing to the Company API. Paged by page number: the response carries current_page, total_pages, total_items and per_page; ask for page + 1 while it is below total_pages. Scope companies:readonly.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "page": {"type": "integer", "minimum": 1, "default": 1, "description": "Page number, starting at 1."},
      "per_page": {"type": "integer", "minimum": 1, "maximum": 1000, "default": 20},
      "filter": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": ["field", "operator", "value"],
          "properties": {
            "field": {"enum": ["client_code"]},
            "operator": {"enum": ["eq", "not_eq", "in", "not_in"]},
            "value": {"type": ["string", "integer", "array"], "items": {"type": ["string", "integer"]}}
          },
          "allOf": [
            {
              "if": {"properties": {"operator": {"enum": ["in", "not_in"]}}},
              "then": {"properties": {"value": {"type": "array", "minItems": 1}}},
              "else": {"properties": {"value": {"type": ["string", "integer"]}}}
            }
          ]
        },
        "description": "Clauses that must all hold, each {field, operator, value}; in and not_in take a list. Field: client_code (eq, not_eq, in, not_in)."
      }
    }
  },
  examples: [
    { title: "Every company of the firm, in one page", input: {"per_page": 1000} },
    { title: "The company with client code 0042", input: {"filter": [{"field": "client_code", "operator": "eq", "value": "0042"}]} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/companies",
    pathParams: [],
    query: {"page": "page", "per_page": "per_page", "filter": "filter"},
    body: {},
    headers: {},
    encode: {"filter": "json"},
  },
  cost: { per: "request" },
})

export const getCompany = defineFunction({
  name: "pennylane_firm.get_company",
  connector: "pennylane_firm",
  class: "read",
  description: "Get one company of the firm by its firm-side id (from list_companies): name, billing_company_name, siren, address, activity codes, external_id, client_code. Scope companies:readonly.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id"],
    "properties": {
      "company_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Firm-side company id, from list_companies. Not a Company API id."
      }
    }
  },
  examples: [
    { title: "One company", input: {"company_id": 1234} },
  ],
  refusals: [
    { code: "company_not_found", when: 404, message: "No company with this id in the firm: read the ids from the list of companies." },
  ],
  request: {
    method: "GET",
    path: "/companies/{company_id}",
    pathParams: ["company_id"],
    query: {},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listFiscalYears = defineFunction({
  name: "pennylane_firm.list_fiscal_years",
  connector: "pennylane_firm",
  class: "read",
  description: "List the fiscal years of one company: id, start, finish (YYYY-MM-DD) and status (open, reopen, closed, frozen). Paged by page number, up to 100 per page: the response carries current_page and total_pages. Scope fiscal_years:readonly.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id"],
    "properties": {
      "company_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Firm-side company id, from list_companies. Not a Company API id."
      },
      "page": {"type": "integer", "minimum": 1, "default": 1, "description": "Page number, starting at 1."},
      "per_page": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20}
    }
  },
  examples: [
    { title: "All fiscal years of a company", input: {"company_id": 1234, "per_page": 100} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/companies/{company_id}/fiscal_years",
    pathParams: ["company_id"],
    query: {"page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listDmsFolders = defineFunction({
  name: "pennylane_firm.list_dms_folders",
  connector: "pennylane_firm",
  class: "read",
  description: "List the folders of one company's DMS: id, name, path (full path from the root, e.g. /Annual/2018/FEC), parent_folder ({id}, or null at the root), files.url, created_at, updated_at. The tree is rebuilt from parent_folder or path. Paged by limit and cursor: pass next_cursor as cursor for the next page. Folders cannot be renamed, moved or deleted through the API. Scope dms_files:readonly.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id"],
    "properties": {
      "company_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Firm-side company id, from list_companies. Not a Company API id."
      },
      "filter": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": ["field", "operator", "value"],
          "properties": {
            "field": {"enum": ["id"]},
            "operator": {"enum": ["lt", "lteq", "gt", "gteq", "eq", "not_eq", "in", "not_in"]},
            "value": {"type": ["string", "integer", "array"], "items": {"type": ["string", "integer"]}}
          },
          "allOf": [
            {
              "if": {"properties": {"operator": {"enum": ["in", "not_in"]}}},
              "then": {"properties": {"value": {"type": "array", "minItems": 1}}},
              "else": {"properties": {"value": {"type": ["string", "integer"]}}}
            }
          ]
        },
        "description": "Clauses that must all hold, each {field, operator, value}; in and not_in take a list. Field: id (lt, lteq, gt, gteq, eq, not_eq, in, not_in)."
      },
      "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "The whole folder tree of a company", input: {"company_id": 1234} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/companies/{company_id}/dms/folders",
    pathParams: ["company_id"],
    query: {"filter": "filter", "limit": "limit", "cursor": "cursor"},
    body: {},
    headers: {},
    encode: {"filter": "json"},
  },
  pagination: { kind: "cursor", requestParam: "cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "items" },
  cost: { per: "request" },
})

export const listDmsFiles = defineFunction({
  name: "pennylane_firm.list_dms_files",
  connector: "pennylane_firm",
  class: "read",
  description: "List the files of one company's DMS: id, name, path (full path, folders included), parent_folder ({id}, or null at the root), url (to download the file), created_at, updated_at. Filter on parent_folder_id to list one folder. There is no single-file read: filter on id instead. Files cannot be renamed, moved or deleted through the API. Paged by limit and cursor: pass next_cursor as cursor for the next page. Scope dms_files:readonly.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id"],
    "properties": {
      "company_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Firm-side company id, from list_companies. Not a Company API id."
      },
      "filter": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": ["field", "operator", "value"],
          "properties": {
            "field": {"enum": ["id", "parent_folder_id"]},
            "operator": {"enum": ["lt", "lteq", "gt", "gteq", "eq", "not_eq", "in", "not_in"]},
            "value": {"type": ["string", "integer", "array"], "items": {"type": ["string", "integer"]}}
          },
          "allOf": [
            {
              "if": {"properties": {"operator": {"enum": ["in", "not_in"]}}},
              "then": {"properties": {"value": {"type": "array", "minItems": 1}}},
              "else": {"properties": {"value": {"type": ["string", "integer"]}}}
            }
          ]
        },
        "description": "Clauses that must all hold, each {field, operator, value}; in and not_in take a list. Fields: id and parent_folder_id (lt, lteq, gt, gteq, eq, not_eq, in, not_in)."
      },
      "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 100},
      "cursor": {"type": "string", "description": "next_cursor of the previous page."},
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "Files of one folder", input: {"company_id": 1234, "filter": [{"field": "parent_folder_id", "operator": "eq", "value": 567}]} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/companies/{company_id}/dms/files",
    pathParams: ["company_id"],
    query: {"filter": "filter", "limit": "limit", "cursor": "cursor"},
    body: {},
    headers: {},
    encode: {"filter": "json"},
  },
  pagination: { kind: "cursor", requestParam: "cursor", next: "next_cursor", more: "has_more", maxPages: 10 },
  output: { items: "items" },
  cost: { per: "request" },
})

export const createDmsFolder = defineFunction({
  name: "pennylane_firm.create_dms_folder",
  connector: "pennylane_firm",
  class: "write",
  description: "Create a folder in one company's DMS, at the root or under parent_folder_id. Returns the folder with its id and full path. A folder cannot be renamed, moved or deleted through the API afterwards: list the folders first and reuse an existing one rather than creating a duplicate. Scope dms_files:all.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id", "name"],
    "properties": {
      "company_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Firm-side company id, from list_companies. Not a Company API id."
      },
      "name": {"type": "string", "minLength": 1, "description": "Folder name."},
      "parent_folder_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Parent folder id; the folder goes at the root without it."
      }
    }
  },
  examples: [
    { title: "A folder under an existing one", input: {"company_id": 1234, "name": "2026", "parent_folder_id": 567} },
  ],
  refusals: [
    { code: "folder_rejected", when: 422, message: "Pennylane refused to create this folder: check the name and the parent folder." },
  ],
  request: {
    method: "POST",
    path: "/companies/{company_id}/dms/folders",
    pathParams: ["company_id"],
    query: {},
    body: {"name": "name", "parent_folder_id": "parent_folder_id"},
    headers: {},
  },
  cost: { per: "request" },
})

export const listDmsFileChanges = defineFunction({
  name: "pennylane_firm.list_dms_file_changes",
  connector: "pennylane_firm",
  class: "read",
  description: "List the changes to one company's DMS files, oldest first: id (of the file), operation (insert, update, delete), processed_at, updated_at, created_at. Start from start_date (RFC 3339), or from the oldest change kept without it; changes are kept four weeks, and an older start_date is refused. Then pass next_cursor as cursor, without start_date, while has_more is true. Up to 1000 changes per page. Scope dms_files:readonly.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["company_id"],
    "not": {"required": ["start_date", "cursor"]},
    "properties": {
      "company_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Firm-side company id, from list_companies. Not a Company API id."
      },
      "start_date": {
        "type": "string",
        "format": "date-time",
        "description": "RFC 3339, within the last four weeks. Never with cursor."
      },
      "cursor": {"type": "string", "description": "next_cursor of the previous page. Never with start_date."},
      "limit": {"type": "integer", "minimum": 1, "maximum": 1000, "default": 1000}
    }
  },
  examples: [
    { title: "Changes since a given time", input: {"company_id": 1234, "start_date": "2026-10-01T00:00:00Z"} },
  ],
  refusals: [
    { code: "start_date_too_old", when: 422, message: "Pennylane keeps DMS file changes four weeks only: pick a start_date within that window." },
  ],
  request: {
    method: "GET",
    path: "/companies/{company_id}/changelogs/dms_files",
    pathParams: ["company_id"],
    query: {"start_date": "start_date", "cursor": "cursor", "limit": "limit"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "pennylane_firm",
  label: "Pennylane (firm)",
  namespace: "pennylane_firm",
  version: "1.0.0",
  apiVersion: "v1",
  baseUrl: "https://app.pennylane.com/api/external/firm/v1",
  auth: {"kind": "bearer", "token": "token"},
  credential: [{"name": "token", "label": "Firm API token", "secret": true}],
  modes: ["byo_org"],
  timeoutMs: 30000,
  rateLimit: { requests: 5, intervalMs: 1000 },
  errors: [
    { status: 400, code: "invalid_request", message: "Pennylane rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "token_invalid", message: "Pennylane refused the firm token as invalid: a valid token is needed, and retrying unchanged fails the same way.", retryable: false },
    { status: 403, code: "scope_missing", message: "The firm token lacks the scope this action requires; Pennylane names it in its message. A missing right is not an argument to fix: tell the user which scope the token needs.", retryable: false },
    { status: 404, code: "not_found", message: "No such object for this firm: company_id is the firm-side id from the list of companies, and folder or file ids belong to that one company.", retryable: false },
    { status: 422, code: "content_rejected", message: "Pennylane rejected the content: the values sent fail its checks. Fix them before calling again.", retryable: false },
    { status: 429, code: "rate_limited", message: "Pennylane request rate exceeded (5 requests per second): wait about a minute before retrying.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Pennylane is temporarily unavailable: retry later.", retryable: true },
  ],
  probe: { function: "pennylane_firm.list_companies", nonEmpty: [] },
  functions: [
    listCompanies,
    getCompany,
    listFiscalYears,
    listDmsFolders,
    listDmsFiles,
    createDmsFolder,
    listDmsFileChanges,
  ],
})
