// Generated by the fabrique from connectors/sellsy/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const listEstimates = defineFunction({
  name: "sellsy.list_estimates",
  connector: "sellsy",
  class: "read",
  description: "List Sellsy estimates (quotes), one page at a time. Pass the returned pagination.offset as offset to get the next page.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 25},
      "offset": {"type": "string", "description": "Cursor from the previous page."},
      "order": {
        "type": "string",
        "enum": ["id", "created", "date", "expiry_date", "number", "amount"],
        "description": "Field to sort by."
      },
      "direction": {"type": "string", "enum": ["asc", "desc"], "default": "asc"},
      "fields": {
        "type": "array",
        "items": {"type": "string", "pattern": "^[A-Za-z0-9.\\[\\]_-]+$"},
        "description": "Fields to return, e.g. id, number, related[].id. With embed, also request _embed (all embeds) or _embed.<name>."
      },
      "embed": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "enum": [
                "company",
                "individual",
                "contact",
                "invoicing_address",
                "delivery_address",
                "issuer_address",
                "currency",
                "acl",
                "payment_method_ids",
                "aggregations",
                "aggregations.amount_sum_by_status",
                "aggregations.count_by_status",
                "fiscal_year",
                "smart_tags",
                "payment_terms",
                "settings"
              ]
            },
            {"type": "string", "pattern": "^cf\\.[0-9]+$"}
          ]
        },
        "description": "Related objects to include. cf.<id> includes a custom field value. An embed whose OAuth2 scope the access lacks comes back null."
      },
      "all_pages": {"type": "boolean", "description": "Read the following pages too, up to max_pages (at most 10)."},
      "max_pages": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 10,
        "description": "Pages read when all_pages is true."
      }
    }
  },
  examples: [
    { title: "First page, id and number only", input: {"limit": 25, "fields": ["id", "number"]} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/estimates",
    pathParams: [],
    query: {"limit": "limit", "offset": "offset", "order": "order", "direction": "direction", "field": "fields", "embed": "embed"},
    body: {},
    headers: {},
  },
  pagination: { kind: "cursor", requestParam: "offset", next: "pagination.offset", total: "pagination.total", maxPages: 10 },
  output: { items: "data", schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "number": {"type": "string"}, "created": {"type": "string", "format": "date-time"}, "date": {"type": "string", "format": "date"}, "expiry_date": {"type": "string", "format": "date"}, "amount": {"type": "number"}}} },
  cost: { per: "request" },
})

export const getEstimate = defineFunction({
  name: "sellsy.get_estimate",
  connector: "sellsy",
  class: "read",
  description: "Get the full record of one Sellsy estimate by its id.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["id"],
    "properties": {
      "id": {"type": "integer"},
      "fields": {
        "type": "array",
        "items": {"type": "string", "pattern": "^[A-Za-z0-9.\\[\\]_-]+$"},
        "description": "Fields to return, e.g. id, number, related[].id. With embed, also request _embed (all embeds) or _embed.<name>."
      },
      "embed": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "enum": [
                "company",
                "individual",
                "contact",
                "invoicing_address",
                "delivery_address",
                "issuer_address",
                "currency",
                "acl",
                "payment_method_ids",
                "aggregations",
                "aggregations.amount_sum_by_status",
                "aggregations.count_by_status",
                "fiscal_year",
                "smart_tags",
                "payment_terms",
                "discount_incl_taxes",
                "settings",
                "file"
              ]
            },
            {"type": "string", "pattern": "^cf\\.[0-9]+$"}
          ]
        },
        "description": "Related objects to include. cf.<id> includes a custom field value. An embed whose OAuth2 scope the access lacks comes back null."
      }
    }
  },
  examples: [
    { title: "One estimate with its company", input: {"id": 42, "embed": ["company"]} },
  ],
  refusals: [
    { code: "estimate_not_found", when: 404, message: "No estimate with this id in this Sellsy account." },
  ],
  request: {
    method: "GET",
    path: "/estimates/{id}",
    pathParams: ["id"],
    query: {"field": "fields", "embed": "embed"},
    body: {},
    headers: {},
  },
  output: { schema: {"type": "object", "additionalProperties": false, "properties": {"id": {"type": "integer"}, "number": {"type": "string"}, "created": {"type": "string", "format": "date-time"}, "date": {"type": "string", "format": "date"}, "expiry_date": {"type": "string", "format": "date"}, "amount": {"type": "number"}}} },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "sellsy",
  label: "Sellsy",
  namespace: "sellsy",
  version: "1.0.0",
  apiVersion: "v2",
  baseUrl: "https://api.sellsy.com/v2",
  auth: {"kind": "oauth2_client_credentials", "tokenUrl": "https://login.sellsy.com/oauth2/access-tokens", "tokenRequest": "json", "clientId": "client_id", "clientSecret": "client_secret", "expiresInDefault": 3600},
  credential: [{"name": "client_id", "label": "Client ID", "secret": true}, {"name": "client_secret", "label": "Client Secret", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 30000,
  queryArrays: "brackets",
  errors: [
    { status: 400, code: "invalid_request", message: "Sellsy rejected the request as invalid: check the arguments.", retryable: false },
    { status: [401, 403], code: "access_rejected", message: "Sellsy rejected the access: check client_id, client_secret and API scopes.", retryable: false },
    { status: 402, code: "plan_quota_reached", message: "Sellsy plan quota reached for this resource.", retryable: false },
    { status: 404, code: "not_found", message: "Sellsy object not found: check the id.", retryable: false },
    { status: 409, code: "conflict", message: "Conflict with the current state of the Sellsy object.", retryable: false },
    { status: 429, code: "rate_limited", message: "Sellsy request quota exhausted: retry later or reduce paging.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Sellsy is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "sellsy"},
  functions: [
    listEstimates,
    getEstimate,
  ],
})
