// Generated by the fabrique from connectors/typeform/connector.yaml. Do not edit: run `python -m fabrique`.
// Not generated:
// - typeform.get_form: input.form_id: not needs a refinement
// - typeform.list_responses: input.form_id: not needs a refinement
import * as z from "zod/v4"
import { defineConnector, defineFunction } from "./types"

export const listWorkspaces = defineFunction({
  name: "typeform.list_workspaces",
  connector: "typeform",
  class: "read",
  description: "List the Typeform workspaces the token can access, across organizations: {total_items, page_count, items: [{id, name, account_id, shared, forms: {count, href}}]}. The id filters list_forms. Needs the workspaces:read scope.",
  schema: z.strictObject({
    "search": z.string().min(1).describe("Only workspaces containing this text.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "page_size": z.int().gte(1).lte(200).meta({"default": 10}).optional(),
  }),
  examples: [
    { title: "Workspaces whose name contains Sales", input: {"search": "Sales"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/workspaces",
    pathParams: [],
    query: {"search": "search", "page": "page", "page_size": "page_size"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const listForms = defineFunction({
  name: "typeform.list_forms",
  connector: "typeform",
  class: "read",
  description: "List the forms of the Typeform account, public and private: {total_items, page_count, items: [{id, title, created_at, last_updated_at, settings: {is_public}, _links: {display, responses}}]}. Needs the forms:read scope.",
  schema: z.strictObject({
    "search": z.string().min(1).describe("Only forms containing this text.").optional(),
    "workspace_id": z.string().min(1).describe("Only the forms of this workspace.").optional(),
    "sort_by": z.enum(["created_at", "last_updated_at"]).optional(),
    "order_by": z.enum(["asc", "desc"]).optional(),
    "is_public": z.boolean().describe("Filter on settings.is_public.").optional(),
    "page": z.int().gte(1).describe("Page number, from 1.").optional(),
    "page_size": z.int().gte(1).lte(200).meta({"default": 10}).optional(),
  }),
  examples: [
    { title: "Latest updated forms of one workspace", input: {"workspace_id": "aBcD12", "sort_by": "last_updated_at", "order_by": "desc"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/forms",
    pathParams: [],
    query: {"search": "search", "workspace_id": "workspace_id", "sort_by": "sort_by", "order_by": "order_by", "is_public": "is_public", "page": "page", "page_size": "page_size"},
    body: {},
    headers: {},
  },
  cost: { per: "request" },
})

export const connector = defineConnector({
  name: "typeform",
  label: "Typeform",
  namespace: "typeform",
  version: "1.0.0",
  apiVersion: "Create API and Responses API (unversioned)",
  baseUrl: "https://api.typeform.com",
  auth: {"kind": "bearer", "token": "access_token"},
  credential: [{"name": "access_token", "label": "Personal access token", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  queryArrays: "comma",
  errors: [
    { status: 400, code: "invalid_request", message: "Typeform rejected the request as invalid: check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Typeform rejected the token: unknown, revoked, or issued by another data center.", retryable: false },
    { status: 403, code: "scope_missing", message: "The Typeform token lacks the read scope this call needs.", retryable: false },
    { status: 404, code: "not_found", message: "Typeform object not found: check the id.", retryable: false },
    { status: 429, code: "rate_limited", message: "Typeform rate limit reached: retry later.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Typeform is temporarily unavailable: retry later.", retryable: true },
  ],
  exposure: {"mode": "per_connector", "tool": "typeform"},
  functions: [
    listWorkspaces,
    listForms,
  ],
})
