// Generated by the fabrique from connectors/wttj_ats/connector.yaml. Do not edit: run `python -m fabrique`.
import { defineConnector, defineFunction } from "./types"

export const getCurrentUser = defineFunction({
  name: "wttj_ats.get_current_user",
  connector: "wttj_ats",
  class: "read",
  description: "Get the user the API token acts as, and on request the organizations, jobs and pipeline stages it can reach. Start here: every other call needs an organization reference or a job reference, and this is where they are listed. Needs the me_r scope; organizations need organizations_r, jobs need jobs_r.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "organizations": {
        "type": "boolean",
        "description": "Include the organizations the token can reach, with their reference."
      },
      "jobs": {"type": "boolean", "description": "Include the jobs of these organizations."},
      "stages": {"type": "boolean", "description": "Include the pipeline stages of these jobs."}
    }
  },
  examples: [
    { title: "The token's user and its organizations", input: {"organizations": true} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/users/current",
    pathParams: [],
    query: {"organizations": "organizations", "jobs": "jobs", "stages": "stages"},
    body: {},
    headers: {},
  },
})

export const getOrganization = defineFunction({
  name: "wttj_ats.get_organization",
  connector: "wttj_ats",
  class: "read",
  description: "Get one organization by its reference: name, slug, description, subsidiaries, logo, sectors, size. Offices and websites on request. Needs the organizations_r scope (offices also need offices_r).",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["reference"],
    "properties": {
      "reference": {"type": "string", "minLength": 1, "description": "Organization reference, from get_current_user."},
      "offices": {"type": "boolean", "description": "Include the organization's offices."},
      "websites": {"type": "boolean", "description": "Include the websites linked to the organization."}
    }
  },
  examples: [
    { title: "One organization with its offices", input: {"reference": "Ab12Cd3", "offices": true} },
  ],
  refusals: [
    { code: "organization_not_found", when: 404, message: "No organization with this reference is reachable with this token." },
  ],
  request: {
    method: "GET",
    path: "/organizations/{reference}",
    pathParams: ["reference"],
    query: {"offices": "offices", "websites": "websites"},
    body: {},
    headers: {},
  },
})

export const listJobs = defineFunction({
  name: "wttj_ats.list_jobs",
  connector: "wttj_ats",
  class: "read",
  description: "List the jobs (offers) of one organization, one page at a time: reference, name, status, description, profile, contract type, salary, remote policy, office, creation and publication dates. The answer is a bare array with no total: an empty or short page means the end. Needs the jobs_r scope.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["organization_reference"],
    "properties": {
      "organization_reference": {"type": "string", "minLength": 1},
      "status": {"type": "string", "enum": ["draft", "published", "archived"]},
      "office": {"type": "boolean", "description": "Embed the office of each job."},
      "stages": {"type": "boolean", "description": "Embed the pipeline stages of each job."},
      "websites": {"type": "boolean", "description": "Embed the websites where each job is visible."},
      "created_after": {"type": "string", "format": "date", "description": "YYYY-MM-DD."},
      "updated_after": {"type": "string", "format": "date", "description": "YYYY-MM-DD."},
      "published_after": {"type": "string", "format": "date", "description": "YYYY-MM-DD."},
      "page": {"type": "integer", "minimum": 1, "description": "1-based page number."},
      "per_page": {
        "type": "integer",
        "minimum": 1,
        "description": "Jobs per page; the API states neither a default nor a maximum."
      }
    }
  },
  examples: [
    { title: "Published jobs of one organization", input: {"organization_reference": "Ab12Cd3", "status": "published", "page": 1} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/jobs",
    pathParams: [],
    query: {"organization_reference": "organization_reference", "status": "status", "office": "office", "stages": "stages", "websites": "websites", "created_after": "created_after", "updated_after": "updated_after", "published_after": "published_after", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
})

export const getJob = defineFunction({
  name: "wttj_ats.get_job",
  connector: "wttj_ats",
  class: "read",
  description: "Get one job by its reference. With stages, embeds its pipeline as [{id, name, reference, visible, candidates_count}]: a stage is addressed by its integer id (its reference may be null), the id that create_candidate and update_candidate take as job_stage_id. Needs the jobs_r scope; candidates_count also needs candidates_r.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["reference"],
    "properties": {
      "reference": {"type": "string", "minLength": 1, "description": "Job reference."},
      "stages": {"type": "boolean", "description": "Embed the pipeline stages."},
      "office": {"type": "boolean", "description": "Embed the office."},
      "candidates_count": {"type": "boolean", "description": "Add the candidate counters, total and per stage."},
      "organization": {"type": "boolean", "description": "Embed the organization."},
      "websites": {"type": "boolean", "description": "Embed the websites where the job is visible."},
      "application_fields": {"type": "boolean", "description": "Embed the application form fields and their mode."}
    }
  },
  examples: [
    { title: "One job with its pipeline stages", input: {"reference": "ACME_Xy7kQ2", "stages": true, "candidates_count": true} },
  ],
  refusals: [
    { code: "job_not_found", when: 404, message: "No job with this reference is reachable with this token." },
  ],
  request: {
    method: "GET",
    path: "/jobs/{reference}",
    pathParams: ["reference"],
    query: {"stages": "stages", "office": "office", "candidates_count": "candidates_count", "organization": "organization", "websites": "websites", "application_fields": "application_fields"},
    body: {},
    headers: {},
  },
})

export const listCandidates = defineFunction({
  name: "wttj_ats.list_candidates",
  connector: "wttj_ats",
  class: "read",
  description: "List the candidates of one job, one page at a time: reference, stage id, profile (first name, last name, email, phone), cover letter, resume URL, origin, archived flag, dates. There is no cross-job listing: a job reference is required. The answer is a bare array with no total. Returns personal data. Needs the candidates_r scope (my_candidates_r only reaches the candidates this token created).",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["job_reference"],
    "properties": {
      "job_reference": {"type": "string", "minLength": 1},
      "email": {"type": "string", "description": "Only the candidate with this email."},
      "referrer": {"type": "string"},
      "origin": {"type": "string"},
      "job_stage_id": {"type": "integer", "description": "Only candidates at this stage (id from get_job with stages)."},
      "job_stage_reference": {"type": "string"},
      "archived": {"type": "boolean", "description": "true: archived only; false: active only."},
      "created_after": {"type": "string", "format": "date", "description": "YYYY-MM-DD."},
      "updated_after": {"type": "string", "format": "date", "description": "YYYY-MM-DD."},
      "stage": {"type": "boolean", "description": "Embed each candidate's stage object."},
      "tags": {"type": "boolean", "description": "Embed each candidate's tags."},
      "page": {"type": "integer", "minimum": 1},
      "per_page": {"type": "integer", "minimum": 1}
    }
  },
  examples: [
    { title: "Active candidates of one job at one stage", input: {"job_reference": "ACME_Xy7kQ2", "job_stage_id": 1234, "archived": false, "stage": true} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/candidates",
    pathParams: [],
    query: {"job_reference": "job_reference", "email": "email", "referrer": "referrer", "origin": "origin", "job_stage_id": "job_stage_id", "job_stage_reference": "job_stage_reference", "archived": "archived", "created_after": "created_after", "updated_after": "updated_after", "stage": "stage", "tags": "tags", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
})

export const getCandidate = defineFunction({
  name: "wttj_ats.get_candidate",
  connector: "wttj_ats",
  class: "read",
  description: "Get one candidate by its reference, same fields as a list item. Returns personal data. Needs the candidates_r scope.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["reference"],
    "properties": {
      "reference": {"type": "string", "minLength": 1, "description": "Candidate reference."},
      "stage": {"type": "boolean", "description": "Embed the stage object."},
      "tags": {"type": "boolean", "description": "Embed the tags."}
    }
  },
  examples: [
    { title: "One candidate with stage and tags", input: {"reference": "acme-0123456789abcdef01234567", "stage": true, "tags": true} },
  ],
  refusals: [
    { code: "candidate_not_found", when: 404, message: "No candidate with this reference is reachable with this token." },
  ],
  request: {
    method: "GET",
    path: "/candidates/{reference}",
    pathParams: ["reference"],
    query: {"stage": "stage", "tags": "tags"},
    body: {},
    headers: {},
  },
})

export const createCandidate = defineFunction({
  name: "wttj_ats.create_candidate",
  connector: "wttj_ats",
  class: "write",
  description: "Add a candidate to a job, at a given pipeline stage. job_stage_id is the integer id of a stage of this job (get_job with stages). Needs the candidates_rw or my_candidates_rw scope.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["organization_reference", "job_reference", "job_stage_id", "email", "firstname", "lastname"],
    "properties": {
      "organization_reference": {"type": "string", "minLength": 1},
      "job_reference": {"type": "string", "minLength": 1},
      "job_stage_id": {"type": "integer"},
      "email": {"type": "string", "minLength": 1},
      "firstname": {"type": "string", "minLength": 1},
      "lastname": {"type": "string", "minLength": 1},
      "phone": {"type": "string"},
      "subtitle": {"type": "string"},
      "tag_list": {"type": "string", "description": "Comma-separated tags."},
      "cover_letter": {"type": "string"},
      "comment": {"type": "string", "description": "A comment about this candidate."},
      "referrer": {"type": "string"},
      "archived": {"type": "boolean"},
      "remote_resume_url": {"type": "string", "description": "URL of the resume: PDF, DOC, DOCX or ODT, 5 MB at most."},
      "remote_image_url": {"type": "string", "description": "URL of the avatar."},
      "remote_portfolio_url": {"type": "string", "description": "URL of the portfolio: PDF, 10 MB at most."},
      "media_website": {"type": "string"},
      "media_linkedin": {"type": "string"},
      "media_github": {"type": "string"},
      "media_stackoverflow": {"type": "string"},
      "media_dribbble": {"type": "string"},
      "media_behance": {"type": "string"},
      "media_facebook": {"type": "string"},
      "media_instagram": {"type": "string"},
      "media_medium": {"type": "string"},
      "media_tumblr": {"type": "string"},
      "media_vimeo": {"type": "string"},
      "media_twitter": {"type": "string"}
    }
  },
  examples: [
    { title: "A candidate at the first stage of a job", input: {"organization_reference": "Ab12Cd3", "job_reference": "ACME_Xy7kQ2", "job_stage_id": 1234, "email": "jane.doe@example.com", "firstname": "Jane", "lastname": "Doe", "tag_list": "backend,referral"} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/candidates",
    pathParams: [],
    query: {},
    body: {"organization_reference": "organization_reference", "job_reference": "job_reference", "job_stage_id": "job_stage_id", "email": "email", "firstname": "firstname", "lastname": "lastname", "phone": "phone", "subtitle": "subtitle", "tag_list": "tag_list", "cover_letter": "cover_letter", "comment": "comment", "referrer": "referrer", "archived": "archived", "remote_resume_url": "remote_resume_url", "remote_image_url": "remote_image_url", "remote_portfolio_url": "remote_portfolio_url", "media_website": "media_website", "media_linkedin": "media_linkedin", "media_github": "media_github", "media_stackoverflow": "media_stackoverflow", "media_dribbble": "media_dribbble", "media_behance": "media_behance", "media_facebook": "media_facebook", "media_instagram": "media_instagram", "media_medium": "media_medium", "media_tumblr": "media_tumblr", "media_vimeo": "media_vimeo", "media_twitter": "media_twitter"},
    headers: {},
  },
})

export const updateCandidate = defineFunction({
  name: "wttj_ats.update_candidate",
  connector: "wttj_ats",
  class: "write",
  description: "Change a candidate: only the fields passed change. job_stage_id MOVES the candidate to that stage of its job (there is no dedicated move endpoint); archived true archives it. Needs the candidates_rw scope.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["reference"],
    "minProperties": 2,
    "properties": {
      "reference": {"type": "string", "minLength": 1, "description": "Candidate reference."},
      "job_stage_id": {"type": "integer", "description": "Move the candidate to this stage."},
      "archived": {"type": "boolean", "description": "true archives the candidate."},
      "email": {"type": "string", "minLength": 1},
      "firstname": {"type": "string", "minLength": 1},
      "lastname": {"type": "string", "minLength": 1},
      "phone": {"type": "string"},
      "subtitle": {"type": "string"},
      "tag_list": {"type": "string", "description": "Comma-separated tags."},
      "cover_letter": {"type": "string"},
      "comment": {"type": "string"},
      "referrer": {"type": "string"},
      "remote_resume_url": {"type": "string", "description": "URL of the resume: PDF, DOC, DOCX or ODT, 5 MB at most."},
      "remote_image_url": {"type": "string"},
      "remote_portfolio_url": {"type": "string", "description": "URL of the portfolio: PDF, 10 MB at most."},
      "media_website": {"type": "string"},
      "media_linkedin": {"type": "string"},
      "media_github": {"type": "string"},
      "media_stackoverflow": {"type": "string"},
      "media_dribbble": {"type": "string"},
      "media_behance": {"type": "string"},
      "media_facebook": {"type": "string"},
      "media_instagram": {"type": "string"},
      "media_medium": {"type": "string"},
      "media_tumblr": {"type": "string"},
      "media_vimeo": {"type": "string"},
      "media_twitter": {"type": "string"}
    }
  },
  examples: [
    { title: "Move a candidate to another stage", input: {"reference": "acme-0123456789abcdef01234567", "job_stage_id": 1240} },
    { title: "Archive a candidate", input: {"reference": "acme-0123456789abcdef01234567", "archived": true} },
  ],
  refusals: [
    { code: "nothing_to_update", when: "no field besides reference is given", message: "Give at least one field to change." },
    { code: "candidate_not_found", when: 404, message: "No candidate with this reference is reachable with this token." },
  ],
  request: {
    method: "PUT",
    path: "/candidates/{reference}",
    pathParams: ["reference"],
    query: {},
    body: {"job_stage_id": "job_stage_id", "archived": "archived", "email": "email", "firstname": "firstname", "lastname": "lastname", "phone": "phone", "subtitle": "subtitle", "tag_list": "tag_list", "cover_letter": "cover_letter", "comment": "comment", "referrer": "referrer", "remote_resume_url": "remote_resume_url", "remote_image_url": "remote_image_url", "remote_portfolio_url": "remote_portfolio_url", "media_website": "media_website", "media_linkedin": "media_linkedin", "media_github": "media_github", "media_stackoverflow": "media_stackoverflow", "media_dribbble": "media_dribbble", "media_behance": "media_behance", "media_facebook": "media_facebook", "media_instagram": "media_instagram", "media_medium": "media_medium", "media_tumblr": "media_tumblr", "media_vimeo": "media_vimeo", "media_twitter": "media_twitter"},
    headers: {},
  },
})

export const createComment = defineFunction({
  name: "wttj_ats.create_comment",
  connector: "wttj_ats",
  class: "write",
  description: "Add a comment on a candidate, as plain text, HTML or markdown. Comments are write-only in this API: none can be listed back. Needs the comments_w scope and candidates_rw or my_candidates_rw.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["candidate_reference", "content"],
    "properties": {
      "candidate_reference": {"type": "string", "minLength": 1},
      "content": {"type": "string", "minLength": 1, "pattern": "\\S", "description": "Plain text, HTML or markdown."}
    }
  },
  examples: [
    { title: "A comment after an interview", input: {"candidate_reference": "acme-0123456789abcdef01234567", "content": "Strong technical interview, next step: team meeting."} },
  ],
  refusals: [],
  request: {
    method: "POST",
    path: "/comments",
    pathParams: [],
    query: {},
    body: {"candidate_reference": "candidate_reference", "content": "content"},
    headers: {},
  },
})

export const listMoves = defineFunction({
  name: "wttj_ats.list_moves",
  connector: "wttj_ats",
  class: "read",
  description: "List the pipeline history of an organization, optionally of one job: each move is {candidate: {reference}, from: {stage, organization, job}, to: {stage, organization, job}, created_at}. A move can change stage, job or organization; a stage deleted after the move is not included. Needs the moves_r scope.",
  schema: {
    "type": "object",
    "additionalProperties": false,
    "required": ["organization_reference"],
    "properties": {
      "organization_reference": {"type": "string", "minLength": 1},
      "job_reference": {"type": "string", "description": "Only moves from or to this job."},
      "page": {"type": "integer", "minimum": 1},
      "per_page": {"type": "integer", "minimum": 1}
    }
  },
  examples: [
    { title: "Moves of one job", input: {"organization_reference": "Ab12Cd3", "job_reference": "ACME_Xy7kQ2"} },
  ],
  refusals: [],
  request: {
    method: "GET",
    path: "/moves",
    pathParams: [],
    query: {"organization_reference": "organization_reference", "job_reference": "job_reference", "page": "page", "per_page": "per_page"},
    body: {},
    headers: {},
  },
})

export const connector = defineConnector({
  name: "wttj_ats",
  label: "Welcome to the Jungle ATS",
  namespace: "wttj_ats",
  version: "1.0.0",
  apiVersion: "v1 external",
  baseUrl: "https://www.welcomekit.co/api/v1/external",
  auth: {"kind": "bearer", "token": "api_key"},
  credential: [{"name": "api_key", "label": "API token", "secret": true}],
  modes: ["byo_user", "byo_org"],
  timeoutMs: 60000,
  errors: [
    { status: 400, code: "invalid_request", message: "Welcome to the Jungle rejected the request as invalid (validation_failed): check the arguments.", retryable: false },
    { status: 401, code: "access_rejected", message: "Welcome to the Jungle rejected the API token: it is wrong or revoked.", retryable: false },
    { status: 403, code: "forbidden", message: "Welcome to the Jungle refused access: the token lacks the scope this call needs (invalid_scope), or the resource is not reachable with it.", retryable: false },
    { status: 404, code: "not_found", message: "Welcome to the Jungle found no resource with this reference.", retryable: false },
    { status: 429, code: "rate_limited", message: "Too many requests to Welcome to the Jungle: retry in a moment.", retryable: true },
    { status: [500, 502, 503, 504], code: "upstream_unavailable", message: "Welcome to the Jungle is temporarily unavailable: retry later.", retryable: true },
  ],
  functions: [
    getCurrentUser,
    getOrganization,
    listJobs,
    getJob,
    listCandidates,
    getCandidate,
    createCandidate,
    updateCandidate,
    createComment,
    listMoves,
  ],
})
